import { CarTypeEnum } from "../../car-type.enum";
import { CarInfoInterface } from "../../interfaces";

export class ToyotaFortuner implements CarInfoInterface {
  name = 'Toyota Fortuner'
  type = CarTypeEnum.XeSuv
  imgSrc = 'assets/img/cars/Fortuner.png'
  banner = 'assets/img/toyota/fortuner/banner.jpg'
  models = [
    {
      brand: 'Toyota Fortuner 2.4AT 4x2',
      price: 1080000000,
      seats: 7,
      type: 'SUV',
      fuelType: 'Dầu',
      manufacture: 'Xe trong nước',
      otherInfo: ['Số tự động 6 cấp/6AT'],
      library:[
        '/assets/img/toyota/fortuner/library/1i4ixg.jpg',
        '/assets/img/toyota/fortuner/library/jgf1ww.jpg',
        '/assets/img/toyota/fortuner/library/xxgjfk.jpg'
      ],
      promotion: [
        `Gói ưu đãi bảo hiểm vàng Toyota trị giá lên đến 19.4 triệu đồng.
        (Áp dụng cho dòng xe Fortuner Legender từ ngày 01/10/2021 đến ngày 31/10/2021)`
        
      ],
      colors: [
        {
          label: 'Đen - 218',
          image: '/assets/img/toyota/fortuner/colors/2.4AT 4X2/01_Den.png',
          colorCode: 'black' 
        },
        {
          label: 'Trắng ngọc trai - 089',
          image: '/assets/img/toyota/fortuner/colors/2.4AT 4X2/01_Trang.png',
          colorCode: '#f7f9fa'
        },
        {
          label: 'Bạc - 1D6',
          image: '/assets/img/toyota/fortuner/colors/2.4AT 4X2/01_Bac.png',
          colorCode: '#c4c4c4'
        },
        {
          label: 'Đồng - 4V8',
          image: '/assets/img/toyota/fortuner/colors/2.4AT 4X2/01_Dong.png',
          colorCode: '#908b85'
        },
        {
          label: 'Nâu - 4W9',
          image: '/assets/img/toyota/fortuner/colors/2.4AT 4X2/01_Nau.png',
          colorCode: '#513e3a'
        }
      ],
      ngoaiThat: {
        label: 'MẠNH MẼ ĐẦY CUỐN HÚT',
        backgroundImage: '/assets/img/toyota/wigo/ngoai-that/0.png',
        image: '/assets/img/toyota/fortuner/ngoai-that/hcycd3.jpg',
        features: [
          {
            image: '/assets/img/toyota/fortuner/ngoai-that/0tbgq1.jpg',
            label: 'Mâm xe'
          },
          {
            image: '/assets/img/toyota/fortuner/ngoai-that/0tfbdj.jpg',
            label: 'Gương chiếu hậu bên ngoài'
          },
          {
            image: '/assets/img/toyota/fortuner/ngoai-that/l1wlxl.jpg',
            label: 'cụm đèn trước'
          },
          {
            image: '/assets/img/toyota/fortuner/ngoai-that/sfeik3.jpg',
            label: 'Đầu xe'
          },
          {
            image: '/assets/img/toyota/fortuner/ngoai-that/t1ijov.jpg',
            label: 'Cụm đèn sau'
          }
        ]
      },
      noiThat: {
        label: 'HOÀN HẢO, TIỆN NGHI VƯỢT TRỘI',
        backgroundImage: '/assets/img/toyota/wigo/noi-that/0.png',
        image: '/assets/img/toyota/fortuner/noi-that/l0ggnf.jpg',
        features: [
          {
            image: '/assets/img/toyota/fortuner/noi-that/04jtqs.jpg',
            label: 'Hệ thống điều hòa'
          },
          {
            image: '/assets/img/toyota/fortuner/noi-that/btiuxb.jpg',
            label: 'Hộp đựng mắt kính'
          },
          {
            image: '/assets/img/toyota/fortuner/noi-that/dgyi54.jpg',
            label: 'Hộp để đồ có khả năng làm mát'
          },
          {
            image: '/assets/img/toyota/fortuner/noi-that/ekc0ms.jpg',
            label: 'Hệ thống âm thanh'
          },
          {
            image: '/assets/img/toyota/fortuner/noi-that/xy0wfx.jpg',
            label: 'Bảng đồng hồ táp lô'
          },
          {
            image: '/assets/img/toyota/fortuner/noi-that/p5mnrb.jpg',
            label: 'Nút bấm khởi động'
          },
          {
            image: '/assets/img/toyota/fortuner/noi-that/j5zxni.jpg',
            label: 'Không gian nội thất'
          }
        ]
      },
      tinhNang:[
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/0txutn.jpg",
          title: "Động cơ",
          message: "Ở 2 phiên bản 2.8L, với những tinh chỉnh trong thiết kế, giúp động cơ của Fortuner thuộc TOP động cơ mạnh nhất phân khúc khi công suất đạt 201 hp / 3400 v/p (tăng 17 hp) và mô men xoắn đạt 500 Nm / 1600 v/p. Với công nghệ mới giúp tiết kiệm nhiên liệu và giảm tiếng ồn từ động cơ."
        },
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/2dg1zv.jpg",
          title: "Hộp số",
          message: "Hộp số tự động 6 cấp giúp chuyển số nhịp nhàng, tăng tốc tốt hơn, vận hành mượt mà hơn, và tiết kiệm nhiên liệu hơn."
        },
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/axbhm3.jpg",
          title: "Camera lùi",
          message: "Camera lùi tăng khả năng quan sát chướng ngại vật giúp người lái an tâm hơn khi lùi xe."
        },
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/c4hyod.jpg",
          title: "Hệ thông kiểm soát lực kéo",
          message: "Hệ thống A-TRC tác động lên công suất động cơ và lực phanh ở mỗi bánh xe, nhờ đó giúp chiếc xe có thể dễ dàng tăng tốc và khởi hành rên đường trơn trượt."
        },
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/ds4kss.jpg",
          title: "Hệ thống khởi hành ngang dốc (HAC)",
          message: "Khi người lái chuyển từ chân phanh sang chân ga để khởi hành ngang dốc, hệ thống HAC sẽ tự động tác ộng phanh tới cả 4 bánh xe trong vòng khoảng 2 giây, nhờ đó giúp chiếc xe không bị trôi dốc và dễ dàng khởi hành hơn."
        },
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/enntff.jpg",
          title: "Hệ thống chống bó cứng phanh (ABS)",
          message: "Khi được kích hoạt bằng cách đạp phanh dứt khoát, hệ thống chống bó cứng phanh ABS sẽ tự động nhấp nhả phanh liên tục, giúp các bánh xe không bị bó cứng, cho phép người lái duy trì khả năng điều khiển xe tránh chướng ngại vật và đảm bảo ổn định thân xe."
        },
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/f3sqmn.jpg",
          title: "Hệ thống túi khí",
          message: "Fortuner thế hệ đột phá được trang bị hệ thống túi khí hiện đại giúp giảm thiểu tối đa chấn thương cho người lái và hành khách trong trường hợp không may xảy ra va chạm."
        },
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/gjjop4.jpg",
          title: "Hệ thống hỗ trợ lực phanh khẩn cấp BA",
          message: "Hệ thống hỗ trợ lực phanh khẩn cấp BA tự động gia tăng thêm lực phanh trong trường hợp khẩn cấp, giúp người lái tự tin xử lý các tình huống bất ngờ."
        },
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/i0cq4w.jpg",
          title: "Tính năng nháy đèn khi phanh khẩn cấp (EBS)",
          message: "Đèn cảnh báo nguy hiểm của xe sẽ tự động nháy sáng trong tình huống người lái phanh gấp. Nhờ đó sẽ cảnh báo cho các xe phía sau kịp thời xử lý để tránh xảy ra va chạm."
        },
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/kkgtxu.jpg",
          title: "Hệ thống kiểm soát móc kéo",
          message: "Hệ thống kiểm soát móc kéo giúp đảm bảo tính ma sát của bề mặt lốp xe với mặt đường giúp tăng cường khả năng ổn định thân xe khi kéo thêm móc phía sau."
        },
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/knbszx.jpg",
          title: "Khung xe GOA",
          message: "Khung xe có các vùng co rụm phía trước, phía sau giúp hấp thụ tốt các xung lực va đập, ngoài ra các thanh tăng cứng bên sườn xe làm giảm biến dạng khoang hành khách, giảm thiểu chấn thương trong trường hợp không may xảy ra va chạm."
        },
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/m2skvh.jpg",
          title: "Khung gầm",
          message: "Khung gầm kiên cố, chắc chắn, đích thực là chiếc SUV đẳng cấp."
        },
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/px0ibr.jpg",
          title: "Đèn báo phanh trên cao",
          message: "Đèn báo phanh trên cao sử dụng công nghệ LED giúp tăng cường tín hiệu cảnh báo khi phanh đối với phương tiện hoặc người đi đường di chuyển phía sau xe, tránh những va chạm bất ngờ có thể xảy ra."
        },
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/q3xwfs.jpg",
          title: "Hệ thống cân bằng điện tử (VSC)",
          message: "Hệ thống VSC kiểm soát công suất động cơ và phân bổ lực phanh hợp lý tới từng bánh xe, nhờ đó giảm thiểu nguy cơ mất lái và trượt bánh xe đặc biệt trên các cung đường trơn trượt hay khi vào cua gấp."
        },
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/scsr51.jpg",
          title: "Hệ thống phân phối lực phanh điện tử EBD",
          message: "Hệ thống phân phối lực phanh điện tử EBD phân bổ lực phanh hợp lý lên các bánh xe, giúp nâng cao hiệu quả phanh, đặc biệt khi xe đang chất tải và vào cua."
        },
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/vdaagj.jpg",
          title: "Hệ thống treo",
          message: "Hệ thống treo với tay đòn kép ở phía trước và liên kết bốn điểm ở phía sau nhằm giảm tối đa độ rung lắc,cho cảm giác lái êm mượt dễ chịu dù trên những địa hình gồ ghề nhất."
        },
        {
          image: "/assets/img/toyota/fortuner/tinh-nang/yvt2s1.jpg",
          title: "Chế độ lái",
          message: "Tuỳ vào hành trình di chuyển, chủ sở hữu có thể chọn chế độ ECO giúp tối ưu hóa tính năng tiết kiệm  nhiên liệu; và chế độ POWER giúp tối ưu hóa tính năng vận hành (vượt xe, vượt dốc, chở tải)."
        }
      ],
      thongSo: [
        {label:"	Kích thước Kích thước tổng thể bên ngoài (D x R x C) (mm x mm x mm)		",value:"	4795 x 1855 x 1835	"},
        {label:"	Chiều dài cơ sở (mm)		",value:"	2745	"},
        {label:"	Chiều rộng cơ sở (Trước / sau) (mm)		",value:"	1545 / 1555	"},
        {label:"	Khoảng sáng gầm xe (mm)		",value:"	279	"},
        {label:"	Bán kính vòng quay tối thiểu (m)		",value:"	5.8	"},
        {label:"	Trọng lượng không tải (kg)		",value:"	2000	"},
        {label:"	Trọng lượng toàn tải (kg)		",value:"	2605	"},
        {label:"	Dung tích bình nhiên liệu (L)		",value:"	80	"},
        {label:"	Động cơ xăng Loại động cơ		",value:"	2GD-FTV (2.4L)	"},
        {label:"	Số xy lanh		",value:"	4	"},
        {label:"	Bố trí xy lanh		",value:"	Thẳng hàng / In line	"},
        {label:"	Dung tích xy lanh (cc)		",value:"	2393	"},
        {label:"	Hệ thống nhiên liệu		",value:"	Phun nhiên liệu trực tiếp sử dụng đường ống dẫn chung, tăng áp biến thiên / Common rail direct injection & Variable nozzle turborcharger (VNT)	"},
        {label:"	Loại nhiên liệu		",value:"	Dầu / Diesel	"},
        {label:"	Công suất tối đa ((KW) HP / vòng / phút)		",value:"	110 (147) / 3400	"},
        {label:"	Mô men xoắn tối đa (Nm / vòng / phút)		",value:"	400 / 1600	"},
        {label:"	Tốc độ tối đa		",value:"	170	"},
        {label:"	Chế độ lái (công suất cao / tiết kiệm nhiên liệu)  		",value:"	Có / With	"},
        {label:"	Hệ thống truyền động  		",value:"	Dẫn động cầu sau / RWD	"},
        {label:"	Hộp số  		",value:"	Số tự động 6 cấp / 6AT	"},
        {label:"	Hệ thống treo Trước		",value:"	Độc lập, tay đòn kép với thanh cân bằng / Double wishbone with torsion bar	"},
        {label:"	Sau		",value:"	Phụ thuộc, liên kết 4 điểm / Four links with torsion bar	"},
        {label:"	Hệ thống lái Trợ lực tay lái		",value:"	Thủy lực biến thiên theo tốc độ / Hydraulic (VFC)	"},
        {label:"	Hệ thống tay lái tỉ số truyền biến thiên (VGRS)		",value:"	Không có / Without	"},
        {label:"	Vành & lốp xe Loại vành		",value:"	Mâm đúc / Alloy	"},
        {label:"	Kích thước lốp		",value:"	265 / 65R17	"},
        {label:"	Lốp dự phòng		",value:"	Mâm đúc / Alloy	"},
        {label:"	Phanh Trước		",value:"	Đĩa tản nhiệt / Ventilated disc	"},
        {label:"	Sau		",value:"	Đĩa / Disc	"},
        {label:"	Tiêu chuẩn khí thải  		",value:"	Euro 4	"},
        {label:"	Tiêu thụ nhiên liệu Trong đô thị (L / 100km)		",value:"	9.05	"},
        {label:"	Ngoài đô thị (L / 100km)		",value:"	6.79	"},
        {label:"	Kết hợp (L / 100km)		",value:"	7.63	"},
        {label:"	Cụm đèn trước Đèn chiếu gần		",value:"	LED	"},
        {label:"	Đèn chiếu xa		",value:"	LED	"},
        {label:"	Đèn chiếu sáng ban ngày		",value:"	Có / With	"},
        {label:"	Chế độ điều khiển đèn tự động		",value:"	Có / With	"},
        {label:"	Hệ thống cân bằng góc chiếu		",value:"	Tự động / Auto (ALS)	"},
        {label:"	Chế độ đèn chờ dẫn đường		",value:"	Có / With	"},
        {label:"	Cụm đèn sau  		",value:"	LED	"},
        {label:"	Đèn báo phanh trên cao  		",value:"	LED	"},
        {label:"	Đèn sương mù Trước		",value:"	LED	"},
        {label:"	Sau		",value:"	Không có / Without	"},
        {label:"	Gương chiếu hậu ngoài Chức năng điều chỉnh điện		",value:"	Có / With	"},
        {label:"	Chức năng gập điện		",value:"	Có / With	"},
        {label:"	Tích hợp đèn chào mừng		",value:"	Không có / Without	"},
        {label:"	Tích hợp đèn báo rẽ		",value:"	Có / With	"},
        {label:"	Màu		",value:"	Cùng màu thân xe / Colored	"},
        {label:"	Gạt mưa Trước		",value:"	Gián đoạn, điều chỉnh thời gian / Intermittent & Time adjustment	"},
        {label:"	Sau		",value:"	Có (gián đoạn) / With (intermittent)	"},
        {label:"	Chức năng sấy kính sau  		",value:"	Có / With	"},
        {label:"	Ăng ten  		",value:"	Dạng vây cá / Shark fin	"},
        {label:"	Tay nắm cửa ngoài  		",value:"	Mạ crôm / Chrome plating	"},
        {label:"	Bộ quây xe thể thao  		",value:"	Không có / Without	"},
        {label:"	Thanh cản (giảm va chạm) Trước		",value:"	Có / With	"},
        {label:"	Sau		",value:"	Có / With	"},
        {label:"	Chắn bùn  		",value:"	Trước + Sau / Front + Rear	"},
        {label:"	Ống xả kép  		",value:"	Không có / Without	"},
        {label:"	Tay lái Loại tay lái		",value:"	3 chấu / 3-spoke	"},
        {label:"	Chất liệu		",value:"	Bọc da, ốp gỗ, mạ bạc / Leather, wood, silver ornamentation	"},
        {label:"	Nút bấm điều khiển tích hợp		",value:"	Điều chỉnh âm thanh, màn hình hiển thị đa thông tin, đàm thoại rảnh tay / Audio switch, MID, hands-free phone	"},
        {label:"	Điều chỉnh		",value:"	Chỉnh tay 4 hướng / Manual tilt & telescopic	"},
        {label:"	Lẫy chuyển số		",value:"	Có / With	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Gương chiếu hậu trong  		",value:"	Chống chói tự động / EC	"},
        {label:"	Tay nắm cửa trong  		",value:"	Mạ crôm / Chrome plating	"},
        {label:"	Cụm đồng hồ Loại đồng hồ		",value:"	Optitron	"},
        {label:"	Đèn báo Eco		",value:"	Có / With	"},
        {label:"	Chức năng báo lượng tiêu thụ nhiên liệu		",value:"	Có / With	"},
        {label:"	Chức năng báo vị trí cần số		",value:"	Có / With	"},
        {label:"	Màn hình hiển thị đa thông tin		",value:"	Có (màn hình màu TFT 4.2) / With (color TFT 4.2)	"},
        {label:"	Chất liệu bọc ghế  		",value:"	Da / Leather	"},
        {label:"	Ghế trước Loại ghế		",value:"	Loại thể thao / Sport type	"},
        {label:"	Điều chỉnh ghế lái		",value:"	Chỉnh điện 8 hướng / 8 way power	"},
        {label:"	Điều chỉnh ghế hành khách		",value:"	Chỉnh điện 8 hướng / 8 way power	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Chức năng thông gió		",value:"	Không có / Without	"},
        {label:"	Chức năng sưởi		",value:"	Không có / Without	"},
        {label:"	Ghế sau Hàng ghế thứ hai		",value:"	Gập lưng ghế 60:40 một chạm, chỉnh cơ 4 hướng / 60:40 split fold, manual slide & reclining	"},
        {label:"	Hàng ghế thứ ba		",value:"	Ngả lưng ghế, gập 50:50 sang 2 bên / Manual reclining, 50:50 tumble, space up	"},
        {label:"	Tựa tay hàng ghế sau		",value:"	Có / With	"},
        {label:"	Hệ thống điều hòa  		",value:"	Tự động, 2 giàn lạnh / Auto, dual cooler	"},
        {label:"	Cửa gió sau  		",value:"	Có / With	"},
        {label:"	Hộp làm mát  		",value:"	Có / With	"},
        {label:"	Hệ thống âm thanh Đầu đĩa		",value:"	DVD cảm ứng 7 / 7 touch screen DVD	"},
        {label:"	Số loa		",value:"	6	"},
        {label:"	Cổng kết nối AUX		",value:"	Có / With	"},
        {label:"	Cổng kết nối USB		",value:"	Có / With	"},
        {label:"	Kết nối Bluetooth		",value:"	Có / With	"},
        {label:"	Kết nối điện thoại thông minh / Smartphone connectivity		",value:"	Không có / Without	"},
        {label:"	Chìa khóa thông minh & Khởi động bằng nút bấm  		",value:"	Có / With	"},
        {label:"	Khóa cửa điện  		",value:"	Có / With	"},
        {label:"	Chức năng khóa cửa từ xa  		",value:"	Có / With	"},
        {label:"	Cửa sổ điều chỉnh điện  		",value:"	Có (1 chạm, chống kẹt tất cả các cửa) / With (Auto, jam protection for all windows)	"},
        {label:"	Cốp điều khiển điện  		",value:"	Không có / Without	"},
        {label:"	Hệ thống điều khiển hành trình  		",value:"	Có / With	"},
        {label:"	Hệ thống báo động  		",value:"	Có / With	"},
        {label:"	Hệ thống mã hóa khóa động cơ  		",value:"	Có / With	"},
        {label:"	Hệ thống an toàn Toyota (Toyota Safety Sense) Cảnh báo tiền va chạm (PCS)		",value:"	Không có / Without	"},
        {label:"	Cảnh báo chệch làn đường (LDA)		",value:"	Không có / Without	"},
        {label:"	Điều khiển hành trình chủ động (DRCC)		",value:"	Không có / Without	"},
        {label:"	Hệ thống chống bó cứng phanh (ABS)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ lực phanh khẩn cấp (BA)  		",value:"	Có / With	"},
        {label:"	Hệ thống phân phối lực phanh điện tử (EBD)  		",value:"	Có / With	"},
        {label:"	Hệ thống cân bằng điện tử (VSC)  		",value:"	Có / With	"},
        {label:"	Hệ thống kiểm soát lực kéo (TRC)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ khởi hành ngang dốc (HAC)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ đổ đèo (DAC)  		",value:"	Không có / Without	"},
        {label:"	Đèn báo phanh khẩn cấp (EBS)  		",value:"	Có / With	"},
        {label:"	Camera  		",value:"	Camera lùi / Back camera	"},
        {label:"	Cảm biến hỗ trợ đỗ xe Sau		",value:"	Có / With	"},
        {label:"	Góc trước		",value:"	Có / With	"},
        {label:"	Góc sau		",value:"	Có / With	"},
        {label:"	Túi khí Túi khí người lái & hành khách phía trước		",value:"	Có / With	"},
        {label:"	Túi khí bên hông phía trước		",value:"	Có / With	"},
        {label:"	Túi khí rèm		",value:"	Có / With	"},
        {label:"	Túi khí đầu gối người lái		",value:"	Có / With	"},
        {label:"	Khung xe GOA  		",value:"	Có / With	"},
        {label:"	Dây đai an toàn  		",value:"	3 điểm ELR, 7 vị trí / 3 points ELRx7	"},
        {label:"	Ghế có cấu trúc giảm chấn thương cổ  		",value:"	Có / With	"},
        {label:"	Cột lái tự đổ  		",value:"	Có / With	"},
        {label:"	Bàn đạp phanh tự đổ  		",value:"	Có / With	"}
      ]
      },
      {
        brand: 'Toyota Fortuner 2.4MT 4x2',
        price: 995000000,
        otherInfo: ['Số sàn 6 cấp/6MT'],
        thongSo:[
          {label:"	Kích thước Kích thước tổng thể bên ngoài (D x R x C) (mm x mm x mm)		",value:"	4795 x 1855 x 1835	"},
          {label:"	Chiều dài cơ sở (mm)		",value:"	2745	"},
          {label:"	Chiều rộng cơ sở (Trước / sau) (mm)		",value:"	1545 / 1555	"},
          {label:"	Khoảng sáng gầm xe (mm)		",value:"	279	"},
          {label:"	Góc thoát (Trước / Sau) (độ / degree)		",value:"	29 / 25	"},
          {label:"	Bán kính vòng quay tối thiểu (m)		",value:"	5.8	"},
          {label:"	Trọng lượng không tải (kg)		",value:"	1985	"},
          {label:"	Trọng lượng toàn tải (kg)		",value:"	2605	"},
          {label:"	Dung tích bình nhiên liệu (L)		",value:"	80	"},
          {label:"	Động cơ xăng Loại động cơ		",value:"	2GD-FTV (2.4L)	"},
          {label:"	Số xy lanh		",value:"	4	"},
          {label:"	Bố trí xy lanh		",value:"	Thẳng hàng / In line	"},
          {label:"	Dung tích xy lanh (cc)		",value:"	2393	"},
          {label:"	Hệ thống nhiên liệu		",value:"	Phun nhiên liệu trực tiếp sử dụng đường ống dẫn chung, tăng áp biến thiên / Common rail direct injection & Variable nozzle turborcharger (VNT)	"},
          {label:"	Loại nhiên liệu		",value:"	Dầu / Diesel	"},
          {label:"	Công suất tối đa ((KW) HP / vòng / phút)		",value:"	110 (147) / 3400	"},
          {label:"	Mô men xoắn tối đa (Nm / vòng / phút)		",value:"	400 / 1600	"},
          {label:"	Tốc độ tối đa		",value:"	175	"},
          {label:"	Chế độ lái (công suất cao / tiết kiệm nhiên liệu)  		",value:"	Có / With	"},
          {label:"	Hệ thống truyền động  		",value:"	Dẫn động cầu sau / RWD	"},
          {label:"	Hộp số  		",value:"	Số sàn 6 cấp / 6MT	"},
          {label:"	Hệ thống treo Trước		",value:"	Độc lập, tay đòn kép với thanh cân bằng / Double wishbone with torsion bar	"},
          {label:"	Sau		",value:"	Phụ thuộc, liên kết 4 điểm / Four links with torsion bar	"},
          {label:"	Hệ thống lái Trợ lực tay lái		",value:"	Thủy lực biến thiên theo tốc độ / Hydraulic (VFC)	"},
          {label:"	Hệ thống tay lái tỉ số truyền biến thiên (VGRS)		",value:"	Không có / Without	"},
          {label:"	Vành & lốp xe Loại vành		",value:"	Mâm đúc / Alloy	"},
          {label:"	Kích thước lốp		",value:"	265 / 65R17	"},
          {label:"	Lốp dự phòng		",value:"	Mâm đúc / Alloy	"},
          {label:"	Phanh Trước		",value:"	Đĩa tản nhiệt / Ventilated disc	"},
          {label:"	Sau		",value:"	Đĩa / Disc	"},
          {label:"	Tiêu chuẩn khí thải  		",value:"	Euro 4	"},
          {label:"	Tiêu thụ nhiên liệu Trong đô thị (L / 100km)		",value:"	8.65	"},
          {label:"	Ngoài đô thị (L / 100km)		",value:"	6.09	"},
          {label:"	Kết hợp (L / 100km)		",value:"	7.03	"},
          {label:"			",value:"		"},
          {label:"	Cụm đèn trước Đèn chiếu gần		",value:"	LED	"},
          {label:"	Đèn chiếu xa		",value:"	LED	"},
          {label:"	Đèn chiếu sáng ban ngày		",value:"	Có / With	"},
          {label:"	Chế độ điều khiển đèn tự động		",value:"	Có / With	"},
          {label:"	Hệ thống cân bằng góc chiếu		",value:"	Tự động / Auto (ALS)	"},
          {label:"	Chế độ đèn chờ dẫn đường		",value:"	Có / With	"},
          {label:"	Cụm đèn sau  		",value:"	LED	"},
          {label:"	Đèn báo phanh trên cao  		",value:"	LED	"},
          {label:"	Đèn sương mù Trước		",value:"	LED	"},
          {label:"	Sau		",value:"	Không có / Without	"},
          {label:"	Gương chiếu hậu ngoài Chức năng điều chỉnh điện		",value:"	Có / With	"},
          {label:"	Chức năng gập điện		",value:"	Có / With	"},
          {label:"	Tích hợp đèn chào mừng		",value:"	Không có / Without	"},
          {label:"	Tích hợp đèn báo rẽ		",value:"	Có / With	"},
          {label:"	Màu		",value:"	Cùng màu thân xe / Colored	"},
          {label:"	Gạt mưa Trước		",value:"	Gián đoạn, điều chỉnh thời gian / Intermittent & Time adjustment	"},
          {label:"	Sau		",value:"	Có (gián đoạn) / With (intermittent)	"},
          {label:"	Chức năng sấy kính sau  		",value:"	Có / With	"},
          {label:"	Ăng ten  		",value:"	Dạng vây cá / Shark fin	"},
          {label:"	Tay nắm cửa ngoài  		",value:"	Cùng màu thân xe / Colored	"},
          {label:"	Bộ quây xe thể thao  		",value:"	Không có / Without	"},
          {label:"	Thanh cản (giảm va chạm) Trước		",value:"	Có / With	"},
          {label:"	Sau		",value:"	Có / With	"},
          {label:"	Chắn bùn  		",value:"	Trước + Sau / Front + Rear	"},
          {label:"	Ống xả kép  		",value:"	Không có / Without	"},
          {label:"			",value:"		"},
          {label:"	Tay lái Loại tay lái		",value:"	3 chấu / 3-spoke	"},
          {label:"	Chất liệu		",value:"	Urethane	"},
          {label:"	Nút bấm điều khiển tích hợp		",value:"	Điều chỉnh âm thanh, màn hình hiển thị đa thông tin, đàm thoại rảnh tay / Audio switch, MID, hands-free phone	"},
          {label:"	Điều chỉnh		",value:"	Chỉnh tay 4 hướng / Manual tilt & telescopic	"},
          {label:"	Lẫy chuyển số		",value:"	Không có / Without	"},
          {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
          {label:"	Gương chiếu hậu trong  		",value:"	2 chế độ ngày và đêm / Day & night	"},
          {label:"	Tay nắm cửa trong  		",value:"	Mạ crôm / Chrome plating	"},
          {label:"	Cụm đồng hồ Loại đồng hồ		",value:"	Analog	"},
          {label:"	Đèn báo Eco		",value:"	Có / With	"},
          {label:"	Chức năng báo lượng tiêu thụ nhiên liệu		",value:"	Có / With	"},
          {label:"	Chức năng báo vị trí cần số		",value:"	Không có / Without	"},
          {label:"	Màn hình hiển thị đa thông tin		",value:"	Có (màn hình màu TFT 4.2) / With (color TFT 4.2)	"},
          {label:"			",value:"		"},
          {label:"	Chất liệu bọc ghế  		",value:"	Nỉ / Fabric	"},
          {label:"	Ghế trước Loại ghế		",value:"	Loại thể thao / Sport type	"},
          {label:"	Điều chỉnh ghế lái		",value:"	Chỉnh tay 6 hướng / 6 way manual	"},
          {label:"	Điều chỉnh ghế hành khách		",value:"	Chỉnh tay 4 hướng / 4 way manual	"},
          {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
          {label:"	Chức năng thông gió		",value:"	Không có / Without	"},
          {label:"	Chức năng sưởi		",value:"	Không có / Without	"},
          {label:"	Ghế sau Hàng ghế thứ hai		",value:"	Gập lưng ghế 60:40 một chạm, chỉnh cơ 4 hướng / 60:40 split fold, manual slide & reclining	"},
          {label:"	Hàng ghế thứ ba		",value:"	Ngả lưng ghế, gập 50:50 sang 2 bên / Manual reclining, 50:50 tumble, space up	"},
          {label:"	Tựa tay hàng ghế sau		",value:"	Có / With	"},
          {label:"			",value:"		"},
          {label:"	Hệ thống điều hòa  		",value:"	Chỉnh tay, 2 giàn lạnh / Manual, dual cooler	"},
          {label:"	Cửa gió sau  		",value:"	Có / With	"},
          {label:"	Hộp làm mát  		",value:"	Có / With	"},
          {label:"	Hệ thống âm thanh Đầu đĩa		",value:"	DVD cảm ứng 7 / 7 touch screen DVD	"},
          {label:"	Số loa		",value:"	6	"},
          {label:"	Cổng kết nối AUX		",value:"	Có / With	"},
          {label:"	Cổng kết nối USB		",value:"	Có / With	"},
          {label:"	Kết nối Bluetooth		",value:"	Có / With	"},
          {label:"	Kết nối điện thoại thông minh / Smartphone connectivity		",value:"	Không có / Without	"},
          {label:"	Chìa khóa thông minh & Khởi động bằng nút bấm  		",value:"	Không có / Without	"},
          {label:"	Khóa cửa điện  		",value:"	Có / With	"},
          {label:"	Chức năng khóa cửa từ xa  		",value:"	Có / With	"},
          {label:"	Cửa sổ điều chỉnh điện  		",value:"	Có (1 chạm, chống kẹt bên người lái) / With (Auto, jam protection for driver window)	"},
          {label:"	Cốp điều khiển điện  		",value:"	Không có / Without	"},
          {label:"	Hệ thống điều khiển hành trình  		",value:"	Không có / Without	"},
          {label:"			",value:"		"},
          {label:"	Hệ thống báo động  		",value:"	Có / With	"},
          {label:"	Hệ thống mã hóa khóa động cơ  		",value:"	Có / With	"},
          {label:"			",value:"		"},
          {label:"	Hệ thống an toàn Toyota (Toyota Safety Sense) Cảnh báo tiền va chạm (PCS)		",value:"	Không có / Without	"},
          {label:"	Cảnh báo chệch làn đường (LDA)		",value:"	Không có / Without	"},
          {label:"	Điều khiển hành trình chủ động (DRCC)		",value:"	Không có / Without	"},
          {label:"	Hệ thống chống bó cứng phanh (ABS)  		",value:"	Có / With	"},
          {label:"	Hệ thống hỗ trợ lực phanh khẩn cấp (BA)  		",value:"	Có / With	"},
          {label:"	Hệ thống cân bằng điện tử (VSC)  		",value:"	Có / With	"},
          {label:"	Hệ thống kiểm soát lực kéo (TRC)  		",value:"	Có / With	"},
          {label:"	Hệ thống hỗ trợ khởi hành ngang dốc (HAC)  		",value:"	Có / With	"},
          {label:"	Hệ thống hỗ trợ đổ đèo (DAC)  		",value:"	Không có / Without	"},
          {label:"	Đèn báo phanh khẩn cấp (EBS)  		",value:"	Có / With	"},
          {label:"	Camera  		",value:"	Camera lùi / Back camera	"},
          {label:"	Cảm biến hỗ trợ đỗ xe Sau		",value:"	Có / With	"},
          {label:"	Góc trước		",value:"	Có / With	"},
          {label:"	Góc sau		",value:"	Có / With	"},
          {label:"			",value:"		"},
          {label:"	Túi khí Túi khí người lái & hành khách phía trước		",value:"	Có / With	"},
          {label:"	Túi khí bên hông phía trước		",value:"	Có / With	"},
          {label:"	Túi khí rèm		",value:"	Có / With	"},
          {label:"	Túi khí đầu gối người lái		",value:"	Có / With	"},
          {label:"	Khung xe GOA  		",value:"	Có / With	"},
          {label:"	Dây đai an toàn  		",value:"	3 điểm ELR, 7 vị trí / 3 points ELRx7	"},
          {label:"	Ghế có cấu trúc giảm chấn thương cổ  		",value:"	Có / With	"},
          {label:"	Cột lái tự đổ  		",value:"	Có / With	"},
          {label:"	Bàn đạp phanh tự đổ  		",value:"	Có / With	"}
        ]
      },
      {
        brand: 'Toyota Fortuner 2.7AT 4x2',
        price: 1130000000,
        fuelType: 'Xăng',
        manufacture: 'Xe nhập khẩu',
        otherInfo: ['Số tự động 6 cấp'],
        thongSo:[
          {label:"	Kích thước Kích thước tổng thể bên ngoài (D x R x C) (mm x mm x mm)		",value:"	4795 x 1855 x 1835	"},
          {label:"	Chiều dài cơ sở (mm)		",value:"	2745	"},
          {label:"	Chiều rộng cơ sở (Trước / sau) (mm)		",value:"	1545 / 1555	"},
          {label:"	Khoảng sáng gầm xe (mm)		",value:"	279	"},
          {label:"	Góc thoát (Trước / Sau) (độ / degree)		",value:"	29 / 25	"},
          {label:"	Bán kính vòng quay tối thiểu (m)		",value:"	5.8	"},
          {label:"	Trọng lượng không tải (kg)		",value:"	1875	"},
          {label:"	Trọng lượng toàn tải (kg)		",value:"	2500	"},
          {label:"	Dung tích bình nhiên liệu (L)		",value:"	80	"},
          {label:"	Động cơ xăng Loại động cơ		",value:"	2TR-FE (2.7L)	"},
          {label:"	Số xy lanh		",value:"	4	"},
          {label:"	Bố trí xy lanh		",value:"	Thẳng hàng / In line	"},
          {label:"	Dung tích xy lanh (cc)		",value:"	2694	"},
          {label:"	Hệ thống nhiên liệu		",value:"	Phun xăng điện tử / Electronic fuel injection	"},
          {label:"	Loại nhiên liệu		",value:"	Xăng / Petrol	"},
          {label:"	Công suất tối đa ((KW) HP / vòng / phút)		",value:"	122 (164) / 5200	"},
          {label:"	Mô men xoắn tối đa (Nm / vòng / phút)		",value:"	245 / 4000	"},
          {label:"	Tốc độ tối đa		",value:"	175	"},
          {label:"	Chế độ lái (công suất cao / tiết kiệm nhiên liệu)  		",value:"	Có / With	"},
          {label:"	Hệ thống truyền động  		",value:"	Dẫn động cầu sau / RWD	"},
          {label:"	Hộp số  		",value:"	Số tự động 6 cấp / 6AT	"},
          {label:"	Hệ thống treo Trước		",value:"	Độc lập, tay đòn kép với thanh cân bằng / Double wishbone with torsion bar	"},
          {label:"	Sau		",value:"	Phụ thuộc, liên kết 4 điểm / Four links with torsion bar	"},
          {label:"	Hệ thống lái Trợ lực tay lái		",value:"	Thủy lực biến thiên theo tốc độ / Hydraulic (VFC)	"},
          {label:"	Hệ thống tay lái tỉ số truyền biến thiên (VGRS)		",value:"	Không có / Without	"},
          {label:"	Vành & lốp xe Loại vành		",value:"	Mâm đúc / Alloy	"},
          {label:"	Kích thước lốp		",value:"	265 / 65R17	"},
          {label:"	Lốp dự phòng		",value:"	Mâm đúc / Alloy	"},
          {label:"	Phanh Trước		",value:"	Đĩa tản nhiệt / Ventilated disc	"},
          {label:"	Sau		",value:"	Đĩa / Disc	"},
          {label:"	Tiêu chuẩn khí thải  		",value:"	Euro 4	"},
          {label:"	Tiêu thụ nhiên liệu Trong đô thị (L / 100km)		",value:"	14.62	"},
          {label:"	Ngoài đô thị (L / 100km)		",value:"	9.2	"},
          {label:"	Kết hợp (L / 100km)		",value:"	11.2	"},
          {label:"	Cụm đèn trước Đèn chiếu gần		",value:"	LED	"},
          {label:"	Đèn chiếu xa		",value:"	LED	"},
          {label:"	Đèn chiếu sáng ban ngày		",value:"	Có / With	"},
          {label:"	Chế độ điều khiển đèn tự động		",value:"	Có / With	"},
          {label:"	Hệ thống cân bằng góc chiếu		",value:"	Tự động / Auto (ALS)	"},
          {label:"	Chế độ đèn chờ dẫn đường		",value:"	Có / With	"},
          {label:"	Cụm đèn sau  		",value:"	LED	"},
          {label:"	Đèn báo phanh trên cao  		",value:"	LED	"},
          {label:"	Đèn sương mù Trước		",value:"	LED	"},
          {label:"	Sau		",value:"	Không có / Without	"},
          {label:"	Gương chiếu hậu ngoài Chức năng điều chỉnh điện		",value:"	Có / With	"},
          {label:"	Chức năng gập điện		",value:"	Có / With	"},
          {label:"	Tích hợp đèn chào mừng		",value:"	Không có / Without	"},
          {label:"	Tích hợp đèn báo rẽ		",value:"	Có / With	"},
          {label:"	Màu		",value:"	Cùng màu thân xe / Colored	"},
          {label:"	Gạt mưa Trước		",value:"	Gián đoạn, điều chỉnh thời gian / Intermittent & Time adjustment	"},
          {label:"	Sau		",value:"	Có (gián đoạn) / With (intermittent)	"},
          {label:"	Chức năng sấy kính sau  		",value:"	Có / With	"},
          {label:"	Ăng ten  		",value:"	Dạng vây cá / Shark fin	"},
          {label:"	Tay nắm cửa ngoài  		",value:"	Mạ crôm / Chrome plating	"},
          {label:"	Bộ quây xe thể thao  		",value:"	Không có / Without	"},
          {label:"	Thanh cản (giảm va chạm) Trước		",value:"	Có / With	"},
          {label:"	Sau		",value:"	Có / With	"},
          {label:"	Chắn bùn  		",value:"	Trước + Sau / Front + Rear	"},
          {label:"	Ống xả kép  		",value:"	Không có / Without	"},
          {label:"	Tay lái Loại tay lái		",value:"	3 chấu / 3-spoke	"},
          {label:"	Chất liệu		",value:"	Bọc da, ốp gỗ, mạ bạc / Leather, wood, silver ornamentation	"},
          {label:"	Nút bấm điều khiển tích hợp		",value:"	Điều chỉnh âm thanh, màn hình hiển thị đa thông tin, đàm thoại rảnh tay / Audio switch, MID, hands-free phone	"},
          {label:"	Điều chỉnh		",value:"	Chỉnh tay 4 hướng / Manual tilt & telescopic	"},
          {label:"	Lẫy chuyển số		",value:"	Có / With	"},
          {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
          {label:"	Gương chiếu hậu trong  		",value:"	Chống chói tự động / EC	"},
          {label:"	Tay nắm cửa trong  		",value:"	Mạ crôm / Chrome plating	"},
          {label:"	Cụm đồng hồ Loại đồng hồ		",value:"	Optitron	"},
          {label:"	Đèn báo Eco		",value:"	Có / with	"},
          {label:"	Chức năng báo lượng tiêu thụ nhiên liệu		",value:"	Có / with	"},
          {label:"	Chức năng báo vị trí cần số		",value:"	Có / with	"},
          {label:"	Màn hình hiển thị đa thông tin		",value:"	Có (màn hình màu TFT 4.2) / With (color TFT 4.2)	"},
          {label:"	Chất liệu bọc ghế  		",value:"	Da / Leather	"},
          {label:"	Ghế trước Loại ghế		",value:"	Loại thể thao / Sport type	"},
          {label:"	Điều chỉnh ghế lái		",value:"	Chỉnh điện 8 hướng / 8 ways power	"},
          {label:"	Điều chỉnh ghế hành khách		",value:"	Chỉnh điện 8 hướng / 8 ways power	"},
          {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
          {label:"	Chức năng thông gió		",value:"	Không có / Without	"},
          {label:"	Chức năng sưởi		",value:"	Không có / Without	"},
          {label:"	Ghế sau Hàng ghế thứ hai		",value:"	Gập lưng ghế 60:40 một chạm, chỉnh cơ 4 hướng / 60:40 split fold, manual slide & reclining	"},
          {label:"	Hàng ghế thứ ba		",value:"	Ngả lưng ghế, gập 50:50 sang 2 bên / Manual reclining, 50:50 tumble, space up	"},
          {label:"	Tựa tay hàng ghế sau		",value:"	Có / With	"},
          {label:"	Hệ thống điều hòa  		",value:"	Tự động, 2 giàn lạnh / Auto, dual cooler	"},
          {label:"	Cửa gió sau  		",value:"	Có / With	"},
          {label:"	Hộp làm mát  		",value:"	Có / With	"},
          {label:"	Hệ thống âm thanh Đầu đĩa		",value:"	Màn hình cảm ứng 8 navigation / 8 touch screen navigation	"},
          {label:"	Số loa		",value:"	6	"},
          {label:"	Cổng kết nối AUX		",value:"	Không có / Without	"},
          {label:"	Cổng kết nối USB		",value:"	Có / With	"},
          {label:"	Kết nối Bluetooth		",value:"	Có / With	"},
          {label:"	Kết nối điện thoại thông minh / Smartphone connectivity		",value:"	Có / With	"},
          {label:"	Chìa khóa thông minh & Khởi động bằng nút bấm  		",value:"	Có / With	"},
          {label:"	Khóa cửa điện  		",value:"	Có / With	"},
          {label:"	Chức năng khóa cửa từ xa  		",value:"	Có / With	"},
          {label:"	Cửa sổ điều chỉnh điện  		",value:"	Có (1 chạm, chống kẹt tất cả các cửa) / With (Auto, jam protection for all windows)	"},
          {label:"	Cốp điều khiển điện  		",value:"	Có / With	"},
          {label:"	Hệ thống điều khiển hành trình  		",value:"	Có / With	"},
          {label:"	Hệ thống báo động  		",value:"	Có / With	"},
          {label:"	Hệ thống mã hóa khóa động cơ  		",value:"	Có / With	"},
          {label:"	Hệ thống an toàn Toyota (Toyota Safety Sense) Cảnh báo tiền va chạm (PCS)		",value:"	Không có / Without	"},
          {label:"	Cảnh báo chệch làn đường (LDA)		",value:"	Không có / Without	"},
          {label:"	Điều khiển hành trình chủ động (DRCC)		",value:"	Không có / Without	"},
          {label:"	Hệ thống chống bó cứng phanh (ABS)  		",value:"	Có / With	"},
          {label:"	Hệ thống hỗ trợ lực phanh khẩn cấp (BA)  		",value:"	Có / With	"},
          {label:"	Hệ thống phân phối lực phanh điện tử (EBD)  		",value:"	Có / With	"},
          {label:"	Hệ thống cân bằng điện tử (VSC)  		",value:"	Có / With	"},
          {label:"	Hệ thống kiểm soát lực kéo (TRC)  		",value:"	Có / With	"},
          {label:"	Hệ thống hỗ trợ khởi hành ngang dốc (HAC)  		",value:"	Có / With	"},
          {label:"	Hệ thống hỗ trợ đổ đèo (DAC)  		",value:"	Không có / Without	"},
          {label:"	Đèn báo phanh khẩn cấp (EBS)  		",value:"	Có / With	"},
          {label:"	Camera  		",value:"	Camera lùi / Back camera	"},
          {label:"	Cảm biến hỗ trợ đỗ xe Sau		",value:"	Có / With	"},
          {label:"	Góc trước		",value:"	Có / With	"},
          {label:"	Góc sau		",value:"	Có / With	"},
          {label:"	Túi khí Túi khí người lái & hành khách phía trước		",value:"	Có / With	"},
          {label:"	Túi khí bên hông phía trước		",value:"	Có / With	"},
          {label:"	Túi khí rèm		",value:"	Có / With	"},
          {label:"	Túi khí đầu gối người lái		",value:"	Có / With	"},
          {label:"	Khung xe GOA  		",value:"	Có / With	"},
          {label:"	Dây đai an toàn Dây đai an toàn		",value:"	3 điểm ELR, 7 vị trí / 3 points ELRx7	"},
          {label:"	Ghế có cấu trúc giảm chấn thương cổ  		",value:"	Có / With	"},
          {label:"	Cột lái tự đổ  		",value:"	Có / With	"},
          {label:"	Bàn đạp phanh tự đổ  		",value:"	Có / With	"}
        ]
      },
      {
        brand: 'Toyota Fortuner 2.7AT 4x4',
        price: 1230000000,
        fuelType: 'Xăng',
        manufacture: 'Xe nhập khẩu',
        otherInfo: ['Số tự động 6 cấp'],
        thongSo:[
          {label:"	Kích thước Kích thước tổng thể bên ngoài (D x R x C) (mm x mm x mm)		",value:"	4795 x 1855 x 1835	"},
          {label:"	Chiều dài cơ sở (mm)		",value:"	2745	"},
          {label:"	Chiều rộng cơ sở (Trước / sau) (mm)		",value:"	1545 / 1555	"},
          {label:"	Khoảng sáng gầm xe (mm)		",value:"	279	"},
          {label:"	Góc thoát (Trước / Sau) (độ / degree)		",value:"	29 / 25	"},
          {label:"	Bán kính vòng quay tối thiểu (m)		",value:"	5.8	"},
          {label:"	Trọng lượng không tải (kg)		",value:"	2035	"},
          {label:"	Trọng lượng toàn tải (kg)		",value:"	2500	"},
          {label:"	Dung tích bình nhiên liệu (L)		",value:"	80	"},
          {label:"	Động cơ xăng Loại động cơ		",value:"	2TR-FE (2.7L)	"},
          {label:"	Số xy lanh		",value:"	4	"},
          {label:"	Bố trí xy lanh		",value:"	Thẳng hàng / In line	"},
          {label:"	Dung tích xy lanh (cc)		",value:"	2694	"},
          {label:"	Hệ thống nhiên liệu		",value:"	Phun xăng điện tử / Electronic fuel injection	"},
          {label:"	Loại nhiên liệu		",value:"	Xăng / Petrol	"},
          {label:"	Công suất tối đa ((KW) HP / vòng / phút)		",value:"	122 (164) / 5200	"},
          {label:"	Mô men xoắn tối đa (Nm / vòng / phút)		",value:"	245 / 4000	"},
          {label:"	Tốc độ tối đa		",value:"	160	"},
          {label:"	Chế độ lái (công suất cao / tiết kiệm nhiên liệu)  		",value:"	Có / With	"},
          {label:"	Hệ thống truyền động  		",value:"	Dẫn động 2 cầu bán thời gian, gài cầu điện tử / Part-time 4WD, electronic transfer switch	"},
          {label:"	Hộp số  		",value:"	Số tự động 6 cấp / 6AT	"},
          {label:"	Hệ thống treo Trước		",value:"	Độc lập, tay đòn kép với thanh cân bằng / Double wishbone with torsion bar	"},
          {label:"	Sau		",value:"	Phụ thuộc, liên kết 4 điểm / Four links with torsion bar	"},
          {label:"	Hệ thống lái Trợ lực tay lái		",value:"	Thủy lực biến thiên theo tốc độ / Hydraulic (VFC)	"},
          {label:"	Hệ thống tay lái tỉ số truyền biến thiên (VGRS)		",value:"	Không có / Without	"},
          {label:"	Vành & lốp xe Loại vành		",value:"	Mâm đúc / Alloy	"},
          {label:"	Kích thước lốp		",value:"	265 / 60R18	"},
          {label:"	Lốp dự phòng		",value:"	Mâm đúc / Alloy	"},
          {label:"	Phanh Trước		",value:"	Đĩa tản nhiệt / Ventilated disc	"},
          {label:"	Sau		",value:"	Đĩa / Disc	"},
          {label:"	Tiêu chuẩn khí thải  		",value:"	Euro 4	"},
          {label:"	Tiêu thụ nhiên liệu Trong đô thị (L / 100km)		",value:"	14	"},
          {label:"	Ngoài đô thị (L / 100km)		",value:"	9.4	"},
          {label:"	Kết hợp (L / 100km)		",value:"	11.1	"},
          {label:"	Cụm đèn trước Đèn chiếu gần		",value:"	LED	"},
          {label:"	Đèn chiếu xa		",value:"	LED	"},
          {label:"	Đèn chiếu sáng ban ngày		",value:"	Có / With	"},
          {label:"	Chế độ điều khiển đèn tự động		",value:"	Có / With	"},
          {label:"	Hệ thống cân bằng góc chiếu		",value:"	Tự động / Auto (ALS)	"},
          {label:"	Chế độ đèn chờ dẫn đường		",value:"	Có / With	"},
          {label:"	Cụm đèn sau  		",value:"	LED	"},
          {label:"	Đèn báo phanh trên cao  		",value:"	LED	"},
          {label:"	Đèn sương mù Trước		",value:"	LED	"},
          {label:"	Sau		",value:"	Không có / Without	"},
          {label:"	Gương chiếu hậu ngoài Chức năng điều chỉnh điện		",value:"	Có / With	"},
          {label:"	Chức năng gập điện		",value:"	Có / With	"},
          {label:"	Tích hợp đèn chào mừng		",value:"	Có / With	"},
          {label:"	Tích hợp đèn báo rẽ		",value:"	Có / With	"},
          {label:"	Màu		",value:"	Cùng màu thân xe / Colored	"},
          {label:"	Gạt mưa Trước		",value:"	Gián đoạn, điều chỉnh thời gian / Intermittent & Time adjustment	"},
          {label:"	Sau		",value:"	Có (gián đoạn) / With (intermittent)	"},
          {label:"	Chức năng sấy kính sau  		",value:"	Có / With	"},
          {label:"	Ăng ten  		",value:"	Dạng vây cá / Shark fin	"},
          {label:"	Tay nắm cửa ngoài  		",value:"	Mạ crôm / Chrome plating	"},
          {label:"	Bộ quây xe thể thao  		",value:"	Không có / Without	"},
          {label:"	Thanh cản (giảm va chạm) Trước		",value:"	Có / With	"},
          {label:"	Sau		",value:"	Có / With	"},
          {label:"	Chắn bùn  		",value:"	Trước + Sau / Front + Rear	"},
          {label:"	Ống xả kép  		",value:"	Không có / Without	"},
          {label:"	Tay lái Loại tay lái		",value:"	3 chấu / 3-spoke	"},
          {label:"	Chất liệu		",value:"	Bọc da, ốp gỗ, mạ bạc / Leather, wood, silver ornamentation	"},
          {label:"	Nút bấm điều khiển tích hợp		",value:"	Điều chỉnh âm thanh, màn hình hiển thị đa thông tin, đàm thoại rảnh tay / Audio switch, MID, hands-free phone	"},
          {label:"	Điều chỉnh		",value:"	Chỉnh tay 4 hướng / Manual tilt & telescopic	"},
          {label:"	Lẫy chuyển số		",value:"	Có / With	"},
          {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
          {label:"	Gương chiếu hậu trong  		",value:"	Chống chói tự động / EC	"},
          {label:"	Tay nắm cửa trong  		",value:"	Mạ crôm / Chrome plating	"},
          {label:"	Cụm đồng hồ Loại đồng hồ		",value:"	Optitron	"},
          {label:"	Đèn báo Eco		",value:"	Có / With	"},
          {label:"	Chức năng báo lượng tiêu thụ nhiên liệu		",value:"	Có / With	"},
          {label:"	Chức năng báo vị trí cần số		",value:"	Có / With	"},
          {label:"	Màn hình hiển thị đa thông tin		",value:"	Có (màn hình màu TFT 4.2) / With (color TFT 4.2)	"},
          {label:"	Chất liệu bọc ghế  		",value:"	Da / Leather	"},
          {label:"	Ghế trước Loại ghế		",value:"	Loại thể thao / Sport type	"},
          {label:"	Điều chỉnh ghế lái		",value:"	Chỉnh điện 8 hướng / 8 ways power	"},
          {label:"	Điều chỉnh ghế hành khách		",value:"	Chỉnh điện 8 hướng / 8 ways power	"},
          {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
          {label:"	Chức năng thông gió		",value:"	Không có / Without	"},
          {label:"	Chức năng sưởi		",value:"	Không có / Without	"},
          {label:"	Ghế sau Hàng ghế thứ hai		",value:"	Gập lưng ghế 60:40 một chạm, chỉnh cơ 4 hướng / 60:40 split fold, manual slide & reclining	"},
          {label:"	Hàng ghế thứ ba		",value:"	Ngả lưng ghế, gập 50:50 sang 2 bên / Manual reclining, 50:50 tumble, space up	"},
          {label:"	Tựa tay hàng ghế sau		",value:"	Có / With	"},
          {label:"	Hệ thống điều hòa  		",value:"	Tự động, 2 giàn lạnh / Auto, dual cooler	"},
          {label:"	Cửa gió sau  		",value:"	Có / With	"},
          {label:"	Hộp làm mát  		",value:"	Có / With	"},
          {label:"	Hệ thống âm thanh Đầu đĩa		",value:"	Màn hình cảm ứng 8 navigation / 8 touch screen navigation	"},
          {label:"	Số loa		",value:"	11 loa JBL	"},
          {label:"	Cổng kết nối AUX		",value:"	Không có / Without	"},
          {label:"	Cổng kết nối USB		",value:"	Có / With	"},
          {label:"	Kết nối Bluetooth		",value:"	Có / With	"},
          {label:"	Kết nối điện thoại thông minh / Smartphone connectivity		",value:"	Có / With	"},
          {label:"	Chìa khóa thông minh & Khởi động bằng nút bấm  		",value:"	Có / With	"},
          {label:"	Khóa cửa điện  		",value:"	Có / With	"},
          {label:"	Chức năng khóa cửa từ xa  		",value:"	Có / With	"},
          {label:"	Cửa sổ điều chỉnh điện  		",value:"	Có (1 chạm, chống kẹt tất cả các cửa) / With (Auto, jam protection for all windows)	"},
          {label:"	Cốp điều khiển điện  		",value:"	Có / With	"},
          {label:"	Hệ thống điều khiển hành trình  		",value:"	Có / With	"},
          {label:"	Hệ thống báo động  		",value:"	Có / With	"},
          {label:"	Hệ thống mã hóa khóa động cơ  		",value:"	Có / With	"},
          {label:"	Hệ thống an toàn Toyota (Toyota Safety Sense) Cảnh báo tiền va chạm (PCS)		",value:"	Không có / Without	"},
          {label:"	Cảnh báo chệch làn đường (LDA)		",value:"	Không có / Without	"},
          {label:"	Điều khiển hành trình chủ động (DRCC)		",value:"	Không có / Without	"},
          {label:"	Hệ thống chống bó cứng phanh (ABS)  		",value:"	Có / With	"},
          {label:"	Hệ thống hỗ trợ lực phanh khẩn cấp (BA)  		",value:"	Có / With	"},
          {label:"	Hệ thống phân phối lực phanh điện tử (EBD)  		",value:"	Có / With	"},
          {label:"	Hệ thống cân bằng điện tử (VSC)  		",value:"	Có / With	"},
          {label:"	Hệ thống kiểm soát lực kéo (TRC)  		",value:"	Có (A-TRC) / With (A-TRC)	"},
          {label:"	Hệ thống hỗ trợ khởi hành ngang dốc (HAC)  		",value:"	Có / With	"},
          {label:"	Hệ thống hỗ trợ đổ đèo (DAC)  		",value:"	Có / With	"},
          {label:"	Đèn báo phanh khẩn cấp (EBS)  		",value:"	Có / With	"},
          {label:"	Camera  		",value:"	Camera lùi / Back camera	"},
          {label:"	Cảm biến hỗ trợ đỗ xe Sau		",value:"	Có / With	"},
          {label:"	Góc trước		",value:"	Có / With	"},
          {label:"	Góc sau		",value:"	Có / With	"},
          {label:"	Túi khí Túi khí người lái & hành khách phía trước		",value:"	Có / With	"},
          {label:"	Túi khí bên hông phía trước		",value:"	Có / With	"},
          {label:"	Túi khí rèm		",value:"	Có / With	"},
          {label:"	Túi khí đầu gối người lái		",value:"	Có / With	"},
          {label:"	Khung xe GOA  		",value:"	Có / With	"},
          {label:"	Dây đai an toàn Dây đai an toàn		",value:"	3 điểm ELR, 7 vị trí / 3 points ELRx7	"},
          {label:"	Ghế có cấu trúc giảm chấn thương cổ  		",value:"	Có / With	"},
          {label:"	Cột lái tự đổ  		",value:"	Có / With	"},
          {label:"	Bàn đạp phanh tự đổ  		",value:"	Có / With	"}
        ]
      },
      {
        brand: 'Toyota Fortuner 2.8AT 4x4',
        price: 1388000000,
        thongSo:[
          {label:"	Kích thước Kích thước tổng thể bên ngoài (D x R x C) (mm x mm x mm)		",value:"	4795 x 1855 x 1835	"},
          {label:"	Chiều dài cơ sở (mm)		",value:"	2745	"},
          {label:"	Chiều rộng cơ sở (Trước / sau) (mm)		",value:"	1545 / 1555	"},
          {label:"	Khoảng sáng gầm xe (mm)		",value:"	279	"},
          {label:"	Bán kính vòng quay tối thiểu (m)		",value:"	5.8	"},
          {label:"	Trọng lượng không tải (kg)		",value:"	2140	"},
          {label:"	Trọng lượng toàn tải (kg)		",value:"	2735	"},
          {label:"	Dung tích bình nhiên liệu (L)		",value:"	80	"},
          {label:"	Động cơ xăng Loại động cơ		",value:"	1GD-FTV (2.8L)	"},
          {label:"	Số xy lanh		",value:"	4	"},
          {label:"	Bố trí xy lanh		",value:"	Thẳng hàng / In line	"},
          {label:"	Dung tích xy lanh (cc)		",value:"	2755	"},
          {label:"	Hệ thống nhiên liệu		",value:"	Phun nhiên liệu trực tiếp sử dụng đường ống dẫn chung, tăng áp biến thiên / Common rail direct injection & Variable nozzle turborcharger (VNT)	"},
          {label:"	Loại nhiên liệu		",value:"	Dầu / Diesel	"},
          {label:"	Công suất tối đa ((KW) HP / vòng / phút)		",value:"	150 (201) / 3400	"},
          {label:"	Mô men xoắn tối đa (Nm / vòng / phút)		",value:"	500 / 1600	"},
          {label:"	Tốc độ tối đa		",value:"	180	"},
          {label:"	Chế độ lái (công suất cao / tiết kiệm nhiên liệu)  		",value:"	Có / With	"},
          {label:"	Hệ thống truyền động  		",value:"	Dẫn động 2 cầu bán thời gian, gài cầu điện tử / Part-time 4WD, electronic transfer switch	"},
          {label:"	Hộp số  		",value:"	Số tự động 6 cấp / 6AT	"},
          {label:"	Hệ thống treo Trước		",value:"	Độc lập, tay đòn kép với thanh cân bằng / Double wishbone with torsion bar	"},
          {label:"	Sau		",value:"	Phụ thuộc, liên kết 4 điểm / Four links with torsion bar	"},
          {label:"	Hệ thống lái Trợ lực tay lái		",value:"	Thủy lực biến thiên theo tốc độ / Hydraulic (VFC)	"},
          {label:"	Hệ thống tay lái tỉ số truyền biến thiên (VGRS)		",value:"	Không có / Without	"},
          {label:"	Vành & lốp xe Loại vành		",value:"	Mâm đúc / Alloy	"},
          {label:"	Kích thước lốp		",value:"	265 / 60R18	"},
          {label:"	Lốp dự phòng		",value:"	Mâm đúc / Alloy	"},
          {label:"	Phanh Trước		",value:"	Đĩa tản nhiệt / Ventilated disc	"},
          {label:"	Sau		",value:"	Đĩa / Disc	"},
          {label:"	Tiêu chuẩn khí thải  		",value:"	Euro 4	"},
          {label:"	Tiêu thụ nhiên liệu Trong đô thị (L / 100km)		",value:"	9.86	"},
          {label:"	Ngoài đô thị (L / 100km)		",value:"	7.07	"},
          {label:"	Kết hợp (L / 100km)		",value:"	8.11	"},
          {label:"	Cụm đèn trước Đèn chiếu gần		",value:"	LED	"},
          {label:"	Đèn chiếu xa		",value:"	LED	"},
          {label:"	Đèn chiếu sáng ban ngày		",value:"	Có / With	"},
          {label:"	Chế độ điều khiển đèn tự động		",value:"	Có / With	"},
          {label:"	Hệ thống cân bằng góc chiếu		",value:"	Tự động / Auto (ALS)	"},
          {label:"	Chế độ đèn chờ dẫn đường		",value:"	Có / With	"},
          {label:"	Cụm đèn sau  		",value:"	LED	"},
          {label:"	Đèn báo phanh trên cao  		",value:"	LED	"},
          {label:"	Đèn sương mù Trước		",value:"	LED	"},
          {label:"	Sau		",value:"	Không có / Without	"},
          {label:"	Gương chiếu hậu ngoài Chức năng điều chỉnh điện		",value:"	Có / With	"},
          {label:"	Chức năng gập điện		",value:"	Có / With	"},
          {label:"	Tích hợp đèn chào mừng		",value:"	Có / With	"},
          {label:"	Tích hợp đèn báo rẽ		",value:"	Có / With	"},
          {label:"	Màu		",value:"	Cùng màu thân xe / Colored	"},
          {label:"	Gạt mưa Trước		",value:"	Gián đoạn, điều chỉnh thời gian / Intermittent & Time adjustment	"},
          {label:"	Sau		",value:"	Có (gián đoạn) / With (intermittent)	"},
          {label:"	Chức năng sấy kính sau  		",value:"	Có / With	"},
          {label:"	Ăng ten  		",value:"	Dạng vây cá / Shark fin	"},
          {label:"	Tay nắm cửa ngoài  		",value:"	Mạ crôm / Chrome plating	"},
          {label:"	Bộ quây xe thể thao  		",value:"	Không có / Without	"},
          {label:"	Thanh cản (giảm va chạm) Trước		",value:"	Có / With	"},
          {label:"	Sau		",value:"	Có / With	"},
          {label:"	Chắn bùn  		",value:"	Trước + Sau / Front + Rear	"},
          {label:"	Ống xả kép  		",value:"	Không có / Without	"},
          {label:"	Tay lái Loại tay lái		",value:"	3 chấu / 3-spoke	"},
          {label:"	Chất liệu		",value:"	Bọc da, ốp gỗ, mạ bạc / Leather, wood, silver ornamentation	"},
          {label:"	Nút bấm điều khiển tích hợp		",value:"	Điều chỉnh âm thanh, màn hình hiển thị đa thông tin, đàm thoại rảnh tay, cảnh báo chệch làn đường / Audio switch, MID, hands-free phone, LDA	"},
          {label:"	Điều chỉnh		",value:"	Chỉnh tay 4 hướng / Manual tilt & telescopic	"},
          {label:"	Lẫy chuyển số		",value:"	Có / With	"},
          {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
          {label:"	Gương chiếu hậu trong  		",value:"	Chống chói tự động / EC	"},
          {label:"	Tay nắm cửa trong  		",value:"	Mạ crôm / Chrome plating	"},
          {label:"	Cụm đồng hồ Loại đồng hồ		",value:"	Optitron	"},
          {label:"	Đèn báo Eco		",value:"	Có / With	"},
          {label:"	Chức năng báo lượng tiêu thụ nhiên liệu		",value:"	Có / With	"},
          {label:"	Chức năng báo vị trí cần số		",value:"	Có / With	"},
          {label:"	Màn hình hiển thị đa thông tin		",value:"	Có (màn hình màu TFT 4.2) / With (color TFT 4.2)	"},
          {label:"	Chất liệu bọc ghế  		",value:"	Da / Leather	"},
          {label:"	Ghế trước Loại ghế		",value:"	Loại thể thao / Sport type	"},
          {label:"	Điều chỉnh ghế lái		",value:"	Chỉnh điện 8 hướng / 8 way power	"},
          {label:"	Điều chỉnh ghế hành khách		",value:"	Chỉnh điện 8 hướng / 8 way power	"},
          {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
          {label:"	Chức năng thông gió		",value:"	Không có / Without	"},
          {label:"	Chức năng sưởi		",value:"	Không có / Without	"},
          {label:"	Ghế sau Hàng ghế thứ hai		",value:"	Gập lưng ghế 60:40 một chạm, chỉnh cơ 4 hướng / 60:40 split fold, manual slide & reclining	"},
          {label:"	Tựa tay hàng ghế thứ ba		",value:"	Ngả lưng ghế, gập 50:50 sang 2 bên / Manual reclining, 50:50 tumble, space up	"},
          {label:"	Tựa tay hàng ghế sau		",value:"	Có / With	"},
          {label:"	Hệ thống điều hòa  		",value:"	Tự động, 2 giàn lạnh / Auto, dual cooler	"},
          {label:"	Cửa gió sau  		",value:"	Có / With	"},
          {label:"	Hộp làm mát  		",value:"	Có / With	"},
          {label:"	Hệ thống âm thanh Đầu đĩa		",value:"	Màn hình cảm ứng 8 navigation / 8 touch screen navigation	"},
          {label:"	Số loa		",value:"	11 loa JBL	"},
          {label:"	Cổng kết nối AUX		",value:"	Không có / Without	"},
          {label:"	Cổng kết nối USB		",value:"	Có / With	"},
          {label:"	Kết nối Bluetooth		",value:"	Có / With	"},
          {label:"	Kết nối điện thoại thông minh / Smartphone connectivity		",value:"	Có / With	"},
          {label:"	Chìa khóa thông minh & Khởi động bằng nút bấm  		",value:"	Có / With	"},
          {label:"	Khóa cửa điện  		",value:"	Có / With	"},
          {label:"	Chức năng khóa cửa từ xa  		",value:"	Có / With	"},
          {label:"	Cửa sổ điều chỉnh điện  		",value:"	Có (1 chạm, chống kẹt tất cả các cửa) / With (Auto, jam protection for all windows)	"},
          {label:"	Cốp điều khiển điện  		",value:"	Mở cốp rảnh tay / Kick active	"},
          {label:"	Hệ thống điều khiển hành trình  		",value:"	Có / With	"},
          {label:"	Hệ thống báo động  		",value:"	Có / With	"},
          {label:"	Hệ thống mã hóa khóa động cơ  		",value:"	Có / With	"},
          {label:"	Hệ thống an toàn Toyota (Toyota Safety Sense) Cảnh báo tiền va chạm (PCS)		",value:"	Có / With	"},
          {label:"	Cảnh báo chệch làn đường (LDA)		",value:"	Có / With	"},
          {label:"	Điều khiển hành trình chủ động (DRCC)		",value:"	Có / With	"},
          {label:"	Hệ thống chống bó cứng phanh (ABS)  		",value:"	Có / With	"},
          {label:"	Hệ thống hỗ trợ lực phanh khẩn cấp (BA)  		",value:"	Có / With	"},
          {label:"	Hệ thống phân phối lực phanh điện tử (EBD)  		",value:"	Có / With	"},
          {label:"	Hệ thống cân bằng điện tử (VSC)  		",value:"	Có / With	"},
          {label:"	Hệ thống kiểm soát lực kéo (TRC)  		",value:"	Có (A-TRC) / With (A-TRC)	"},
          {label:"	Hệ thống hỗ trợ khởi hành ngang dốc (HAC)  		",value:"	Có / With	"},
          {label:"	Hệ thống hỗ trợ đổ đèo (DAC)  		",value:"	Có / With	"},
          {label:"	Đèn báo phanh khẩn cấp (EBS)  		",value:"	Có / With	"},
          {label:"	Camera  		",value:"	Camera 360	"},
          {label:"	Cảm biến hỗ trợ đỗ xe Sau		",value:"	Có / With	"},
          {label:"	Góc trước		",value:"	Có / With	"},
          {label:"	Góc sau		",value:"	Có / With	"},
          {label:"	Túi khí Túi khí người lái & hành khách phía trước		",value:"	Có / With	"},
          {label:"	Túi khí bên hông phía trước		",value:"	Có / With	"},
          {label:"	Túi khí rèm		",value:"	Có / With	"},
          {label:"	Túi khí đầu gối người lái		",value:"	Có / With	"},
          {label:"	Khung xe GOA  		",value:"	Có / With	"},
          {label:"	Dây đai an toàn  		",value:"	3 điểm ELR, 7 vị trí / 3 points ELRx7	"},
          {label:"	Ghế có cấu trúc giảm chấn thương cổ  		",value:"	Có / With	"},
          {label:"	Cột lái tự đổ  		",value:"	Có / With	"},
          {label:"	Bàn đạp phanh tự đổ  		",value:"	Có / With	"}
        ]
      },
      {
        brand: 'Toyota Fortuner Legender 2.4AT 4X2',
        price: 1195000000,
        thongSo:[
          {label:"	Kích thước Kích thước tổng thể bên ngoài (D x R x C) (mm x mm x mm)		",value:"	4795 x 1855 x 1835	"},
          {label:"	Chiều dài cơ sở (mm)		",value:"	2745	"},
          {label:"	Chiều rộng cơ sở (Trước / sau) (mm)		",value:"	1545 / 1555	"},
          {label:"	Khoảng sáng gầm xe (mm)		",value:"	279	"},
          {label:"	Bán kính vòng quay tối thiểu (m)		",value:"	5.8	"},
          {label:"	Trọng lượng không tải (kg)		",value:"	2005	"},
          {label:"	Trọng lượng toàn tải (kg)		",value:"	2605	"},
          {label:"	Dung tích bình nhiên liệu (L)		",value:"	80	"},
          {label:"	Động cơ xăng Loại động cơ		",value:"	2GD-FTV (2.4L)	"},
          {label:"	Số xy lanh		",value:"	4	"},
          {label:"	Bố trí xy lanh		",value:"	Thẳng hàng / In line	"},
          {label:"	Dung tích xy lanh (cc)		",value:"	2393	"},
          {label:"	Hệ thống nhiên liệu		",value:"	Phun nhiên liệu trực tiếp sử dụng đường ống dẫn chung, tăng áp biến thiên / Common rail direct injection & Variable nozzle turborcharger (VNT)	"},
          {label:"	Loại nhiên liệu		",value:"	Dầu / Diesel	"},
          {label:"	Công suất tối đa ((KW) HP / vòng / phút)		",value:"	110 (147) / 3400	"},
          {label:"	Mô men xoắn tối đa (Nm / vòng / phút)		",value:"	400 / 1600	"},
          {label:"	Tốc độ tối đa		",value:"	170	"},
          {label:"	Chế độ lái (công suất cao / tiết kiệm nhiên liệu)  		",value:"	Có / With	"},
          {label:"	Hệ thống truyền động  		",value:"	Dẫn động cầu sau / RWD	"},
          {label:"	Hộp số  		",value:"	Số tự động 6 cấp / 6AT	"},
          {label:"	Hệ thống treo Trước		",value:"	Độc lập, tay đòn kép với thanh cân bằng / Double wishbone with torsion bar	"},
          {label:"	Sau		",value:"	Phụ thuộc, liên kết 4 điểm / Four links with torsion bar	"},
          {label:"	Hệ thống lái Trợ lực tay lái		",value:"	Thủy lực biến thiên theo tốc độ / Hydraulic (VFC)	"},
          {label:"	Hệ thống tay lái tỉ số truyền biến thiên (VGRS)		",value:"	Không có / Without	"},
          {label:"	Vành & lốp xe Loại vành		",value:"	Mâm đúc / Alloy	"},
          {label:"	Kích thước lốp		",value:"	265 / 60R18	"},
          {label:"	Lốp dự phòng		",value:"	Mâm đúc / Alloy	"},
          {label:"	Phanh Trước		",value:"	Đĩa tản nhiệt / Ventilated disc	"},
          {label:"	Sau		",value:"	Đĩa / Disc	"},
          {label:"	Tiêu chuẩn khí thải  		",value:"	Euro 4	"},
          {label:"	Tiêu thụ nhiên liệu Trong đô thị (L / 100km)		",value:"	10.21	"},
          {label:"	Ngoài đô thị (L / 100km)		",value:"	7.14	"},
          {label:"	Kết hợp (L / 100km)		",value:"	8.28	"},
          {label:"	Cụm đèn trước Đèn chiếu gần		",value:"	LED	"},
          {label:"	Đèn chiếu xa		",value:"	LED	"},
          {label:"	Đèn chiếu sáng ban ngày		",value:"	Có / With	"},
          {label:"	Chế độ điều khiển đèn tự động		",value:"	Có / With	"},
          {label:"	Hệ thống cân bằng góc chiếu		",value:"	Tự động / Auto (ALS)	"},
          {label:"	Chế độ đèn chờ dẫn đường		",value:"	Có / With	"},
          {label:"	Cụm đèn sau  		",value:"	LED	"},
          {label:"	Đèn báo phanh trên cao  		",value:"	LED	"},
          {label:"	Đèn sương mù Trước		",value:"	LED	"},
          {label:"	Sau		",value:"	LED	"},
          {label:"	Gương chiếu hậu ngoài Chức năng điều chỉnh điện		",value:"	Có / With	"},
          {label:"	Chức năng gập điện		",value:"	Có / With	"},
          {label:"	Tích hợp đèn chào mừng		",value:"	Có / With	"},
          {label:"	Tích hợp đèn báo rẽ		",value:"	Có / With	"},
          {label:"	Gạt mưa Trước		",value:"	Gián đoạn, điều chỉnh thời gian / Intermittent & Time adjustment	"},
          {label:"	Sau		",value:"	Có (gián đoạn) / With (intermittent)	"},
          {label:"	Chức năng sấy kính sau  		",value:"	Có / With	"},
          {label:"	Ăng ten  		",value:"	Dạng vây cá / Shark fin	"},
          {label:"	Tay nắm cửa ngoài  		",value:"	Mạ crôm / Chrome plating	"},
          {label:"	Bộ quây xe thể thao  		",value:"	Không có / Without	"},
          {label:"	Thanh cản (giảm va chạm) Trước		",value:"	Có / With	"},
          {label:"	Sau		",value:"	Có / With	"},
          {label:"	Chắn bùn  		",value:"	Trước + Sau / Front + Rear	"},
          {label:"	Ống xả kép  		",value:"	Không có / Without	"},
          {label:"	Tay lái Loại tay lái		",value:"	3 chấu / 3-spoke	"},
          {label:"	Chất liệu		",value:"	Bọc da, ốp gỗ, mạ bạc / Leather, wood, silver ornamentation	"},
          {label:"	Nút bấm điều khiển tích hợp		",value:"	Điều chỉnh âm thanh, màn hình hiển thị đa thông tin, đàm thoại rảnh tay / Audio switch, MID, hands-free phone	"},
          {label:"	Điều chỉnh		",value:"	Chỉnh tay 4 hướng / Manual tilt & telescopic	"},
          {label:"	Lẫy chuyển số		",value:"	Có / With	"},
          {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
          {label:"	Gương chiếu hậu trong  		",value:"	Chống chói tự động / EC	"},
          {label:"	Tay nắm cửa trong  		",value:"	Mạ crôm / Chrome plating	"},
          {label:"	Cụm đồng hồ Loại đồng hồ		",value:"	Optitron	"},
          {label:"	Đèn báo Eco		",value:"	Có / With	"},
          {label:"	Chức năng báo lượng tiêu thụ nhiên liệu		",value:"	Có / With	"},
          {label:"	Chức năng báo vị trí cần số		",value:"	Có / With	"},
          {label:"	Màn hình hiển thị đa thông tin		",value:"	Có (màn hình màu TFT 4.2) / With (color TFT 4.2)	"},
          {label:"	Chất liệu bọc ghế  		",value:"	Da / Leather	"},
          {label:"	Ghế trước Loại ghế		",value:"	Loại thể thao / Sport type	"},
          {label:"	Điều chỉnh ghế lái		",value:"	Chỉnh điện 8 hướng / 8 way power	"},
          {label:"	Điều chỉnh ghế hành khách		",value:"	Chỉnh điện 8 hướng / 8 way power	"},
          {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
          {label:"	Chức năng thông gió		",value:"	Không có / Without	"},
          {label:"	Chức năng sưởi		",value:"	Không có / Without	"},
          {label:"	Ghế sau Hàng ghế thứ hai		",value:"	Gập lưng ghế 60:40 một chạm, chỉnh cơ 4 hướng / 60:40 split fold, manual slide & reclining	"},
          {label:"	Hàng ghế thứ ba		",value:"	Ngả lưng ghế, gập 50:50 sang 2 bên / Manual reclining, 50:50 tumble, space up	"},
          {label:"	Tựa tay hàng ghế sau		",value:"	Có / With	"},
          {label:"	Hệ thống điều hòa  		",value:"	Tự động, 2 giàn lạnh / Auto, dual cooler	"},
          {label:"	Cửa gió sau  		",value:"	Có / With	"},
          {label:"	Hộp làm mát  		",value:"	Có / With	"},
          {label:"	Hệ thống âm thanh Đầu đĩa		",value:"	Màn hình cảm ứng 8 navigation / 8 touch screen navigation	"},
          {label:"	Số loa		",value:"	6	"},
          {label:"	Cổng kết nối AUX		",value:"	Không có / Without	"},
          {label:"	Cổng kết nối USB		",value:"	Có / With	"},
          {label:"	Kết nối Bluetooth		",value:"	Có / With	"},
          {label:"	Kết nối điện thoại thông minh / Smartphone connectivity		",value:"	Có / With	"},
          {label:"	Chìa khóa thông minh & Khởi động bằng nút bấm  		",value:"	Có / With	"},
          {label:"	Khóa cửa điện  		",value:"	Có / With	"},
          {label:"	Chức năng khóa cửa từ xa  		",value:"	Có / With	"},
          {label:"	Cửa sổ điều chỉnh điện  		",value:"	Có (1 chạm, chống kẹt tất cả các cửa) / With (Auto, jam protection for all windows)	"},
          {label:"	Cốp điều khiển điện  		",value:"	Mở cốp rảnh tay / Kick active	"},
          {label:"	Hệ thống điều khiển hành trình  		",value:"	Có / With	"},
          {label:"	Hệ thống báo động  		",value:"	Có / With	"},
          {label:"	Hệ thống mã hóa khóa động cơ  		",value:"	Có / With	"},
          {label:"	Hệ thống an toàn Toyota (Toyota Safety Sense) Cảnh báo tiền va chạm (PCS)		",value:"	Không có / Without	"},
          {label:"	Cảnh báo chệch làn đường (LDA)		",value:"	Không có / Without	"},
          {label:"	Điều khiển hành trình chủ động (DRCC)		",value:"	Không có / Without	"},
          {label:"	Hệ thống chống bó cứng phanh (ABS)  		",value:"	Có / With	"},
          {label:"	Hệ thống hỗ trợ lực phanh khẩn cấp (BA)  		",value:"	Có / With	"},
          {label:"	Hệ thống phân phối lực phanh điện tử (EBD)  		",value:"	Có / With	"},
          {label:"	Hệ thống cân bằng điện tử (VSC)  		",value:"	Có / With	"},
          {label:"	Hệ thống kiểm soát lực kéo (TRC)  		",value:"	Có / With	"},
          {label:"	Hệ thống hỗ trợ khởi hành ngang dốc (HAC)  		",value:"	Có / With	"},
          {label:"	Hệ thống hỗ trợ đổ đèo (DAC)  		",value:"	Không có / Without	"},
          {label:"	Đèn báo phanh khẩn cấp (EBS)  		",value:"	Có / With	"},
          {label:"	Camera  		",value:"	Camera 360	"},
          {label:"	Cảm biến hỗ trợ đỗ xe Sau		",value:"	Có / With	"},
          {label:"	Góc trước		",value:"	Có / With	"},
          {label:"	Góc sau		",value:"	Có / With	"},
          {label:"	Túi khí Túi khí người lái & hành khách phía trước		",value:"	Có / With	"},
          {label:"	Túi khí bên hông phía trước		",value:"	Có / With	"},
          {label:"	Túi khí rèm		",value:"	Có / With	"},
          {label:"	Túi khí đầu gối người lái		",value:"	Có / With	"},
          {label:"	Khung xe GOA  		",value:"	Có / With	"},
          {label:"	Dây đai an toàn  		",value:"	3 điểm ELR, 7 vị trí / 3 points ELRx7	"},
          {label:"	Ghế có cấu trúc giảm chấn thương cổ  		",value:"	Có / With	"},
          {label:"	Cột lái tự đổ  		",value:"	Có / With	"},
          {label:"	Bàn đạp phanh tự đổ  		",value:"	Có / With	"}
        ]
        
      },
      {
        brand: 'Toyota Fortuner Legender 2.8AT 4X4',
        price: 1426000000,
        thongSo:[
          {label:"	Kích thước Kích thước tổng thể bên ngoài (D x R x C) (mm x mm x mm)		",value:"	4795 x 1855 x 1835	"},
          {label:"	Chiều dài cơ sở (mm)		",value:"	2745	"},
          {label:"	Chiều rộng cơ sở (Trước / sau) (mm)		",value:"	1545 / 1555	"},
          {label:"	Khoảng sáng gầm xe (mm)		",value:"	279	"},
          {label:"	Bán kính vòng quay tối thiểu (m)		",value:"	5.8	"},
          {label:"	Trọng lượng không tải (kg)		",value:"	2140	"},
          {label:"	Trọng lượng toàn tải (kg)		",value:"	2735	"},
          {label:"	Dung tích bình nhiên liệu (L)		",value:"	80	"},
          {label:"	Động cơ xăng Loại động cơ		",value:"	1GD-FTV (2.8L)	"},
          {label:"	Số xy lanh		",value:"	4	"},
          {label:"	Bố trí xy lanh		",value:"	Thẳng hàng / In line	"},
          {label:"	Dung tích xy lanh (cc)		",value:"	2755	"},
          {label:"	Hệ thống nhiên liệu		",value:"	Phun nhiên liệu trực tiếp sử dụng đường ống dẫn chung, tăng áp biến thiên / Common rail direct injection & Variable nozzle turborcharger (VNT)	"},
          {label:"	Loại nhiên liệu		",value:"	Dầu / Diesel	"},
          {label:"	Công suất tối đa ((KW) HP / vòng / phút)		",value:"	150 (201) / 3400	"},
          {label:"	Mô men xoắn tối đa (Nm / vòng / phút)		",value:"	500 / 1600	"},
          {label:"	Tốc độ tối đa		",value:"	180	"},
          {label:"	Chế độ lái (công suất cao / tiết kiệm nhiên liệu)  		",value:"	Có / With	"},
          {label:"	Hệ thống truyền động  		",value:"	Dẫn động 2 cầu bán thời gian, gài cầu điện tử / Part-time 4WD, electronic transfer switch	"},
          {label:"	Hộp số  		",value:"	Số tự động 6 cấp / 6AT	"},
          {label:"	Hệ thống treo Trước		",value:"	Độc lập, tay đòn kép với thanh cân bằng / Double wishbone with torsion bar	"},
          {label:"	Sau		",value:"	Phụ thuộc, liên kết 4 điểm / Four links with torsion bar	"},
          {label:"	Hệ thống lái Trợ lực tay lái		",value:"	Thủy lực biến thiên theo tốc độ / Hydraulic (VFC)	"},
          {label:"	Hệ thống tay lái tỉ số truyền biến thiên (VGRS)		",value:"	Không có / Without	"},
          {label:"	Vành & lốp xe Loại vành		",value:"	Mâm đúc / Alloy	"},
          {label:"	Kích thước lốp		",value:"	265 / 60R18	"},
          {label:"	Lốp dự phòng		",value:"	Mâm đúc / Alloy	"},
          {label:"	Phanh Trước		",value:"	Đĩa tản nhiệt / Ventilated disc	"},
          {label:"	Sau		",value:"	Đĩa / Disc	"},
          {label:"	Tiêu chuẩn khí thải  		",value:"	Euro 4	"},
          {label:"	Tiêu thụ nhiên liệu Trong đô thị (L / 100km)		",value:"	7.32	"},
          {label:"	Ngoài đô thị (L / 100km)		",value:"	10.85	"},
          {label:"	Kết hợp (L / 100km)		",value:"	8.63	"},
          {label:"	Cụm đèn trước Đèn chiếu gần		",value:"	LED	"},
          {label:"	Đèn chiếu xa		",value:"	LED	"},
          {label:"	Đèn chiếu sáng ban ngày		",value:"	Có / With	"},
          {label:"	Chế độ điều khiển đèn tự động		",value:"	Có / With	"},
          {label:"	Hệ thống cân bằng góc chiếu		",value:"	Tự động / Auto (ALS)	"},
          {label:"	Chế độ đèn chờ dẫn đường		",value:"	Có / With	"},
          {label:"	Cụm đèn sau  		",value:"	LED	"},
          {label:"	Đèn báo phanh trên cao  		",value:"	LED	"},
          {label:"	Đèn sương mù Trước		",value:"	LED	"},
          {label:"	Sau		",value:"	LED	"},
          {label:"	Gương chiếu hậu ngoài Chức năng điều chỉnh điện		",value:"	Có / With	"},
          {label:"	Chức năng gập điện		",value:"	Có / With	"},
          {label:"	Tích hợp đèn chào mừng		",value:"	Có / With	"},
          {label:"	Tích hợp đèn báo rẽ		",value:"	Có / With	"},
          {label:"	Màu		",value:"	Cùng màu thân xe / Colored	"},
          {label:"	Gạt mưa Trước		",value:"	Gián đoạn, điều chỉnh thời gian / Intermittent & Time adjustment	"},
          {label:"	Sau		",value:"	Có (gián đoạn) / With (intermittent)	"},
          {label:"	Chức năng sấy kính sau  		",value:"	Có / With	"},
          {label:"	Ăng ten  		",value:"	Dạng vây cá / Shark fin	"},
          {label:"	Tay nắm cửa ngoài  		",value:"	Mạ crôm / Chrome plating	"},
          {label:"	Bộ quây xe thể thao  		",value:"	Không có / Without	"},
          {label:"	Thanh cản (giảm va chạm) Trước		",value:"	Có / With	"},
          {label:"	Sau		",value:"	Có / With	"},
          {label:"	Chắn bùn  		",value:"	Trước + Sau / Front + Rear	"},
          {label:"	Ống xả kép  		",value:"	Không có / Without	"},
          {label:"	Tay lái Loại tay lái		",value:"	3 chấu / 3-spoke	"},
          {label:"	Chất liệu		",value:"	Bọc da, ốp gỗ, mạ bạc / Leather, wood, silver ornamentation	"},
          {label:"	Nút bấm điều khiển tích hợp		",value:"	Điều chỉnh âm thanh, màn hình hiển thị đa thông tin, đàm thoại rảnh tay, cảnh báo chệch làn đường / Audio switch, MID, hands-free phone, LDA	"},
          {label:"	Điều chỉnh		",value:"	Chỉnh tay 4 hướng / Manual tilt & telescopic	"},
          {label:"	Lẫy chuyển số		",value:"	Có / With	"},
          {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
          {label:"	Gương chiếu hậu trong  		",value:"	Chống chói tự động / EC	"},
          {label:"	Tay nắm cửa trong  		",value:"	Mạ crôm / Chrome plating	"},
          {label:"	Cụm đồng hồ Loại đồng hồ		",value:"	Optitron	"},
          {label:"	Đèn báo Eco		",value:"	Có / With	"},
          {label:"	Chức năng báo lượng tiêu thụ nhiên liệu		",value:"	Có / With	"},
          {label:"	Chức năng báo vị trí cần số		",value:"	Có / With	"},
          {label:"	Màn hình hiển thị đa thông tin		",value:"	Có (màn hình màu TFT 4.2) / With (color TFT 4.2)	"},
          {label:"	Chất liệu bọc ghế  		",value:"	Da / Leather	"},
          {label:"	Ghế trước Loại ghế		",value:"	Loại thể thao / Sport type	"},
          {label:"	Điều chỉnh ghế lái		",value:"	Chỉnh điện 8 hướng / 8 way power	"},
          {label:"	Điều chỉnh ghế hành khách		",value:"	Chỉnh điện 8 hướng / 8 way power	"},
          {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
          {label:"	Chức năng thông gió		",value:"	Không có / Without	"},
          {label:"	Chức năng sưởi		",value:"	Không có / Without	"},
          {label:"	Ghế sau Hàng ghế thứ hai		",value:"	Gập lưng ghế 60:40 một chạm, chỉnh cơ 4 hướng / 60:40 split fold, manual slide & reclining	"},
          {label:"	Hàng ghế thứ ba		",value:"	Ngả lưng ghế, gập 50:50 sang 2 bên / Manual reclining, 50:50 tumble, space up	"},
          {label:"	Tựa tay hàng ghế sau		",value:"	Có / With	"},
          {label:"	Hệ thống điều hòa  		",value:"	Tự động, 2 giàn lạnh / Auto, dual cooler	"},
          {label:"	Cửa gió sau  		",value:"	Có / With	"},
          {label:"	Hộp làm mát  		",value:"	Có / With	"},
          {label:"	Hệ thống âm thanh Đầu đĩa		",value:"	Màn hình cảm ứng 8 navigation / 8 touch screen navigation	"},
          {label:"	Số loa		",value:"	11 loa JBL	"},
          {label:"	Cổng kết nối AUX		",value:"	Không có / Without	"},
          {label:"	Cổng kết nối USB		",value:"	Có / With	"},
          {label:"	Kết nối Bluetooth		",value:"	Có / With	"},
          {label:"	Kết nối điện thoại thông minh / Smartphone connectivity		",value:"	Có / With	"},
          {label:"	Chìa khóa thông minh & Khởi động bằng nút bấm  		",value:"	Có / With	"},
          {label:"	Khóa cửa điện  		",value:"	Có / With	"},
          {label:"	Chức năng khóa cửa từ xa  		",value:"	Có / With	"},
          {label:"	Cửa sổ điều chỉnh điện  		",value:"	Có (1 chạm, chống kẹt tất cả các cửa) / With (Auto, jam protection for all windows)	"},
          {label:"	Cốp điều khiển điện  		",value:"	Mở cốp rảnh tay / Kick active	"},
          {label:"	Hệ thống điều khiển hành trình  		",value:"	Có / With	"},
          {label:"	Hệ thống báo động  		",value:"	Có / With	"},
          {label:"	Hệ thống mã hóa khóa động cơ  		",value:"	Có / With	"},
          {label:"	Hệ thống an toàn Toyota (Toyota Safety Sense) Cảnh báo tiền va chạm (PCS)		",value:"	Có / With	"},
          {label:"	Cảnh báo chệch làn đường (LDA)		",value:"	Có / With	"},
          {label:"	Điều khiển hành trình chủ động (DRCC)		",value:"	Có / With	"},
          {label:"	Hệ thống chống bó cứng phanh (ABS)  		",value:"	Có / With	"},
          {label:"	Hệ thống hỗ trợ lực phanh khẩn cấp (BA)  		",value:"	Có / With	"},
          {label:"	Hệ thống phân phối lực phanh điện tử (EBD)  		",value:"	Có / With	"},
          {label:"	Hệ thống cân bằng điện tử (VSC)  		",value:"	Có / With	"},
          {label:"	Hệ thống kiểm soát lực kéo (TRC)  		",value:"	Có (A-TRC) / With (A-TRC)	"},
          {label:"	Hệ thống hỗ trợ khởi hành ngang dốc (HAC)  		",value:"	Có / With	"},
          {label:"	Hệ thống hỗ trợ đổ đèo (DAC)  		",value:"	Có / With	"},
          {label:"	Đèn báo phanh khẩn cấp (EBS)  		",value:"	Có / With	"},
          {label:"	Camera  		",value:"	Camera 360	"},
          {label:"	Cảm biến hỗ trợ đỗ xe Sau		",value:"	Có / With	"},
          {label:"	Góc trước		",value:"	Có / With	"},
          {label:"	Góc sau		",value:"	Có / With	"},
          {label:"	Túi khí Túi khí người lái & hành khách phía trước		",value:"	Có / With	"},
          {label:"	Túi khí bên hông phía trước		",value:"	Có / With	"},
          {label:"	Túi khí rèm		",value:"	Có / With	"},
          {label:"	Túi khí đầu gối người lái		",value:"	Có / With	"},
          {label:"	Khung xe GOA  		",value:"	Có / With	"},
          {label:"	Dây đai an toàn  		",value:"	3 điểm ELR, 7 vị trí / 3 points ELRx7	"},
          {label:"	Ghế có cấu trúc giảm chấn thương cổ  		",value:"	Có / With	"},
          {label:"	Cột lái tự đổ  		",value:"	Có / With	"},
          {label:"	Bàn đạp phanh tự đổ  		",value:"	Có / With	"}
        ]
      }
  ]

}