import { CarTypeEnum } from "../../car-type.enum";
import { CarInfoInterface } from "../../interfaces";

export class ToyotaVios implements CarInfoInterface {
  name   = 'Toyota Vios'
  type   =  CarTypeEnum.XeDuLich
  imgSrc = 'assets/img/cars/vios.png'
  banner = 'assets/img/toyota/vios/banner.jpg'

  models = [
    {
      brand: 'Toyota Vios 1.5E MT (3 Túi Khí)',
      price: 478000000,
      lingo: 'Khởi xướng trào lưu',  
      seats: 5,
      type: 'Sedan',
      fuelType: 'Xăng',
      manufacture: 'Xe trong nước',
      otherInfo: ['Số tay 5 cấp'],
      library:[
        '/assets/img/toyota/vios/library/czcwkc.jpg',
        '/assets/img/toyota/vios/library/dz5zvo.jpg',
        '/assets/img/toyota/vios/library/fjsivp.jpg',
        '/assets/img/toyota/vios/library/lcalpp.jpg',
        '/assets/img/toyota/vios/library/tab01q.jpg',
        '/assets/img/toyota/vios/library/zj4nwk.jpg'
      ],
      promotion: [
        `Hỗ trợ 1 phần lệ trí trước bạ lên đến 20 triệu dồng,
        áp dụng từ 1/8-31/8/2021`,
        `Sở hữu xe chỉ với 95,2 triệu thanh toán ban đầu, trả góp
        từ 4,0 triệu đồng/tháng trong 6 tháng đầu tiên`
      ],
      colors: [
          {
            label: 'Đỏ - 3G3',
            image: '/assets/img/toyota/vios/colors/1.5E MT/VE-(3R3)-1.png',
            colorCode: 'red'
          },
          {
            label: 'Nâu Vàng - 4R0',
            image: '/assets/img/toyota/vios/colors/1.5E MT/VE-(4R0)-1.png',
            colorCode: '#afa599'
          },
          {
            label: 'Trắng - 040',
            image: '/assets/img/toyota/vios/colors/1.5E MT/VE-(040)-1.png',
            colorCode: 'white'
          },
          {
            label: 'Trắng ngọc trai - 089',
            image: '/assets/img/toyota/vios/colors/1.5E MT/VE-(089)-1.png',
            colorCode: '#f7f9fa'
          },
          {
            label: 'Đen - 218',
            image: '/assets/img/toyota/vios/colors/1.5E MT/VE-(218)-1.png',
            colorCode: 'black'
          },
          {
            label: 'Vàng - 576',
            image: '/assets/img/toyota/vios/colors/1.5E MT/VE-(576)-1.png',
            colorCode: 'yellow'
          },
          {
            label: 'Bạc - 1D6',
            image: '/assets/img/toyota/vios/colors/1.5E MT/VE-(1D6)-1.png',
            colorCode: 'silver'
          }
      ],
      ngoaiThat: {
        label: 'THIẾT KẾ GIÀU CẢM XÚC',
        backgroundImage: '/assets/img/toyota/wigo/ngoai-that/0.png',
        image: '/assets/img/toyota/vios/ngoai-that/rrewc4.jpg',
        features: [
          {
            image: '/assets/img/toyota/vios/ngoai-that/1gmbwf.jpg',
            label: 'Đuôi xe'
          },
          {
            image: '/assets/img/toyota/vios/ngoai-that/bgmjef.jpg',
            label: 'Cụm đèn sau'
          },
          {
            image: '/assets/img/toyota/vios/ngoai-that/h15foc.jpg',
            label: 'Cụm đèn trước'
          },
          {
            image: '/assets/img/toyota/vios/ngoai-that/jvsbxm.jpg',
            label: 'Đầu xe'
          },
          {
            image: '/assets/img/toyota/vios/ngoai-that/mempep.jpg',
            label: 'Mâm xe'
          },
          {
            image: '/assets/img/toyota/vios/ngoai-that/q24lq5.jpg',
            label: 'Gương chiếu hậu ngoài'
          },
          {
            image: '/assets/img/toyota/vios/ngoai-that/vuezqm.jpg',
            label: 'Ăng-ten'
          }
        ]
      },
      noiThat: {
        label: 'TRUYỀN CẢM HỨNG TỪ TIỆN NGHI VÀ THOẢI MÁI',
        backgroundImage: '/assets/img/toyota/wigo/noi-that/0.png',
        image: '/assets/img/toyota/vios/noi-that/l.jpg',
        features: [
          {
            image: '/assets/img/toyota/vios/noi-that/0g24rw.jpg',
            label: 'Hệ thống điều hòa'
          },
          {
            image: '/assets/img/toyota/vios/noi-that/0j2ezj.jpg',
            label: 'Hàng ghế sau gặp thẳng'
          },
          {
            image: '/assets/img/toyota/vios/noi-that/sgkurw.jpg',
            label: 'Cụm đồng hồ'
          },
          {
            image: '/assets/img/toyota/vios/noi-that/1toaq0.jpg',
            label: 'Hàng ghế sau'
          },
          {
            image: '/assets/img/toyota/vios/noi-that/2toejf.jpg',
            label: 'Hệ thống giải trí'
          },
          {
            image: '/assets/img/toyota/vios/noi-that/usycoq.jpg',
            label: 'Khoang hành lý'
          }
        ]
      },
      tinhNang:[
        {
          image: "/assets/img/toyota/vios/tinh-nang/cambien.jpg",
          title: "Cảm biến đuôi xe",
          message: "Khách hàng hoàn toàn yên tâm khi vận hành dù trong không gian nhiều chướng ngại vật"
        },
        {
          image: "/assets/img/toyota/vios/tinh-nang/cambiendoxe.jpg",
          title: "Cảm biến đổ xe",
          message: "Khách hàng hoàn toàn yên tâm khi vận hành dù trong không gian nhiều chướng ngại vật"
        },
        {
          image: "/assets/img/toyota/vios/tinh-nang/cameralui.jpg",
          title: "Camera lùi",
          message: "Camera lùi giúp người lái quan sát được phía sau, thuận tiện và an toàn khi lùi xe, tự tin khi cầm lái"
        },
        {
          image: "/assets/img/toyota/vios/tinh-nang/canbang.jpg",
          title: "Hệ thống cân bằng điện tử",
          message: "VSC kiểm soát công suất động cơ và phân bổ lực phanh hợp lý tới từng bánh xe, nhờ đó giảm thiểu nguy cơ mất lái và trượt bánh xe đặc biệt trên các cung đường trơn trợt khi vào cua gấp"
        },
        {
          image: "/assets/img/toyota/vios/tinh-nang/chongcung.jpg",
          title: "Hệ thống phanh ABS",
          message: "Hệ thống phanh ABS chống bó cưng phanh giúp xe an toàn nhất khi thắng gấp."
        },
        {
          image: "/assets/img/toyota/vios/tinh-nang/dongco.jpg",
          title: "Động cơ",
          message: "Động cơ 2NR-FE (1.5L) mới được trang bị hệ thống điều phối van biến thiên thông minh kép VVT-I mang lại hiệu suất vận hành cao ở mọi địa hình, cho phép tăng tốc êm ái giúp tiết kiệm nhiên liệu tối đa, giảm thiểu ô nhiễm môi trường và gia tăng tuổi thọ cho động cơ."
        },
        {
          image: "/assets/img/toyota/vios/tinh-nang/hethongphanh.jpg",
          title: "Hệ thống phanh",
          message: "Phanh trước dạng đĩa thông gió và phanh sau dạng đĩa đảm bảo lực phanh tối ưu gia tăng tính an toàn để người lái yên tâm và tự tin hơn khi điều khiển xe"
        },
        {
          image: "/assets/img/toyota/vios/tinh-nang/hopso.jpg",
          title: "Hộp số",
          message: "Hộp số sàn 5 cấp giúp tiết kiệm nhiên liệu khi lưu thông qua nhiều địa hình khác nhau. Bảo trì thường ít tốn kém chi phí hơn và kiểm soát xe tốt nhất có thể"
        },
        {
          image: "/assets/img/toyota/vios/tinh-nang/khoihanh.jpg",
          title: "Khởi hành ngang dốc",
          message: "EDB phân bổ lực phanh hợp lý đến các bánh xe, giúp nâng cao hiệu quả phanh, đặc biệt khi xe đang chất tải và vào cua."
        },
        {
          image: "/assets/img/toyota/vios/tinh-nang/kiemsoatluckeo.jpg",
          title: "Kiểm soát lực kéo",
          message: "TRC kiểm soát công suất động cơ và phanh các bánh xe dẫn động nhằm giúp cho xe khởi hành và tăng tốc trên đường trơn trượt."
        },
        {
          image: "/assets/img/toyota/vios/tinh-nang/phanhkhancap.jpg",
          title: "Hỗ trợ lực phanh khẩn cấp",
          message: "Các phiên bản Vios mới đều đã được trang bị hệ thống BA - bổ sung lực phanh lên tới mức tối đa khi người lái đạp phanh khẩn cấp, mang lại sự an tâm cho hành khách trên mọi chuyến đi."
        },
        {
          image: "/assets/img/toyota/vios/tinh-nang/phanphoi.jpg",
          title: "Phân phối phanh điện tử",
          message: "TRC kiểm soát công suất động cơ và phanh các bánh xe dẫn động nhằm giúp cho xe khởi hành và tăng tốc trên đường trơn trượt."
        },
        {
          image: "/assets/img/toyota/vios/tinh-nang/thietkedonghoc.jpg",
          title: "Thiết kế khí động học",
          message: "Thiết kế khí động học giúp tối ưu các khí động, khắc phục các lực cản lên xe, giúp xe vận hành “trơn tru”, đồng thời tăng tính ổn định khi xe đang di chuyển tốc độ cao để đảm bảo an toàn cho người lái."
        },
        {
          image: "/assets/img/toyota/vios/tinh-nang/tuikhi.jpg",
          title: "Túi khí",
          message: "Các dòng xe VIOS mới được trang bị hệ thống 7 túi khí gồm 2 túi khí phía trước, 2 túi khí bên hông phía trước, 2 túi khí rèm và 1 túi khí đầu gối người lái sẽ đảm bảo an toàn cho hành khách và người lái trên mọi hành trình."
        },
        {
          image: "/assets/img/toyota/vios/tinh-nang/vanhanh.jpg",
          title: "Vận hành êm ái",
          message: "Vios thế hệ mới hứa mang lại những trải nghiệm thú vị phía sau tay lái nhưng vẫn tối ưu hóa khả năng tiết kiệm nhiên liệu."
        }
      ],
      thongSo: [
        {label:"	Kích thước Kích thước tổng thể bên ngoài (D x R x C) (mm x mm x mm)		",value:"	4425 x 1730 x 1475	"},
        {label:"	Kích thước tổng thể bên trong (D x R x C) (mm x mm x mm)		",value:"	1895 x 1420 x 1205	"},
        {label:"	Chiều dài cơ sở (mm)		",value:"	2550	"},
        {label:"	Chiều rộng cơ sở (Trước / sau) (mm)		",value:"	1475 / 1460	"},
        {label:"	Khoảng sáng gầm xe (mm)		",value:"	133	"},
        {label:"	Góc thoát (Trước / Sau) (độ / degree)		",value:"	N / A	"},
        {label:"	Bán kính vòng quay tối thiểu (m)		",value:"	5.1	"},
        {label:"	Trọng lượng toàn tải (kg)		",value:"	1550	"},
        {label:"	Dung tích bình nhiên liệu (L)		",value:"	42	"},
        {label:"	Dung tích khoang hành lý (L)		",value:"	N / A	"},
        {label:"	Dung tích khoang chở hàng (L)		",value:"	N / A	"},
        {label:"	Động cơ xăng Loại động cơ		",value:"	2NR-FE	"},
        {label:"	Số xy lanh		",value:"	4	"},
        {label:"	Bố trí xy lanh		",value:"	Thẳng hàng / In line	"},
        {label:"	Dung tích xy lanh (cc)		",value:"	1496	"},
        {label:"	Tỉ số nén		",value:"	11.5	"},
        {label:"	Hệ thống nhiên liệu		",value:"	Phun xăng điện tử / Electronic fuel injection	"},
        {label:"	Loại nhiên liệu		",value:"	Xăng / Petrol	"},
        {label:"	Công suất tối đa ((KW) HP / vòng / phút)		",value:"	79 / 6000	"},
        {label:"	Mô men xoắn tối đa (Nm / vòng / phút)		",value:"	140 / 4200	"},
        {label:"	Tốc độ tối đa		",value:"	180	"},
        {label:"	Khả năng tăng tốc		",value:"	N / A	"},
        {label:"	Hệ số cản khí		",value:"	N / A	"},
        {label:"	Hệ thống ngắt / mở động cơ tự động		",value:"	N / A	"},
        {label:"	Chế độ lái (công suất cao / tiết kiệm nhiên liệu)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống truyền động  		",value:"	Dẫn động cầu trước / FWD	"},
        {label:"	Hộp số  		",value:"	Số sàn 5 cấp / 5MT	"},
        {label:"	Hệ thống treo Trước		",value:"	Độc lập Macpherson / Macpherson strut	"},
        {label:"	Sau		",value:"	Dầm xoắn / Torsion beam	"},
        {label:"	Hệ thống lái Trợ lực tay lái		",value:"	Điện / Electric	"},
        {label:"	Hệ thống tay lái tỉ số truyền biến thiên (VGRS)		",value:"	Không có / Without	"},
        {label:"	Vành & lốp xe Loại vành		",value:"	Mâm đúc / Alloy	"},
        {label:"	Kích thước lốp		",value:"	185 / 60R15	"},
        {label:"	Lốp dự phòng		",value:"	Mâm đúc / Alloy	"},
        {label:"	Phanh Trước		",value:"	Đĩa thông gió / Ventilated disc 15	"},
        {label:"	Sau		",value:"	Đĩa đặc / Solid disc	"},
        {label:"	Tiêu chuẩn khí thải  		",value:"	Euro 4	"},
        {label:"	Tiêu thụ nhiên liệu Trong đô thị (L / 100km)		",value:"	7.74	"},
        {label:"	Ngoài đô thị (L / 100km)		",value:"	4.85	"},
        {label:"	Kết hợp (L / 100km)		",value:"	5.92	"},
        {label:"	Cụm đèn trước Đèn chiếu gần		",value:"	Halogen phản xạ đa hướng / Halogen multi reflect	"},
        {label:"	Đèn chiếu xa		",value:"	Halogen phản xạ đa hướng / Halogen multi reflect	"},
        {label:"	Đèn chiếu sáng ban ngày		",value:"	Không có / Without	"},
        {label:"	Hệ thống rửa đèn		",value:"	Không có / Without	"},
        {label:"	Tự động bật / tắt		",value:"	Không có / Without	"},
        {label:"	Hệ thống mở rộng góc chiếu tự động		",value:"	Không có / Without	"},
        {label:"	Đèn pha tự động		",value:"	Không có / Without	"},
        {label:"	Hệ thống cân bằng góc chiếu		",value:"	Không có / Without	"},
        {label:"	Chế độ đèn chờ dẫn đường		",value:"	Không có / Without	"},
        {label:"	Cụm đèn sau Đèn vị trí		",value:"	Led	"},
        {label:"	Đèn phanh		",value:"	Led	"},
        {label:"	Đèn báo rẽ		",value:"	Bóng thường / Bulb	"},
        {label:"	Đèn lùi		",value:"	Bóng thường / Bulb	"},
        {label:"	Đèn báo phanh trên cao  		",value:"	Bóng thường / Bulb	"},
        {label:"	Đèn sương mù Trước		",value:"	Có / With Led	"},
        {label:"	Sau		",value:"	Không có / Without	"},
        {label:"	Gương chiếu hậu ngoài Chức năng điều chỉnh điện		",value:"	Có / With	"},
        {label:"	Chức năng gập điện		",value:"	Có / With	"},
        {label:"	Cảnh báo điểm mù (BSM)		",value:"	Có / With	"},
        {label:"	Tích hợp đèn chào mừng		",value:"	N / A	"},
        {label:"	Màu		",value:"	Cùng màu thân xe / Colored	"},
        {label:"	Chức năng tự điều chỉnh khi lùi		",value:"	Không có / Without	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Chức năng sấy gương		",value:"	Không có / Without	"},
        {label:"	Chức năng chống bám nước		",value:"	Không có / Without	"},
        {label:"	Chức năng chống chói tự động		",value:"	Không có / Without	"},
        {label:"	Gạt mưa Trước		",value:"	Gián đoạn, điều chỉnh thời gian / Intermittent & Time adjustment	"},
        {label:"	Sau		",value:"	Không có / Without	"},
        {label:"	Chức năng sấy kính sau  		",value:"	Có / With	"},
        {label:"	Ăng ten  		",value:"	Vây cá / Shark fin	"},
        {label:"	Tay nắm cửa ngoài  		",value:"	Cùng màu thân xe / Body color	"},
        {label:"	Bộ quây xe thể thao  		",value:"	Không có / Without	"},
        {label:"	Thanh cản (giảm va chạm) Trước		",value:"	Cùng màu thân xe / Color	"},
        {label:"	Sau		",value:"	Cùng màu thân xe / Color	"},
        {label:"	Lưới tản nhiệt  		",value:"	Color / Sơn đen	"},
        {label:"	Cánh hướng gió sau  		",value:"	Không có / Without	"},
        {label:"	Chắn bùn  		",value:"	Không có / Without	"},
        {label:"	Ống xả kép  		",value:"	Không có / Without	"},
        {label:"	Thanh đỡ nóc xe  		",value:"	Không có / Without	"},
        {label:"			",value:"		"},
        {label:"	Tay lái Loại tay lái		",value:"	3 chấu / 3-spoke	"},
        {label:"	Chất liệu		",value:"	Urethane	"},
        {label:"	Nút bấm điều khiển tích hợp		",value:"	Không có / Without	"},
        {label:"	Điều chỉnh		",value:"	Chỉnh tay 2 hướng / Manual tilt	"},
        {label:"	Lẫy chuyển số		",value:"	Không có / Without	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Gương chiếu hậu trong  		",value:"	2 chế độ ngày và đêm / Day & Night mode	"},
        {label:"	Tay nắm cửa trong  		",value:"	Cùng màu nội thất / Pigmentation	"},
        {label:"	Cụm đồng hồ Loại đồng hồ		",value:"	Analog	"},
        {label:"	Đèn báo Eco		",value:"	Không có / Without	"},
        {label:"	Chức năng báo lượng tiêu thụ nhiên liệu		",value:"	Không có / Without	"},
        {label:"	Chức năng báo vị trí cần số		",value:"	Không có / Without	"},
        {label:"	Màn hình hiển thị đa thông tin		",value:"	Không có / Without	"},
        {label:"	Cửa sổ trời  		",value:"	Không có / Without	"},
        {label:"	Chất liệu bọc ghế  		",value:"	PVC	"},
        {label:"	Ghế trước Loại ghế		",value:"	Thường / Normal	"},
        {label:"	Điều chỉnh ghế lái		",value:"	Chỉnh tay 6 hướng / 6 way manual	"},
        {label:"	Điều chỉnh ghế hành khách		",value:"	Chỉnh tay 4 hướng / 4 way manual	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Chức năng thông gió		",value:"	Không có / Without	"},
        {label:"	Chức năng sưởi		",value:"	Không có / Without	"},
        {label:"	Ghế sau Hàng ghế thứ hai		",value:"	Gập lưng ghế 60:40 / 60:40 Spilt fold	"},
        {label:"	Hàng ghế thứ ba		",value:"	Không có / Without	"},
        {label:"	Hàng ghế thứ bốn		",value:"	Không có / Without	"},
        {label:"	Hàng ghế thứ năm		",value:"	Không có / Without	"},
        {label:"	Tựa tay hàng ghế sau		",value:"	Có / With	"},
        {label:"	Rèm che nắng kính sau  		",value:"	Không có / Without	"},
        {label:"	Rèm che nắng cửa sau  		",value:"	Không có / Without	"},
        {label:"	Hệ thống điều hòa  		",value:"	Chỉnh tay / Manual	"},
        {label:"	Cửa gió sau  		",value:"	Không có / Without	"},
        {label:"	Hộp làm mát  		",value:"	Không có / Without	"},
        {label:"	Hệ thống âm thanh Màn hình		",value:"	DVD, màn hình cảm ứng	"},
        {label:"	Số loa		",value:"	4	"},
        {label:"	Cổng kết nối AUX		",value:"	Không có / Without	"},
        {label:"	Cổng kết nối USB		",value:"	Có / With	"},
        {label:"	Kết nối Bluetooth		",value:"	Có / With	"},
        {label:"	Điều khiển giọng nói		",value:"	Không có / Without	"},
        {label:"	Chức năng điều khiển từ hàng ghế sau		",value:"	Không có / Without	"},
        {label:"	Kết nối wifi		",value:"	Không có / Without	"},
        {label:"	Hệ thống đàm thoại rảnh tay		",value:"	Không có / Without	"},
        {label:"	Kết nối điện thoại thông minh / Smartphone connectivity		",value:"	Có / With	"},
        {label:"	Chìa khóa thông minh & Khởi động bằng nút bấm  		",value:"	Không có / Without	"},
        {label:"	Khóa cửa điện  		",value:"	Có / With	"},
        {label:"	Chức năng khóa cửa từ xa  		",value:"	Có / With	"},
        {label:"	Hệ thống dẫn đường  		",value:"	Không có / Without	"},
        {label:"	Hiển thị thông tin trên kính lái  		",value:"	Không có / Without	"},
        {label:"	Cửa sổ điều chỉnh điện  		",value:"	Tự động lên và chống kẹt bên người lá / Auto Up & Jam protection for driver window	"},
        {label:"	Cốp điều khiển điện  		",value:"	Không có / Without	"},
        {label:"	Hệ thống sạc không dây  		",value:"	Không có / Without	"},
        {label:"	Ga tự động  		",value:"	Không có / Without	"},
        {label:"	Hệ thống theo dõi áp suất lốp  		",value:"	Không có / Without	"},
        {label:"	Hệ thống báo động  		",value:"	Có / With	"},
        {label:"	Hệ thống mã hóa khóa động cơ  		",value:"	Không có / Without	"},
        {label:"	Hệ thống chống bó cứng phanh (ABS)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ lực phanh khẩn cấp (BA)  		",value:"	Có / With	"},
        {label:"	Hệ thống phân phối lực phanh điện tử (EBD)  		",value:"	Có / With	"},
        {label:"	Hệ thống cân bằng điện tử (VSC)  		",value:"	Có / With	"},
        {label:"	Hệ thống kiểm soát lực kéo (TRC)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ khởi hành ngang dốc (HAC)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ đổ đèo (DAC)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống lựa chọn vận tốc vượt địa hình  		",value:"	Không có / Without	"},
        {label:"	Hệ thống thích nghi địa hình (MTS)  		",value:"	Không có / Without	"},
        {label:"	Đèn báo phanh khẩn cấp (EBS)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống cảnh báo điểm mù (BSM)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống cảnh báo phương tiện cắt ngang khi lùi  		",value:"	Không có / Without	"},
        {label:"	Camera lùi  		",value:"	Có / With	"},
        {label:"	Cảm biến hỗ trợ đỗ xe Trước		",value:"	Không có / Without	"},
        {label:"	Sau		",value:"	Có / With	"},
        {label:"	Góc trước		",value:"	Không có / Without	"},
        {label:"	Góc sau		",value:"	Không có / Without	"},
        {label:"	Túi khí Túi khí người lái & hành khách phía trước		",value:"	Có / With	"},
        {label:"	Túi khí bên hông phía trước		",value:"	Không có / Without	"},
        {label:"	Túi khí rèm		",value:"	Không có / Without	"},
        {label:"	Túi khí bên hông phía sau		",value:"	Không có / Without	"},
        {label:"	Túi khí đầu gối người lái		",value:"	Có / With	"},
        {label:"	Túi khí đầu gối hành khách		",value:"	Không có / Without	"},
        {label:"	Dây đai an toàn  		",value:"	3 điểm ELR, 5 vị trí / 3 P ELR x5	"},
        {label:"	Ghế có cấu trúc giảm chấn thương cổ  		",value:"	Có / With	"},
        {label:"	Cột lái tự đổ  		",value:"	Có / With	"},
        {label:"	Bàn đạp phanh tự đổ  		",value:"	Có / With	"}
      ]
      },
     {
       brand: 'Toyota Vios 1.5E CVT (3 Túi Khí)',
       price: 531000000,
       otherInfo: ['Số tay tự động vô cấp','Động cơ xăng dung tích 1.496cm3'],
       promotion: [
        `Hỗ trợ 1 phần lệ trí trước bạ lên đến 20 triệu dồng,
        áp dụng từ 1/8-31/8/2021`,
        `Sở hữu xe chỉ với 106,2 triệu thanh toán ban đầu, trả góp
        từ 4,4 triệu đồng/tháng trong 6 tháng đầu tiên`
       ],
       thongSo: [
        {label:"	Kích thước Kích thước tổng thể bên ngoài (D x R x C) (mm x mm x mm)		",value:"	4425 x 1730 x 1475	"},
        {label:"	Kích thước tổng thể bên trong (D x R x C) (mm x mm x mm)		",value:"	1895 x 1420 x 1205	"},
        {label:"	Chiều dài cơ sở (mm)		",value:"	2550	"},
        {label:"	Chiều rộng cơ sở (Trước / sau) (mm)		",value:"	1475 / 1460	"},
        {label:"	Khoảng sáng gầm xe (mm)		",value:"	133	"},
        {label:"	Góc thoát (Trước / Sau) (độ / degree)		",value:"	N / A	"},
        {label:"	Bán kính vòng quay tối thiểu (m)		",value:"	5.1	"},
        {label:"	Trọng lượng toàn tải (kg)		",value:"	1550	"},
        {label:"	Dung tích bình nhiên liệu (L)		",value:"	42	"},
        {label:"	Dung tích khoang hành lý (L)		",value:"	N / A	"},
        {label:"	Kích thước khoang chở hàng (D x R x C) (mm)		",value:"	N / A	"},
        {label:"	Động cơ xăng Loại động cơ		",value:"	2NR-FE	"},
        {label:"	Số xy lanh		",value:"	4	"},
        {label:"	Bố trí xy lanh		",value:"	Thẳng hàng / In line	"},
        {label:"	Dung tích xy lanh (cc)		",value:"	1496	"},
        {label:"	Tỉ số nén		",value:"	11.5	"},
        {label:"	Hệ thống nhiên liệu		",value:"	Phun xăng điện tử / Electronic fuel injection	"},
        {label:"	Loại nhiên liệu		",value:"	Xăng / Petrol	"},
        {label:"	Công suất tối đa ((KW) HP / vòng / phút)		",value:"	79 / 6000	"},
        {label:"	Mô men xoắn tối đa (Nm / vòng / phút)		",value:"	140 / 4200	"},
        {label:"	Tốc độ tối đa		",value:"	170	"},
        {label:"	Khả năng tăng tốc		",value:"	N / A	"},
        {label:"	Hệ số cản khí		",value:"	N / A	"},
        {label:"	Hệ thống ngắt / mở động cơ tự động		",value:"	N / A	"},
        {label:"	Chế độ lái (công suất cao / tiết kiệm nhiên liệu)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống truyền động  		",value:"	Dẫn động cầu trước / FWD	"},
        {label:"	Hộp số  		",value:"	Hộp số tự động vô cấp / CVT	"},
        {label:"	Hệ thống treo Trước		",value:"	Độc lập Macpherson / Macpherson strut	"},
        {label:"	Sau		",value:"	Dầm xoắn / Torsion beam	"},
        {label:"	Hệ thống lái Trợ lực tay lái		",value:"	Điện / Electric	"},
        {label:"	Hệ thống tay lái tỉ số truyền biến thiên (VGRS)		",value:"	Không có / Without	"},
        {label:"	Vành & lốp xe Loại vành		",value:"	Mâm đúc / Alloy	"},
        {label:"	Kích thước lốp		",value:"	185 / 60R15	"},
        {label:"	Lốp dự phòng		",value:"	Mâm đúc / Alloy	"},
        {label:"	Phanh Trước		",value:"	Đĩa thông gió / Ventilated disc 15'	"},
        {label:"	Sau		",value:"	Đĩa đặc / Solid disc	"},
        {label:"	Tiêu chuẩn khí thải  		",value:"	Euro 4	"},
        {label:"	Tiêu thụ nhiên liệu Trong đô thị (L / 100km)		",value:"	7.49	"},
        {label:"	Ngoài đô thị (L / 100km)		",value:"	4.79	"},
        {label:"	Kết hợp (L / 100km)		",value:"	5.78	"},
        {label:"	Cụm đèn trước Đèn chiếu gần		",value:"	Led	"},
        {label:"	Đèn chiếu xa		",value:"	Led	"},
        {label:"	Đèn chiếu sáng ban ngày		",value:"	Có / With	"},
        {label:"	Hệ thống rửa đèn		",value:"	Không có / Without	"},
        {label:"	Tự động bật / tắt		",value:"	Có / With	"},
        {label:"	Hệ thống nhắc nhở đèn sáng		",value:"	Có / With	"},
        {label:"	Hệ thống mở rộng góc chiếu tự động		",value:"	Không có / Without	"},
        {label:"	Đèn pha tự động		",value:"	Không có / Without	"},
        {label:"	Hệ thống cân bằng góc chiếu		",value:"	Không có / Without	"},
        {label:"	Chế độ đèn chờ dẫn đường		",value:"	Có / With	"},
        {label:"	Cụm đèn sau Đèn vị trí		",value:"	Led	"},
        {label:"	Đèn phanh		",value:"	Led	"},
        {label:"	Đèn báo rẽ		",value:"	Bóng thường / Bulb	"},
        {label:"	Đèn lùi		",value:"	Bóng thường / Bulb	"},
        {label:"	Đèn báo phanh trên cao  		",value:"	LED	"},
        {label:"	Đèn sương mù Trước		",value:"	Có / With Led	"},
        {label:"	Sau		",value:"	Không có / Without	"},
        {label:"	Gương chiếu hậu ngoài Chức năng điều chỉnh điện		",value:"	Có / With	"},
        {label:"	Chức năng gập điện		",value:"	Có / With	"},
        {label:"	Tích hợp đèn chào mừng		",value:"	N / A	"},
        {label:"	Tích hợp đèn báo rẽ		",value:"	Có / With	"},
        {label:"	Màu		",value:"	Cùng màu thân xe / Colored	"},
        {label:"	Chức năng tự điều chỉnh khi lùi		",value:"	Không có / Without	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Chức năng sấy gương		",value:"	Không có / Without	"},
        {label:"	Chức năng chống bám nước		",value:"	Không có / Without	"},
        {label:"	Chức năng chống chói tự động		",value:"	Không có / Without	"},
        {label:"	Gạt mưa Trước		",value:"	Gián đoạn, điều chỉnh thời gian / Intermittent & Time adjustment	"},
        {label:"	Sau		",value:"	Không có / Without	"},
        {label:"	Chức năng sấy kính sau  		",value:"	Có / With	"},
        {label:"	Ăng ten  		",value:"	Vây cá / Shark fin	"},
        {label:"	Tay nắm cửa ngoài  		",value:"	Mạ cờ rôm / Chrome plated	"},
        {label:"	Bộ quây xe thể thao  		",value:"	Không có / Without	"},
        {label:"	Thanh cản (giảm va chạm) Trước		",value:"	Cùng màu thân xe / Color	"},
        {label:"	Sau		",value:"	Cùng màu thân xe / Color	"},
        {label:"	Lưới tản nhiệt  		",value:"	Plating + Color / Sơn đen bóng	"},
        {label:"	Cánh hướng gió sau  		",value:"	Không có / Without	"},
        {label:"	Chắn bùn  		",value:"	Không có / Without	"},
        {label:"	Ống xả kép  		",value:"	Không có / Without	"},
        {label:"	Thanh đỡ nóc xe  		",value:"	Không có / Without	"},
        {label:"	Tay lái Loại tay lái		",value:"	3 chấu / 3-spoke	"},
        {label:"	Chất liệu		",value:"	Bọc da / Leather	"},
        {label:"	Nút bấm điều khiển tích hợp		",value:"	Điều chỉnh âm thanh, bluetooth, màn hình hiển thị đa thông tin / Audio, bluetooth, MID switch	"},
        {label:"	Điều chỉnh		",value:"	Chỉnh tay 2 hướng / Manual tilt	"},
        {label:"	Lẫy chuyển số		",value:"	Không có / Without	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Gương chiếu hậu trong  		",value:"	2 chế độ ngày và đêm / Day & Night mode	"},
        {label:"	Tay nắm cửa trong  		",value:"	Mạ bạc / Silver plating	"},
        {label:"	Cụm đồng hồ Loại đồng hồ		",value:"	Optitron	"},
        {label:"	Đèn báo Eco		",value:"	Có / With	"},
        {label:"	Chức năng báo lượng tiêu thụ nhiên liệu		",value:"	Có / With	"},
        {label:"	Chức năng báo vị trí cần số		",value:"	Có / With	"},
        {label:"	Màn hình hiển thị đa thông tin		",value:"	Màn hình TFT / TFT	"},
        {label:"	Cửa sổ trời  		",value:"	Không có / Without	"},
        {label:"	Chất liệu bọc ghế  		",value:"	Da / Leather + Stitch	"},
        {label:"	Ghế trước Loại ghế		",value:"	Thường / Normal	"},
        {label:"	Điều chỉnh ghế lái		",value:"	Chỉnh tay 6 hướng / 6 way manual	"},
        {label:"	Điều chỉnh ghế hành khách		",value:"	Chỉnh tay 4 hướng / 4 way manual	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Chức năng thông gió		",value:"	Không có / Without	"},
        {label:"	Chức năng sưởi		",value:"	Không có / Without	"},
        {label:"	Ghế sau Hàng ghế thứ hai		",value:"	Gập lưng ghế 60:40 / 60:40 Spilt fold	"},
        {label:"	Hàng ghế thứ ba		",value:"	Không có / Without	"},
        {label:"	Hàng ghế thứ bốn		",value:"	Không có / Without	"},
        {label:"	Hàng ghế thứ năm		",value:"	Không có / Without	"},
        {label:"	Tựa tay hàng ghế sau		",value:"	Có / With	"},
        {label:"	Rèm che nắng kính sau  		",value:"	Không có / Without	"},
        {label:"	Rèm che nắng cửa sau  		",value:"	Không có / Without	"},
        {label:"	Hệ thống điều hòa  		",value:"	Tụ động / Auto	"},
        {label:"	Cửa gió sau  		",value:"	Không có / Without	"},
        {label:"	Hộp làm mát  		",value:"	Không có / Without	"},
        {label:"	Hệ thống âm thanh Màn hình		",value:"	Màn hình cảm ứng / touch screen	"},
        {label:"	Số loa		",value:"	6	"},
        {label:"	Cổng kết nối AUX		",value:"	Không có / Without	"},
        {label:"	Cổng kết nối USB		",value:"	Có / With	"},
        {label:"	Kết nối Bluetooth		",value:"	Có / With	"},
        {label:"	Điều khiển giọng nói		",value:"	Không có / Without	"},
        {label:"	Chức năng điều khiển từ hàng ghế sau		",value:"	Không có / Without	"},
        {label:"	Kết nối wifi		",value:"	Không có / Without	"},
        {label:"	Hệ thống đàm thoại rảnh tay		",value:"	Có / With	"},
        {label:"	Kết nối điện thoại thông minh / Smartphone connectivity		",value:"	Có / With	"},
        {label:"	Chìa khóa thông minh & Khởi động bằng nút bấm  		",value:"	Có / With	"},
        {label:"	Khóa cửa điện  		",value:"	Có / With	"},
        {label:"	Chức năng khóa cửa từ xa  		",value:"	Có / With	"},
        {label:"	Hệ thống dẫn đường  		",value:"	Không có / Without	"},
        {label:"	Hiển thị thông tin trên kính lái  		",value:"	Không có / Without	"},
        {label:"	Cửa sổ điều chỉnh điện  		",value:"	Tự động lên và chống kẹt bên người lá) / Auto Up & Jam protection for driver window	"},
        {label:"	Cốp điều khiển điện  		",value:"	Không có / Without	"},
        {label:"	Hệ thống sạc không dây  		",value:"	Không có / Without	"},
        {label:"	Ga tự động  		",value:"	Có / With	"},
        {label:"	Hệ thống theo dõi áp suất lốp  		",value:"	Không có / Without	"},
        {label:"	Hệ thống báo động  		",value:"	Có / With	"},
        {label:"	Hệ thống mã hóa khóa động cơ  		",value:"	Có / With	"},
        {label:"	Hệ thống chống bó cứng phanh (ABS)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ lực phanh khẩn cấp (BA)  		",value:"	Có / With	"},
        {label:"	Hệ thống phân phối lực phanh điện tử (EBD)  		",value:"	Có / With	"},
        {label:"	Hệ thống cân bằng điện tử (VSC)  		",value:"	Có / With	"},
        {label:"	Hệ thống kiểm soát lực kéo (TRC)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ khởi hành ngang dốc (HAC)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ đổ đèo (DAC)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống lựa chọn vận tốc vượt địa hình  		",value:"	Không có / Without	"},
        {label:"	Hệ thống thích nghi địa hình (MTS)  		",value:"	Không có / Without	"},
        {label:"	Đèn báo phanh khẩn cấp (EBS)  		",value:"	Có / With	"},
        {label:"	Hệ thống cảnh báo điểm mù (BSM)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống cảnh báo phương tiện cắt ngang khi lùi  		",value:"	Không có / Without	"},
        {label:"	Camera lùi  		",value:"	Có / With	"},
        {label:"	Cảm biến hỗ trợ đỗ xe Trước		",value:"	Không có / Without	"},
        {label:"	Sau		",value:"	Có / With	"},
        {label:"	Góc trước		",value:"	Có / With	"},
        {label:"	Góc sau		",value:"	Có / With	"},
        {label:"	Túi khí Túi khí người lái & hành khách phía trước		",value:"	Có / With	"},
        {label:"	Túi khí bên hông phía trước		",value:"	Không có / Without	"},
        {label:"	Túi khí rèm		",value:"	Không có / Without	"},
        {label:"	Túi khí bên hông phía sau		",value:"	Không có / Without	"},
        {label:"	Túi khí đầu gối người lái		",value:"	Có / With	"},
        {label:"	Túi khí đầu gối hành khách		",value:"	Không có / Without	"},
        {label:"	Khung xe GOA  		",value:"	Có / With	"},
        {label:"	Dây đai an toàn  		",value:"	3 điểm ELR, 5 vị trí / 3 P ELR x5	"},
        {label:"	Ghế có cấu trúc giảm chấn thương cổ  		",value:"	Có / With	"},
        {label:"	Cột lái tự đổ  		",value:"	Có / With	"},
        {label:"	Bàn đạp phanh tự đổ  		",value:"	Có / With	"}
      ]
     },
     {
      brand: 'Toyota Vios 1.5E CVT',
      price: 550000000,
      otherInfo: ['Số tay tự động vô cấp','Động cơ xăng dung tích 1.496cm3'],
      promotion: [
        `Hỗ trợ 1 phần lệ trí trước bạ lên đến 20 triệu dồng,
        áp dụng từ 1/8-31/8/2021`,
        `Sở hữu xe chỉ với 110 triệu thanh toán ban đầu, trả góp
        từ 4,6 triệu đồng/tháng trong 6 tháng đầu tiên`
      ],
      thongSo: [
        {label:"	Kích thước Kích thước tổng thể bên ngoài (D x R x C) (mm x mm x mm)		",value:"	4425 x 1730 x 1475	"},
        {label:"	Kích thước tổng thể bên trong (D x R x C) (mm x mm x mm)		",value:"	1895 x 1420 x 1205	"},
        {label:"	Chiều dài cơ sở (mm)		",value:"	2550	"},
        {label:"	Chiều rộng cơ sở (Trước / sau) (mm)		",value:"	1475 / 1460	"},
        {label:"	Khoảng sáng gầm xe (mm)		",value:"	133	"},
        {label:"	Góc thoát (Trước / Sau) (độ / degree)		",value:"	N / A	"},
        {label:"	Bán kính vòng quay tối thiểu (m)		",value:"	5.1	"},
        {label:"	Trọng lượng toàn tải (kg)		",value:"	1550	"},
        {label:"	Dung tích bình nhiên liệu (L)		",value:"	42	"},
        {label:"	Dung tích khoang hành lý (L)		",value:"	N / A	"},
        {label:"	Kích thước khoang chở hàng (D x R x C) (mm)		",value:"	N / A	"},
        {label:"	Động cơ xăng Loại động cơ		",value:"	2NR-FE	"},
        {label:"	Số xy lanh		",value:"	4	"},
        {label:"	Bố trí xy lanh		",value:"	Thẳng hàng / In line	"},
        {label:"	Dung tích xy lanh (cc)		",value:"	1496	"},
        {label:"	Tỉ số nén		",value:"	11.5	"},
        {label:"	Hệ thống nhiên liệu		",value:"	Phun xăng điện tử / Electronic fuel injection	"},
        {label:"	Loại nhiên liệu		",value:"	Xăng / Petrol	"},
        {label:"	Công suất tối đa ((KW) HP / vòng / phút)		",value:"	79 / 6000	"},
        {label:"	Mô men xoắn tối đa (Nm / vòng / phút)		",value:"	140 / 4200	"},
        {label:"	Tốc độ tối đa		",value:"	170	"},
        {label:"	Khả năng tăng tốc		",value:"	N / A	"},
        {label:"	Hệ số cản khí		",value:"	N / A	"},
        {label:"	Hệ thống ngắt / mở động cơ tự động		",value:"	N / A	"},
        {label:"	Chế độ lái (công suất cao / tiết kiệm nhiên liệu)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống truyền động  		",value:"	Dẫn động cầu trước / FWD	"},
        {label:"	Hộp số  		",value:"	Hộp số tự động vô cấp / CVT	"},
        {label:"	Hệ thống treo Trước		",value:"	Độc lập Macpherson / Macpherson strut	"},
        {label:"	Sau		",value:"	Dầm xoắn / Torsion beam	"},
        {label:"	Hệ thống lái Trợ lực tay lái		",value:"	Điện / Electric	"},
        {label:"	Hệ thống tay lái tỉ số truyền biến thiên (VGRS)		",value:"	Không có / Without	"},
        {label:"	Vành & lốp xe Loại vành		",value:"	Mâm đúc / Alloy	"},
        {label:"	Kích thước lốp		",value:"	185 / 60R15	"},
        {label:"	Lốp dự phòng		",value:"	Mâm đúc / Alloy	"},
        {label:"	Phanh Trước		",value:"	Đĩa thông gió / Ventilated disc 15'	"},
        {label:"	Sau		",value:"	Đĩa đặc / Solid disc	"},
        {label:"	Tiêu chuẩn khí thải  		",value:"	Euro 4	"},
        {label:"	Tiêu thụ nhiên liệu Trong đô thị (L / 100km)		",value:"	7.49	"},
        {label:"	Ngoài đô thị (L / 100km)		",value:"	4.79	"},
        {label:"	Kết hợp (L / 100km)		",value:"	5.78	"},
        {label:"	Cụm đèn trước Đèn chiếu gần		",value:"	Led	"},
        {label:"	Đèn chiếu xa		",value:"	Led	"},
        {label:"	Đèn chiếu sáng ban ngày		",value:"	Có / With	"},
        {label:"	Hệ thống rửa đèn		",value:"	Không có / Without	"},
        {label:"	Tự động bật / tắt		",value:"	Có / With	"},
        {label:"	Hệ thống nhắc nhở đèn sáng		",value:"	Có / With	"},
        {label:"	Hệ thống mở rộng góc chiếu tự động		",value:"	Không có / Without	"},
        {label:"	Đèn pha tự động		",value:"	Không có / Without	"},
        {label:"	Hệ thống cân bằng góc chiếu		",value:"	Không có / Without	"},
        {label:"	Chế độ đèn chờ dẫn đường		",value:"	Có / With	"},
        {label:"	Cụm đèn sau Đèn vị trí		",value:"	Led	"},
        {label:"	Đèn phanh		",value:"	Led	"},
        {label:"	Đèn báo rẽ		",value:"	Bóng thường / Bulb	"},
        {label:"	Đèn lùi		",value:"	Bóng thường / Bulb	"},
        {label:"	Đèn báo phanh trên cao  		",value:"	LED	"},
        {label:"	Đèn sương mù Trước		",value:"	Có / With Led	"},
        {label:"	Sau		",value:"	Không có / Without	"},
        {label:"	Gương chiếu hậu ngoài Chức năng điều chỉnh điện		",value:"	Có / With	"},
        {label:"	Chức năng gập điện		",value:"	Có / With	"},
        {label:"	Tích hợp đèn chào mừng		",value:"	N / A	"},
        {label:"	Tích hợp đèn báo rẽ		",value:"	Có / With	"},
        {label:"	Màu		",value:"	Cùng màu thân xe / Colored	"},
        {label:"	Chức năng tự điều chỉnh khi lùi		",value:"	Không có / Without	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Chức năng sấy gương		",value:"	Không có / Without	"},
        {label:"	Chức năng chống bám nước		",value:"	Không có / Without	"},
        {label:"	Chức năng chống chói tự động		",value:"	Không có / Without	"},
        {label:"	Gạt mưa Trước		",value:"	Gián đoạn, điều chỉnh thời gian / Intermittent & Time adjustment	"},
        {label:"	Sau		",value:"	Không có / Without	"},
        {label:"	Chức năng sấy kính sau  		",value:"	Có / With	"},
        {label:"	Ăng ten  		",value:"	Vây cá / Shark fin	"},
        {label:"	Tay nắm cửa ngoài  		",value:"	Mạ cờ rôm / Chrome plated	"},
        {label:"	Bộ quây xe thể thao  		",value:"	Không có / Without	"},
        {label:"	Thanh cản (giảm va chạm) Trước		",value:"	Cùng màu thân xe / Color	"},
        {label:"	Sau		",value:"	Cùng màu thân xe / Color	"},
        {label:"	Lưới tản nhiệt  		",value:"	Plating + Color / Sơn đen bóng	"},
        {label:"	Cánh hướng gió sau  		",value:"	Không có / Without	"},
        {label:"	Chắn bùn  		",value:"	Không có / Without	"},
        {label:"	Ống xả kép  		",value:"	Không có / Without	"},
        {label:"	Thanh đỡ nóc xe  		",value:"	Không có / Without	"},
        {label:"	Tay lái Loại tay lái		",value:"	3 chấu / 3-spoke	"},
        {label:"	Chất liệu		",value:"	Bọc da / Leather	"},
        {label:"	Nút bấm điều khiển tích hợp		",value:"	Điều chỉnh âm thanh, bluetooth, màn hình hiển thị đa thông tin / Audio, bluetooth, MID switch	"},
        {label:"	Điều chỉnh		",value:"	Chỉnh tay 2 hướng / Manual tilt	"},
        {label:"	Lẫy chuyển số		",value:"	Không có / Without	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Gương chiếu hậu trong  		",value:"	2 chế độ ngày và đêm / Day & Night mode	"},
        {label:"	Tay nắm cửa trong  		",value:"	Mạ bạc / Silver plating	"},
        {label:"	Cụm đồng hồ Loại đồng hồ		",value:"	Optitron	"},
        {label:"	Đèn báo Eco		",value:"	Có / With	"},
        {label:"	Chức năng báo lượng tiêu thụ nhiên liệu		",value:"	Có / With	"},
        {label:"	Chức năng báo vị trí cần số		",value:"	Có / With	"},
        {label:"	Màn hình hiển thị đa thông tin		",value:"	Màn hình TFT / TFT	"},
        {label:"	Cửa sổ trời  		",value:"	Không có / Without	"},
        {label:"	Chất liệu bọc ghế  		",value:"	Da / Leather + Stitch	"},
        {label:"	Ghế trước Loại ghế		",value:"	Thường / Normal	"},
        {label:"	Điều chỉnh ghế lái		",value:"	Chỉnh tay 6 hướng / 6 way manual	"},
        {label:"	Điều chỉnh ghế hành khách		",value:"	Chỉnh tay 4 hướng / 4 way manual	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Chức năng thông gió		",value:"	Không có / Without	"},
        {label:"	Chức năng sưởi		",value:"	Không có / Without	"},
        {label:"	Ghế sau Hàng ghế thứ hai		",value:"	Gập lưng ghế 60:40 / 60:40 Spilt fold	"},
        {label:"	Hàng ghế thứ ba		",value:"	Không có / Without	"},
        {label:"	Hàng ghế thứ bốn		",value:"	Không có / Without	"},
        {label:"	Hàng ghế thứ năm		",value:"	Không có / Without	"},
        {label:"	Tựa tay hàng ghế sau		",value:"	Có / With	"},
        {label:"	Rèm che nắng kính sau  		",value:"	Không có / Without	"},
        {label:"	Rèm che nắng cửa sau  		",value:"	Không có / Without	"},
        {label:"	Hệ thống điều hòa  		",value:"	Tụ động / Auto	"},
        {label:"	Cửa gió sau  		",value:"	Không có / Without	"},
        {label:"	Hộp làm mát  		",value:"	Không có / Without	"},
        {label:"	Hệ thống âm thanh Màn hình		",value:"	Màn hình cảm ứng / touch screen	"},
        {label:"	Số loa		",value:"	6	"},
        {label:"	Cổng kết nối AUX		",value:"	Không có / Without	"},
        {label:"	Cổng kết nối USB		",value:"	Có / With	"},
        {label:"	Kết nối Bluetooth		",value:"	Có / With	"},
        {label:"	Điều khiển giọng nói		",value:"	Không có / Without	"},
        {label:"	Chức năng điều khiển từ hàng ghế sau		",value:"	Không có / Without	"},
        {label:"	Kết nối wifi		",value:"	Không có / Without	"},
        {label:"	Hệ thống đàm thoại rảnh tay		",value:"	Có / With	"},
        {label:"	Kết nối điện thoại thông minh / Smartphone connectivity		",value:"	Có / With	"},
        {label:"	Chìa khóa thông minh & Khởi động bằng nút bấm  		",value:"	Có / With	"},
        {label:"	Khóa cửa điện  		",value:"	Có / With	"},
        {label:"	Chức năng khóa cửa từ xa  		",value:"	Có / With	"},
        {label:"	Hệ thống dẫn đường  		",value:"	Không có / Without	"},
        {label:"	Hiển thị thông tin trên kính lái  		",value:"	Không có / Without	"},
        {label:"	Cửa sổ điều chỉnh điện  		",value:"	Tự động lên và chống kẹt bên người lá) / Auto Up & Jam protection for driver window	"},
        {label:"	Cốp điều khiển điện  		",value:"	Không có / Without	"},
        {label:"	Hệ thống sạc không dây  		",value:"	Không có / Without	"},
        {label:"	Ga tự động  		",value:"	Có / With	"},
        {label:"	Hệ thống theo dõi áp suất lốp  		",value:"	Không có / Without	"},
        {label:"	Hệ thống báo động  		",value:"	Có / With	"},
        {label:"	Hệ thống mã hóa khóa động cơ  		",value:"	Có / With	"},
        {label:"	Hệ thống chống bó cứng phanh (ABS)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ lực phanh khẩn cấp (BA)  		",value:"	Có / With	"},
        {label:"	Hệ thống phân phối lực phanh điện tử (EBD)  		",value:"	Có / With	"},
        {label:"	Hệ thống cân bằng điện tử (VSC)  		",value:"	Có / With	"},
        {label:"	Hệ thống kiểm soát lực kéo (TRC)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ khởi hành ngang dốc (HAC)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ đổ đèo (DAC)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống lựa chọn vận tốc vượt địa hình  		",value:"	Không có / Without	"},
        {label:"	Hệ thống thích nghi địa hình (MTS)  		",value:"	Không có / Without	"},
        {label:"	Đèn báo phanh khẩn cấp (EBS)  		",value:"	Có / With	"},
        {label:"	Hệ thống cảnh báo điểm mù (BSM)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống cảnh báo phương tiện cắt ngang khi lùi  		",value:"	Không có / Without	"},
        {label:"	Camera lùi  		",value:"	Có / With	"},
        {label:"	Cảm biến hỗ trợ đỗ xe Trước		",value:"	Không có / Without	"},
        {label:"	Sau		",value:"	Có / With	"},
        {label:"	Góc trước		",value:"	Có / With	"},
        {label:"	Góc sau		",value:"	Có / With	"},
        {label:"	Túi khí Túi khí người lái & hành khách phía trước		",value:"	Có / With	"},
        {label:"	Túi khí bên hông phía trước		",value:"	Không có / Without	"},
        {label:"	Túi khí rèm		",value:"	Không có / Without	"},
        {label:"	Túi khí bên hông phía sau		",value:"	Không có / Without	"},
        {label:"	Túi khí đầu gối người lái		",value:"	Có / With	"},
        {label:"	Túi khí đầu gối hành khách		",value:"	Không có / Without	"},
        {label:"	Khung xe GOA  		",value:"	Có / With	"},
        {label:"	Dây đai an toàn  		",value:"	3 điểm ELR, 5 vị trí / 3 P ELR x5	"},
        {label:"	Ghế có cấu trúc giảm chấn thương cổ  		",value:"	Có / With	"},
        {label:"	Cột lái tự đổ  		",value:"	Có / With	"},
        {label:"	Bàn đạp phanh tự đổ  		",value:"	Có / With	"}
      ]
    },
     {
       brand: 'Toyota Vios 1.5G CVT',
       price: 581000000,
       otherInfo: ['Số tay tự động vô cấp','Động cơ xăng dung tích 1.496cm3'],
       promotion: [
        `Hỗ trợ 1 phần lệ trí trước bạ lên đến 20 triệu dồng,
        áp dụng từ 1/8-31/8/2021`,
        `Sở hữu xe chỉ với 116,2 triệu thanh toán ban đầu, trả góp
        từ 4,8 triệu đồng/tháng trong 6 tháng đầu tiên`
      ],
       thongSo: [
        {label:"	Kích thước Kích thước tổng thể bên ngoài (D x R x C) (mm x mm x mm)		",value:"	4425 x 1730 x 1475	"},
        {label:"	Kích thước tổng thể bên trong (D x R x C) (mm x mm x mm)		",value:"	1895 x 1420 x 1205	"},
        {label:"	Chiều dài cơ sở (mm)		",value:"	2550	"},
        {label:"	Chiều rộng cơ sở (Trước / sau) (mm)		",value:"	1475 / 1460	"},
        {label:"	Khoảng sáng gầm xe (mm)		",value:"	133	"},
        {label:"	Góc thoát (Trước / Sau) (độ / degree)		",value:"	N / A	"},
        {label:"	Bán kính vòng quay tối thiểu (m)		",value:"	5.1	"},
        {label:"	Trọng lượng toàn tải (kg)		",value:"	1550	"},
        {label:"	Dung tích bình nhiên liệu (L)		",value:"	42	"},
        {label:"	Dung tích khoang hành lý (L)		",value:"	N / A	"},
        {label:"	Kích thước khoang chở hàng (D x R x C) (mm)		",value:"	N / A	"},
        {label:"	Động cơ xăng Loại động cơ		",value:"	2NR-FE	"},
        {label:"	Số xy lanh		",value:"	4	"},
        {label:"	Bố trí xy lanh		",value:"	Thẳng hàng / In line	"},
        {label:"	Dung tích xy lanh (cc)		",value:"	1496	"},
        {label:"	Tỉ số nén		",value:"	11.5	"},
        {label:"	Hệ thống nhiên liệu		",value:"	Phun xăng điện tử / Electronic fuel injection	"},
        {label:"	Loại nhiên liệu		",value:"	Xăng / Petrol	"},
        {label:"	Công suất tối đa ((KW) HP / vòng / phút)		",value:"	79 / 6000	"},
        {label:"	Mô men xoắn tối đa (Nm / vòng / phút)		",value:"	140 / 4200	"},
        {label:"	Tốc độ tối đa		",value:"	170	"},
        {label:"	Khả năng tăng tốc		",value:"	N / A	"},
        {label:"	Hệ số cản khí		",value:"	N / A	"},
        {label:"	Hệ thống ngắt / mở động cơ tự động		",value:"	N / A	"},
        {label:"	Chế độ lái (công suất cao / tiết kiệm nhiên liệu)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống truyền động  		",value:"	Dẫn động cầu trước / FWD	"},
        {label:"	Hộp số  		",value:"	Hộp số tự động vô cấp / CVT	"},
        {label:"	Hệ thống treo Trước		",value:"	Độc lập Macpherson / Macpherson strut	"},
        {label:"	Sau		",value:"	Dầm xoắn / Torsion beam	"},
        {label:"	Hệ thống lái Trợ lực tay lái		",value:"	Điện / Electric	"},
        {label:"	Hệ thống tay lái tỉ số truyền biến thiên (VGRS)		",value:"	Không có / Without	"},
        {label:"	Vành & lốp xe Loại vành		",value:"	Mâm đúc / Alloy	"},
        {label:"	Kích thước lốp		",value:"	185 / 60R15	"},
        {label:"	Lốp dự phòng		",value:"	Mâm đúc / Alloy	"},
        {label:"	Phanh Trước		",value:"	Đĩa thông gió / Ventilated disc 15	"},
        {label:"	Sau		",value:"	Đĩa đặc / Solid disc	"},
        {label:"	Tiêu chuẩn khí thải  		",value:"	Euro 4	"},
        {label:"	Tiêu thụ nhiên liệu Trong đô thị (L / 100km)		",value:"	7.53	"},
        {label:"	Ngoài đô thị (L / 100km)		",value:"	4.7	"},
        {label:"	Kết hợp (L / 100km)		",value:"	5.74	"},
        {label:"	Cụm đèn trước Đèn chiếu gần		",value:"	Halogen kiểu đèn chiếu / Halogen Projector	"},
        {label:"	Đèn chiếu xa		",value:"	Halogen phản xạ đa hướng / Halogen multi reflect	"},
        {label:"	Đèn chiếu sáng ban ngày		",value:"	Không có / Without	"},
        {label:"	Hệ thống rửa đèn		",value:"	Không có / Without	"},
        {label:"	Tự động bật / tắt		",value:"	Có / With	"},
        {label:"	Hệ thống nhắc nhở đèn sáng		",value:"	Có / With	"},
        {label:"	Hệ thống mở rộng góc chiếu tự động		",value:"	Không có / Without	"},
        {label:"	Đèn pha tự động		",value:"	Không có / Without	"},
        {label:"	Hệ thống cân bằng góc chiếu		",value:"	Không có / Without	"},
        {label:"	Chế độ đèn chờ dẫn đường		",value:"	Có / With	"},
        {label:"	Cụm đèn sau Đèn vị trí		",value:"	Led	"},
        {label:"	Đèn phanh		",value:"	Led	"},
        {label:"	Đèn báo rẽ		",value:"	Bóng thường / Bulb	"},
        {label:"	Đèn lùi		",value:"	Bóng thường / Bulb	"},
        {label:"	Đèn báo phanh trên cao  		",value:"	Bóng thường / Bulb	"},
        {label:"	Đèn sương mù Trước		",value:"	Có / With Led	"},
        {label:"	Sau		",value:"	Không có / Without	"},
        {label:"	Gương chiếu hậu ngoài Chức năng điều chỉnh điện		",value:"	Có / With	"},
        {label:"	Chức năng gập điện		",value:"	Có / With	"},
        {label:"	Tích hợp đèn chào mừng		",value:"	N / A	"},
        {label:"	Tích hợp đèn báo rẽ		",value:"	Có / With	"},
        {label:"	Màu		",value:"	Cùng màu thân xe / Colored	"},
        {label:"	Chức năng tự điều chỉnh khi lùi		",value:"	Không có / Without	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Chức năng sấy gương		",value:"	Không có / Without	"},
        {label:"	Chức năng chống bám nước		",value:"	Không có / Without	"},
        {label:"	Chức năng chống chói tự động		",value:"	Không có / Without	"},
        {label:"	Gạt mưa Trước		",value:"	Gián đoạn, điều chỉnh thời gian / Intermittent & Time adjustment	"},
        {label:"	Sau		",value:"	Không có / Without	"},
        {label:"	Chức năng sấy kính sau  		",value:"	Có / With	"},
        {label:"	Ăng ten  		",value:"	Vây cá / Shark fin	"},
        {label:"	Tay nắm cửa ngoài  		",value:"	Cùng màu thân xe / Body color	"},
        {label:"	Bộ quây xe thể thao  		",value:"	Không có / Without	"},
        {label:"	Thanh cản (giảm va chạm) Trước		",value:"	Cùng màu thân xe / Color	"},
        {label:"	Sau		",value:"	Cùng màu thân xe / Color	"},
        {label:"	Lưới tản nhiệt  		",value:"	Color / Sơn đen	"},
        {label:"	Cánh hướng gió sau  		",value:"	Không có / Without	"},
        {label:"	Chắn bùn  		",value:"	Không có / Without	"},
        {label:"	Ống xả kép  		",value:"	Không có / Without	"},
        {label:"	Thanh đỡ nóc xe  		",value:"	Không có / Without	"},
        {label:"	Tay lái Loại tay lái		",value:"	3 chấu / 3-spoke	"},
        {label:"	Chất liệu		",value:"	Bọc da / Leather	"},
        {label:"	Nút bấm điều khiển tích hợp		",value:"	Điều chỉnh âm thanh / Audio switch	"},
        {label:"	Điều chỉnh		",value:"	Chỉnh tay 2 hướng / Manual tilt	"},
        {label:"	Lẫy chuyển số		",value:"	Không có / Without	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Gương chiếu hậu trong  		",value:"	2 chế độ ngày và đêm / Day & Night mode	"},
        {label:"	Tay nắm cửa trong  		",value:"	Cùng màu nội thất / Pigmentation	"},
        {label:"	Cụm đồng hồ Loại đồng hồ		",value:"	Optitron	"},
        {label:"	Đèn báo Eco		",value:"	Có / With	"},
        {label:"	Chức năng báo lượng tiêu thụ nhiên liệu		",value:"	Có / With	"},
        {label:"	Chức năng báo vị trí cần số		",value:"	Có / With	"},
        {label:"	Màn hình hiển thị đa thông tin		",value:"	Có / With	"},
        {label:"	Cửa sổ trời  		",value:"	Không có / Without	"},
        {label:"	Chất liệu bọc ghế  		",value:"	Da / Leather + Stitch	"},
        {label:"	Ghế trước Loại ghế		",value:"	Thường / Normal	"},
        {label:"	Điều chỉnh ghế lái		",value:"	Chỉnh tay 6 hướng / 6 way manual	"},
        {label:"	Điều chỉnh ghế hành khách		",value:"	Chỉnh tay 4 hướng / 4 way manual	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Chức năng thông gió		",value:"	Không có / Without	"},
        {label:"	Chức năng sưởi		",value:"	Không có / Without	"},
        {label:"	Ghế sau Hàng ghế thứ hai		",value:"	Gập lưng ghế 60:40 / 60:40 Spilt fold	"},
        {label:"	Hàng ghế thứ ba		",value:"	Không có / Without	"},
        {label:"	Hàng ghế thứ bốn		",value:"	Không có / Without	"},
        {label:"	Hàng ghế thứ năm		",value:"	Không có / Without	"},
        {label:"	Tựa tay hàng ghế sau		",value:"	Có / With	"},
        {label:"	Rèm che nắng kính sau  		",value:"	Không có / Without	"},
        {label:"	Rèm che nắng cửa sau  		",value:"	Không có / Without	"},
        {label:"	Hệ thống điều hòa  		",value:"	Chỉnh tay / Manual	"},
        {label:"	Cửa gió sau  		",value:"	Không có / Without	"},
        {label:"	Hộp làm mát  		",value:"	Không có / Without	"},
        {label:"	Hệ thống âm thanh Màn hình		",value:"	Màn hình cảm ứng / touch screen	"},
        {label:"	Số loa		",value:"	4	"},
        {label:"	Cổng kết nối AUX		",value:"	Không có / Without	"},
        {label:"	Cổng kết nối USB		",value:"	Có / With	"},
        {label:"	Kết nối Bluetooth		",value:"	Có / With	"},
        {label:"	Điều khiển giọng nói		",value:"	Không có / Without	"},
        {label:"	Chức năng điều khiển từ hàng ghế sau		",value:"	Không có / Without	"},
        {label:"	Kết nối wifi		",value:"	Không có / Without	"},
        {label:"	Hệ thống đàm thoại rảnh tay		",value:"	Không có / Without	"},
        {label:"	Kết nối điện thoại thông minh / Smartphone connectivity		",value:"	Có / With	"},
        {label:"	Chìa khóa thông minh & Khởi động bằng nút bấm  		",value:"	Không có / Without	"},
        {label:"	Khóa cửa điện  		",value:"	Có / With	"},
        {label:"	Chức năng khóa cửa từ xa  		",value:"	Có / With	"},
        {label:"	Hệ thống dẫn đường  		",value:"	Không có / Without	"},
        {label:"	Hiển thị thông tin trên kính lái  		",value:"	Không có / Without	"},
        {label:"	Cửa sổ điều chỉnh điện  		",value:"	Tự động lên và chống kẹt bên người lá) / Auto Up & Jam protection for driver window	"},
        {label:"	Cốp điều khiển điện  		",value:"	Không có / Without	"},
        {label:"	Hệ thống sạc không dây  		",value:"	Không có / Without	"},
        {label:"	Ga tự động  		",value:"	Không có / Without	"},
        {label:"	Hệ thống theo dõi áp suất lốp  		",value:"	Không có / Without	"},
        {label:"	Hệ thống báo động  		",value:"	Có / With	"},
        {label:"	Hệ thống mã hóa khóa động cơ  		",value:"	Có / With	"},
        {label:"	Hệ thống chống bó cứng phanh (ABS)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ lực phanh khẩn cấp (BA)  		",value:"	Có / With	"},
        {label:"	Hệ thống phân phối lực phanh điện tử (EBD)  		",value:"	Có / With	"},
        {label:"	Hệ thống cân bằng điện tử (VSC)  		",value:"	Có / With	"},
        {label:"	Hệ thống kiểm soát lực kéo (TRC)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ khởi hành ngang dốc (HAC)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ đổ đèo (DAC)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống lựa chọn vận tốc vượt địa hình  		",value:"	Không có / Without	"},
        {label:"	Hệ thống thích nghi địa hình (MTS)  		",value:"	Không có / Without	"},
        {label:"	Đèn báo phanh khẩn cấp (EBS)  		",value:"	Có / With	"},
        {label:"	Hệ thống cảnh báo điểm mù (BSM)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống cảnh báo phương tiện cắt ngang khi lùi  		",value:"	Không có / Without	"},
        {label:"	Camera lùi  		",value:"	Có / With	"},
        {label:"	Cảm biến hỗ trợ đỗ xe Trước		",value:"	Không có / Without	"},
        {label:"	Sau		",value:"	Có / With	"},
        {label:"	Góc trước		",value:"	Không có / Without	"},
        {label:"	Góc sau		",value:"	Không có / Without	"},
        {label:"	Túi khí Túi khí người lái & hành khách phía trước		",value:"	Có / With	"},
        {label:"	Túi khí bên hông phía trước		",value:"	Không có / Without	"},
        {label:"	Túi khí rèm		",value:"	Không có / Without	"},
        {label:"	Túi khí bên hông phía sau		",value:"	Không có / Without	"},
        {label:"	Túi khí đầu gối người lái		",value:"	Có / With	"},
        {label:"	Túi khí đầu gối hành khách		",value:"	Không có / Without	"},
        {label:"	Khung xe GOA  		",value:"	Có / With	"},
        {label:"	Dây đai an toàn  		",value:"	3 điểm ELR, 5 vị trí / 3 P ELR x5	"},
        {label:"	Ghế có cấu trúc giảm chấn thương cổ  		",value:"	Có / With	"},
        {label:"	Cột lái tự đổ  		",value:"	Có / With	"},
        {label:"	Bàn đạp phanh tự đổ  		",value:"	Có / With	"}
      ]
     },
     {
       brand: 'Toyota Vios 1.5E MT',
       price: 495000000,
       promotion: [
        `Hỗ trợ 1 phần lệ trí trước bạ lên đến 20 triệu dồng,
        áp dụng từ 1/8-31/8/2021`,
        `Sở hữu xe chỉ với 99 triệu thanh toán ban đầu, trả góp
        từ 4,1 triệu đồng/tháng trong 6 tháng đầu tiên`
      ],
       thongSo: [
        {label:"	Kích thước Kích thước tổng thể bên ngoài (D x R x C) (mm x mm x mm)		",value:"	4425 x 1730 x 1475	"},
        {label:"	Kích thước tổng thể bên trong (D x R x C) (mm x mm x mm)		",value:"	1895 x 1420 x 1205	"},
        {label:"	Chiều dài cơ sở (mm)		",value:"	2550	"},
        {label:"	Chiều rộng cơ sở (Trước / sau) (mm)		",value:"	1475 / 1460	"},
        {label:"	Khoảng sáng gầm xe (mm)		",value:"	133	"},
        {label:"	Góc thoát (Trước / Sau) (độ / degree)		",value:"	N / A	"},
        {label:"	Bán kính vòng quay tối thiểu (m)		",value:"	5.1	"},
        {label:"	Trọng lượng toàn tải (kg)		",value:"	1550	"},
        {label:"	Dung tích bình nhiên liệu (L)		",value:"	42	"},
        {label:"	Dung tích khoang hành lý (L)		",value:"	N / A	"},
        {label:"	Dung tích khoang chở hàng (L)		",value:"	N / A	"},
        {label:"	Động cơ xăng Loại động cơ		",value:"	2NR-FE	"},
        {label:"	Số xy lanh		",value:"	4	"},
        {label:"	Bố trí xy lanh		",value:"	Thẳng hàng / In line	"},
        {label:"	Dung tích xy lanh (cc)		",value:"	1496	"},
        {label:"	Tỉ số nén		",value:"	11.5	"},
        {label:"	Hệ thống nhiên liệu		",value:"	Phun xăng điện tử / Electronic fuel injection	"},
        {label:"	Loại nhiên liệu		",value:"	Xăng / Petrol	"},
        {label:"	Công suất tối đa ((KW) HP / vòng / phút)		",value:"	79 / 6000	"},
        {label:"	Mô men xoắn tối đa (Nm / vòng / phút)		",value:"	140 / 4200	"},
        {label:"	Tốc độ tối đa		",value:"	180	"},
        {label:"	Khả năng tăng tốc		",value:"	N / A	"},
        {label:"	Hệ số cản khí		",value:"	N / A	"},
        {label:"	Hệ thống ngắt / mở động cơ tự động		",value:"	N / A	"},
        {label:"	Chế độ lái (công suất cao / tiết kiệm nhiên liệu)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống truyền động  		",value:"	Dẫn động cầu trước / FWD	"},
        {label:"	Hộp số  		",value:"	Số sàn 5 cấp / 5MT	"},
        {label:"	Hệ thống treo Trước		",value:"	Độc lập Macpherson / Macpherson strut	"},
        {label:"	Sau		",value:"	Dầm xoắn / Torsion beam	"},
        {label:"	Hệ thống lái Trợ lực tay lái		",value:"	Điện / Electric	"},
        {label:"	Hệ thống tay lái tỉ số truyền biến thiên (VGRS)		",value:"	Không có / Without	"},
        {label:"	Vành & lốp xe Loại vành		",value:"	Mâm đúc / Alloy	"},
        {label:"	Kích thước lốp		",value:"	185 / 60R15	"},
        {label:"	Lốp dự phòng		",value:"	Mâm đúc / Alloy	"},
        {label:"	Phanh Trước		",value:"	Đĩa thông gió / Ventilated disc 15	"},
        {label:"	Sau		",value:"	Đĩa đặc / Solid disc	"},
        {label:"	Tiêu chuẩn khí thải  		",value:"	Euro 4	"},
        {label:"	Tiêu thụ nhiên liệu Trong đô thị (L / 100km)		",value:"	7.74	"},
        {label:"	Ngoài đô thị (L / 100km)		",value:"	4.85	"},
        {label:"	Kết hợp (L / 100km)		",value:"	5.92	"},
        {label:"	Cụm đèn trước Đèn chiếu gần		",value:"	Halogen phản xạ đa hướng / Halogen multi reflect	"},
        {label:"	Đèn chiếu xa		",value:"	Halogen phản xạ đa hướng / Halogen multi reflect	"},
        {label:"	Đèn chiếu sáng ban ngày		",value:"	Không có / Without	"},
        {label:"	Hệ thống rửa đèn		",value:"	Không có / Without	"},
        {label:"	Tự động bật / tắt		",value:"	Không có / Without	"},
        {label:"	Hệ thống mở rộng góc chiếu tự động		",value:"	Không có / Without	"},
        {label:"	Đèn pha tự động		",value:"	Không có / Without	"},
        {label:"	Hệ thống cân bằng góc chiếu		",value:"	Không có / Without	"},
        {label:"	Chế độ đèn chờ dẫn đường		",value:"	Không có / Without	"},
        {label:"	Cụm đèn sau Đèn vị trí		",value:"	Led	"},
        {label:"	Đèn phanh		",value:"	Led	"},
        {label:"	Đèn báo rẽ		",value:"	Bóng thường / Bulb	"},
        {label:"	Đèn lùi		",value:"	Bóng thường / Bulb	"},
        {label:"	Đèn báo phanh trên cao  		",value:"	Bóng thường / Bulb	"},
        {label:"	Đèn sương mù Trước		",value:"	Có / With Led	"},
        {label:"	Sau		",value:"	Không có / Without	"},
        {label:"	Gương chiếu hậu ngoài Chức năng điều chỉnh điện		",value:"	Có / With	"},
        {label:"	Chức năng gập điện		",value:"	Có / With	"},
        {label:"	Cảnh báo điểm mù (BSM)		",value:"	Có / With	"},
        {label:"	Tích hợp đèn chào mừng		",value:"	N / A	"},
        {label:"	Màu		",value:"	Cùng màu thân xe / Colored	"},
        {label:"	Chức năng tự điều chỉnh khi lùi		",value:"	Không có / Without	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Chức năng sấy gương		",value:"	Không có / Without	"},
        {label:"	Chức năng chống bám nước		",value:"	Không có / Without	"},
        {label:"	Chức năng chống chói tự động		",value:"	Không có / Without	"},
        {label:"	Gạt mưa Trước		",value:"	Gián đoạn, điều chỉnh thời gian / Intermittent & Time adjustment	"},
        {label:"	Sau		",value:"	Không có / Without	"},
        {label:"	Chức năng sấy kính sau  		",value:"	Có / With	"},
        {label:"	Ăng ten  		",value:"	Vây cá / Shark fin	"},
        {label:"	Tay nắm cửa ngoài  		",value:"	Cùng màu thân xe / Body color	"},
        {label:"	Bộ quây xe thể thao  		",value:"	Không có / Without	"},
        {label:"	Thanh cản (giảm va chạm) Trước		",value:"	Cùng màu thân xe / Color	"},
        {label:"	Sau		",value:"	Cùng màu thân xe / Color	"},
        {label:"	Lưới tản nhiệt  		",value:"	Color / Sơn đen	"},
        {label:"	Cánh hướng gió sau  		",value:"	Không có / Without	"},
        {label:"	Chắn bùn  		",value:"	Không có / Without	"},
        {label:"	Ống xả kép  		",value:"	Không có / Without	"},
        {label:"	Thanh đỡ nóc xe  		",value:"	Không có / Without	"},
        {label:"			",value:"		"},
        {label:"	Tay lái Loại tay lái		",value:"	3 chấu / 3-spoke	"},
        {label:"	Chất liệu		",value:"	Urethane	"},
        {label:"	Nút bấm điều khiển tích hợp		",value:"	Không có / Without	"},
        {label:"	Điều chỉnh		",value:"	Chỉnh tay 2 hướng / Manual tilt	"},
        {label:"	Lẫy chuyển số		",value:"	Không có / Without	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Gương chiếu hậu trong  		",value:"	2 chế độ ngày và đêm / Day & Night mode	"},
        {label:"	Tay nắm cửa trong  		",value:"	Cùng màu nội thất / Pigmentation	"},
        {label:"	Cụm đồng hồ Loại đồng hồ		",value:"	Analog	"},
        {label:"	Đèn báo Eco		",value:"	Không có / Without	"},
        {label:"	Chức năng báo lượng tiêu thụ nhiên liệu		",value:"	Không có / Without	"},
        {label:"	Chức năng báo vị trí cần số		",value:"	Không có / Without	"},
        {label:"	Màn hình hiển thị đa thông tin		",value:"	Không có / Without	"},
        {label:"	Cửa sổ trời  		",value:"	Không có / Without	"},
        {label:"	Chất liệu bọc ghế  		",value:"	PVC	"},
        {label:"	Ghế trước Loại ghế		",value:"	Thường / Normal	"},
        {label:"	Điều chỉnh ghế lái		",value:"	Chỉnh tay 6 hướng / 6 way manual	"},
        {label:"	Điều chỉnh ghế hành khách		",value:"	Chỉnh tay 4 hướng / 4 way manual	"},
        {label:"	Bộ nhớ vị trí		",value:"	Không có / Without	"},
        {label:"	Chức năng thông gió		",value:"	Không có / Without	"},
        {label:"	Chức năng sưởi		",value:"	Không có / Without	"},
        {label:"	Ghế sau Hàng ghế thứ hai		",value:"	Gập lưng ghế 60:40 / 60:40 Spilt fold	"},
        {label:"	Hàng ghế thứ ba		",value:"	Không có / Without	"},
        {label:"	Hàng ghế thứ bốn		",value:"	Không có / Without	"},
        {label:"	Hàng ghế thứ năm		",value:"	Không có / Without	"},
        {label:"	Tựa tay hàng ghế sau		",value:"	Có / With	"},
        {label:"	Rèm che nắng kính sau  		",value:"	Không có / Without	"},
        {label:"	Rèm che nắng cửa sau  		",value:"	Không có / Without	"},
        {label:"	Hệ thống điều hòa  		",value:"	Chỉnh tay / Manual	"},
        {label:"	Cửa gió sau  		",value:"	Không có / Without	"},
        {label:"	Hộp làm mát  		",value:"	Không có / Without	"},
        {label:"	Hệ thống âm thanh Màn hình		",value:"	DVD, màn hình cảm ứng	"},
        {label:"	Số loa		",value:"	4	"},
        {label:"	Cổng kết nối AUX		",value:"	Không có / Without	"},
        {label:"	Cổng kết nối USB		",value:"	Có / With	"},
        {label:"	Kết nối Bluetooth		",value:"	Có / With	"},
        {label:"	Điều khiển giọng nói		",value:"	Không có / Without	"},
        {label:"	Chức năng điều khiển từ hàng ghế sau		",value:"	Không có / Without	"},
        {label:"	Kết nối wifi		",value:"	Không có / Without	"},
        {label:"	Hệ thống đàm thoại rảnh tay		",value:"	Không có / Without	"},
        {label:"	Kết nối điện thoại thông minh / Smartphone connectivity		",value:"	Có / With	"},
        {label:"	Chìa khóa thông minh & Khởi động bằng nút bấm  		",value:"	Không có / Without	"},
        {label:"	Khóa cửa điện  		",value:"	Có / With	"},
        {label:"	Chức năng khóa cửa từ xa  		",value:"	Có / With	"},
        {label:"	Hệ thống dẫn đường  		",value:"	Không có / Without	"},
        {label:"	Hiển thị thông tin trên kính lái  		",value:"	Không có / Without	"},
        {label:"	Cửa sổ điều chỉnh điện  		",value:"	Tự động lên và chống kẹt bên người lá) / Auto Up & Jam protection for driver window	"},
        {label:"	Cốp điều khiển điện  		",value:"	Không có / Without	"},
        {label:"	Hệ thống sạc không dây  		",value:"	Không có / Without	"},
        {label:"	Ga tự động  		",value:"	Không có / Without	"},
        {label:"	Hệ thống theo dõi áp suất lốp  		",value:"	Không có / Without	"},
        {label:"	Hệ thống báo động  		",value:"	Có / With	"},
        {label:"	Hệ thống mã hóa khóa động cơ  		",value:"	Không có / Without	"},
        {label:"	Hệ thống chống bó cứng phanh (ABS)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ lực phanh khẩn cấp (BA)  		",value:"	Có / With	"},
        {label:"	Hệ thống phân phối lực phanh điện tử (EBD)  		",value:"	Có / With	"},
        {label:"	Hệ thống cân bằng điện tử (VSC)  		",value:"	Có / With	"},
        {label:"	Hệ thống kiểm soát lực kéo (TRC)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ khởi hành ngang dốc (HAC)  		",value:"	Có / With	"},
        {label:"	Hệ thống hỗ trợ đổ đèo (DAC)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống lựa chọn vận tốc vượt địa hình  		",value:"	Không có / Without	"},
        {label:"	Hệ thống thích nghi địa hình (MTS)  		",value:"	Không có / Without	"},
        {label:"	Đèn báo phanh khẩn cấp (EBS)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống cảnh báo điểm mù (BSM)  		",value:"	Không có / Without	"},
        {label:"	Hệ thống cảnh báo phương tiện cắt ngang khi lùi  		",value:"	Không có / Without	"},
        {label:"	Camera lùi  		",value:"	Có / With	"},
        {label:"	Cảm biến hỗ trợ đỗ xe Trước		",value:"	Không có / Without	"},
        {label:"	Sau		",value:"	Có / With	"},
        {label:"	Góc trước		",value:"	Không có / Without	"},
        {label:"	Góc sau		",value:"	Không có / Without	"},
        {label:"	Túi khí Số lượng túi khí		",value:"	7 túi khí	"},
        {label:"	Túi khí người lái & hành khách phía trước		",value:"	Có / With	"},
        {label:"	Túi khí bên hông phía trước		",value:"	Có / With	"},
        {label:"	Túi khí rèm		",value:"	Có / With	"},
        {label:"	Túi khí bên hông phía sau		",value:"	Không có / Without	"},
        {label:"	Túi khí đầu gối người lái		",value:"	Có / With	"},
        {label:"	Túi khí đầu gối hành khách		",value:"	Không có / Without	"},
        {label:"	Dây đai an toàn  		",value:"	3 điểm ELR, 5 vị trí / 3 P ELR x5	"},
        {label:"	Ghế có cấu trúc giảm chấn thương cổ  		",value:"	Có / With	"},
        {label:"	Cột lái tự đổ  		",value:"	Có / With	"},
        {label:"	Bàn đạp phanh tự đổ  		",value:"	Có / With	"}
      ]
     }
  ]
}
