import { CarTypeEnum } from "../../car-type.enum";
import { CarInfoInterface } from "../../interfaces";

export class ToyotaAvanza implements CarInfoInterface {
  name = 'Toyota Avanza'
  type = CarTypeEnum.XeChuyenDung
  imgSrc = 'assets/img/cars/avanza.png'
  models = [
    {
      brand: 'Toyota Avanza MT',
      price: 544000000,
      lingo: 'Mang yêu thương cho mỗi hành trình',
      seats: 7,
      type: 'Đa dụng',
      fuelType: 'Xăng',
      manufacture: 'Xe nhập khẩu',
      otherInfo: ['Số sàn 5 cấp'],
      library:[
        '/assets/img/toyota/avanza/MT/library/2ys5br.jpg',
        '/assets/img/toyota/avanza/MT/library/ckbbbm.jpg',
        '/assets/img/toyota/avanza/MT/library/dr0g0m.jpg',
        '/assets/img/toyota/avanza/MT/library/nl1nql.jpg'
      ],
      colors:[
        {
          label:'Bạc - 1E7',
          image:'/assets/img/toyota/avanza/colors/MT/Bac-1E7-MT.png',
          colorCode: '#dedfe1'
        },
        {
          label:'Vàng - T23',
          image:'/assets/img/toyota/avanza/colors/MT/Be-T23-MT.png',
          colorCode: '#cfcbc1'
        },
        {
          label:'Đen - X12',
          image:'/assets/img/toyota/avanza/colors/MT/Den-X12-MT.png',
          colorCode: 'black'
        },
        {
          label:'Trắng - W09',
          image:'/assets/img/toyota/avanza/colors/MT/Trang-W09-MT.png',
          colorCode: 'white'
        },
        {
          label:'Xám - 1G3',
          image:'/assets/img/toyota/avanza/colors/MT/Xam-1G3-AT.png',
          colorCode: '#94989b'
        },
        {
          label:'Xanh sẫm - B79',
          image:'/assets/img/toyota/avanza/colors/MT/Xanh-8X2-MT.png',
          colorCode: '#133368'
        }
      ],
      ngoaiThat: {
        label: 'THIẾT KẾ MẠNH MẼ ĐẦY UY LỰC',
        backgroundImage: '/assets/img/toyota/wigo/ngoai-that/0.png',
        image: '/assets/img/toyota/avanza/MT/ngoai-that/0rdr2w.jpg',
        features: [
          {
            image: '/assets/img/toyota/avanza/MT/ngoai-that/42uajl.jpg',
            label: 'Cụm đèn sau'
          },
          {
            image: '/assets/img/toyota/avanza/MT/ngoai-that/d4o1bf.jpg',
            label: 'Đuôi xe'
          },
          {
            image: '/assets/img/toyota/avanza/MT/ngoai-that/fvr2vc.jpg',
            label: 'Đèn sương mù'
          },
          {
            image: '/assets/img/toyota/avanza/MT/ngoai-that/gyjkoz.jpg',
            label: 'Gương chiếu hậu'
          },
          {
            image: '/assets/img/toyota/avanza/MT/ngoai-that/nmcird.jpg',
            label: 'Cánh hướng gió sau'
          },
          {
            image: '/assets/img/toyota/avanza/MT/ngoai-that/sgbasc.jpg',
            label: 'Cụm đèn trước'
          }
        ]
      },
      noiThat: {
        label: 'Diện mạo tinh tế, mạnh mẽ',
        backgroundImage: '/assets/img/toyota/wigo/noi-that/0.png',
        image: '/assets/img/toyota/avanza/MT/noi-that/hbrphl.jpg',
        features: [
          {
            image: '/assets/img/toyota/avanza/MT/noi-that/z4ddei.jpg',
            label: 'Hộc chứa đồ'
          },
          {
            image: '/assets/img/toyota/avanza/MT/noi-that/e2lffq.jpg',
            label: 'Hệ thống âm thanh'
          },
          {
            image: '/assets/img/toyota/avanza/MT/noi-that/zlmjne.jpg',
            label: 'Hệ thống điều hòa'
          }
        ]
      },
      tinhNang:[
        {
          image: "/assets/img/toyota/avanza/MT/tinh-nang/5dcbeo.jpg",
          title: "Hộp số",
          message: "Hộp số sàn 5 cấp (1.3MT) hỗ trợ vận hành mượt mà và tiết kiệm nhiên liệu tối ưu trên mọi cung đường."
        },
        {
          image: "/assets/img/toyota/avanza/MT/tinh-nang/41modv.jpg",
          title: "Bán kính vòng quay",
          message: "Bán kính vòng quay tối thiểu nhỏ - 4.7m cho phép xe chuyển động linh hoạt trên mọi cung đường."
        },
        {
          image: "/assets/img/toyota/avanza/MT/tinh-nang/eamrjh.jpg",
          title: "Túi khí",
          message: "Hai túi khí trang bị cho nguyowif lái và hành khách phía trước mang lại sự an tâm trong mỗi chuyến đi."
        },
        {
          image: "/assets/img/toyota/avanza/MT/tinh-nang/eqx2tv.jpg",
          title: "Hệ thống phân phối lực phanh điện",
          message: "Hệ thống phân phối lực phanh điện tử EBD phân bố lực phanh hợp lý đến các bánh xe, giúp nâng cao hiệu quả phanh, đặc biệt khi xe đang chất tải và cào cua."
        },
        {
          image: "/assets/img/toyota/avanza/MT/tinh-nang/etbpjx.jpg",
          title: "Hệ thống chống bó cứng phanh (ABS)",
          message: "ABS giúp các bánh xe không bị bó cứng khi phanh gấp hay phanh trên đường trơn trượt, đảm bảo an toàn cho người lái và hành khách trên xe."
        },
        {
          image: "/assets/img/toyota/avanza/MT/tinh-nang/y3n5tw.jpg",
          title: "Hệ thống treo trước",
          message: "Hệ thống treo trước giúp xe vận hành êm dịu và đảm bảo bộ bám đường cho bánh xe."
        }
      ],
      thongSo: [
        {label:"	Kích thướcKích thước tổng thể bên ngoài (D x R x C) (mm x mm x mm)	",
        value:"	4190 x 1660 x 1740	"},
        {label:"	Kích thước tổng thể bên trong (D x R x C) (mm x mm x mm)	",
        value:"	2480 x 1415 x 1270	"},
        {label:"	Chiều dài cơ sở (mm)	",
        value:"	2655	"},
        {label:"	Chiều rộng cơ sở (Trước/sau) (mm)	",
        value:"	1425/1435	"},
        {label:"	Khoảng sáng gầm xe (mm)	",
        value:"	200	"},
        {label:"	Bán kính vòng quay tối thiểu (m)	",
        value:"	4,7	"},
        {label:"	Trọng lượng không tải (kg)	",
        value:"	1130	"},
        {label:"	Trọng lượng toàn tải (kg)	",
        value:"	1680	"},
        {label:"	Dung tích bình nhiên liệu (L)	",
        value:"	45	"},
        {label:"	Dung tích khoang hành lý (L)	",
        value:"	899	"},
        {label:"	Động cơ xăngLoại động cơ	",
        value:"	1NR-VE (1.3L)	"},
        {label:"	Số xy lanh	",
        value:"	4	"},
        {label:"	Bố trí xy lanh	",
        value:"	Thẳng hàng/In line	"},
        {label:"	Dung tích xy lanh (cc)	",
        value:"	1329	"},
        {label:"	Tỉ số nén	",
        value:"	11,5	"},
        {label:"	Hệ thống nhiên liệu	",
        value:"	Phun xăng điện tử/ Electronic fuel injection	"},
        {label:"	Loại nhiên liệu	",
        value:"	Xăng/Petrol	"},
        {label:"	Công suất tối đa ((KW) HP/ vòng/phút)	",
        value:"	(70)/94/6000	"},
        {label:"	Mô men xoắn tối đa (Nm/vòng/phút)	",
        value:"	119/4200	"},
        {label:"	Tốc độ tối đa	",
        value:"	160	"},
        {label:"	Tiêu chuẩn khí thải	",
        value:"	Euro 4	"},
        {label:"	Hệ thống ngắt/mở động cơ tự động	",
        value:"	Không có/Without	"},
        {label:"	Chế độ lái (công suất cao/tiết kiệm nhiên liệu)	",
        value:"	Không có/Without	"},
        {label:"	Hệ thống truyền động	",
        value:"	Dẫn động cầu sau/RWD	"},
        {label:"	Hộp số	",
        value:"	Số sàn 5 cấp/5MT	"},
        {label:"	Hệ thống treoTrước	",
        value:"	MacPherson Strut	"},
        {label:"	Sau	",
        value:"	Liên kết đa điểm / Five link	"},
        {label:"	Hệ thống láiTrợ lực tay lái	",
        value:"	Điện/Power	"},
        {label:"	Hệ thống tay lái tỉ số truyền biến thiên (VGRS)	",
        value:"	Không có/Without	"},
        {label:"	Vành & lốp xeLoại vành	",
        value:"	Mâm đúc/Alloy	"},
        {label:"	Kích thước lốp	",
        value:"	185/70R14	"},
        {label:"	Lốp dự phòng	",
        value:"	Mâm đúc/Alloy	"},
        {label:"	PhanhTrước	",
        value:"	Đĩa tản nhiệt 13/Ventilated disc 13	"},
        {label:"	Sau	",
        value:"	Tang trống/Drum	"},
        {label:"	Tiêu thụ nhiên liệuTrong đô thị (L/100km)	",
        value:"	8.67	"},
        {label:"	Ngoài đô thị (L/100km)	",
        value:"	5.82	"},
        {label:"	Kết hợp (L/100km)	",
        value:"	6.87	"},
        {label:"	Cụm đèn trước Đèn chiếu gần	",value:"	Halogen phản xạ đa hướng	"},
        {label:"	Đèn chiếu xa	",value:"	Halogen phản xạ đa hướng	"},
        {label:"	Đèn chiếu sáng ban ngày	",value:"	Không có/Without	"},
        {label:"	Hệ thống rửa đèn	",value:"	Không có/Without	"},
        {label:"	Chế độ điều khiển đèn tự động	",value:"	Không có/Without	"},
        {label:"	Hệ thống nhắc nhở đèn sáng	",value:"	Không có/Without	"},
        {label:"	Hệ thống cân bằng đèn pha	",value:"	Không có/Without	"},
        {label:"	Hệ thống cân bằng góc chiếu	",value:"	Không có/Without	"},
        {label:"	Chế độ đèn chờ dẫn đường	",value:"	Không có/Without	"},
        {label:"	Cụm đèn sau Đèn vị trí	",value:"	Có/With	"},
        {label:"	Đèn phanh	",value:"	Có/With	"},
        {label:"	Đèn báo rẽ	",value:"	Có/With	"},
        {label:"	Đèn lùi	",value:"	Có/With	"},
        {label:"	Đèn báo phanh trên cao	",value:"	Không có/Without	"},
        {label:"	Đèn sương mù Trước	",value:"	Có/With	"},
        {label:"	Sau	",value:"	Không có/Without	"},
        {label:"	Gương chiếu hậu ngoài Chức năng điều chỉnh điện	",value:"	Có/With	"},
        {label:"	Chức năng gập điện	",value:"	Không có/Without	"},
        {label:"	Tích hợp đèn chào mừng	",value:"	Không có/Without	"},
        {label:"	Tích hợp đèn báo rẽ	",value:"	Không có/Without	"},
        {label:"	Màu	",value:"	Cùng màu thân xe/Body color	"},
        {label:"	Chức năng tự điều chỉnh khi lùi	",value:"	Không có/Without	"},
        {label:"	Bộ nhớ vị trí	",value:"	Không có/Without	"},
        {label:"	Chức năng sấy gương	",value:"	Không có/Without	"},
        {label:"	Chức năng chống bám nước	",value:"	Không có/Without	"},
        {label:"	Chức năng chống chói tự động	",value:"	Không có/Without	"},
        {label:"	Gạt mưa Trước	",value:"	Gián đoạn/intermittent	"},
        {label:"	Sau	",value:"	Có/With	"},
        {label:"	Chức năng sấy kính sau	",value:"	Có/With	"},
        {label:"	Ăng ten	",value:"	Vây cá/Sharkfin	"},
        {label:"	Tay nắm cửa ngoài	",value:"	Cùng màu thân xe/Body color	"},
        {label:"	Bộ quây xe thể thao	",value:"	Không có/Without	"},
        {label:"	Cản xe Trước	",value:"	Cùng màu thân xe/Colored	"},
        {label:"	Sau	",value:"	Cùng màu thân xe/Colored	"},
        {label:"	Lưới tản nhiệt Trước	",value:"	Sơn bạc/Silver paint	"},
        {label:"	Chắn bùn	",value:"	With/Có	"},
        {label:"	Ống xả kép	",value:"	Không có/Without	"},
        {label:"	Cánh hướng gió nóc xe	",value:"	Không có/Without	"},
        {label:"	Thanh đỡ nóc xe	",value:"	Không có/Without	"},
        {label:"	Tay lái Loại tay lái	",value:"	3 chấu/3-spoke		"},
        {label:"	Chất liệu	",value:"	Urethane		"},
        {label:"	Nút bấm điều khiển tích hợp	",value:"	Không có/Without		"},
        {label:"	Điều chỉnh	",value:"	Chỉnh tay 2 hướng/ Manual tilt		"},
        {label:"	Lẫy chuyển số	",value:"	Không có/Without		"},
        {label:"	Bộ nhớ vị trí	",value:"	Không có/Without		"},
        {label:"	Gương chiếu hậu trong	",value:"	2 chế độ ngày và đêm/Day & night		"},
        {label:"	Tay nắm cửa trong	",value:"	Cùng màu nội thất/Material color		"},
        {label:"	Cụm đồng hồ Loại đồng hồ	",value:"	Analog		"},
        {label:"	Đèn báo Eco	",value:"	Có/With		"},
        {label:"	Chức năng báo lượng tiêu thụ nhiên liệu	",value:"	Không có/Without		"},
        {label:"	Chức năng báo vị trí cần số	",value:"	Không có/Without		"},
        {label:"	Màn hình hiển thị đa thông tin	",value:"	Có/With		"},
        {label:"	Cửa sổ trời	",value:"	Không có/Without		"},
        {label:"	Hệ thống âm thanh Đầu đĩa	",value:"	CD		"},
        {label:"	Số loa	",value:"	4		"},
        {label:"	Cổng kết nối AUX	",value:"	Có/With		"},
        {label:"	Cổng kết nối USB	",value:"	Có/With		"},
        {label:"	Kết nối Bluetooth	",value:"	Có/With		"},
        {label:"	Hệ thống điều khiển bằng giọng nói	",value:"	Không có/Without		"},
        {label:"	Bảng điều khiển từ hàng ghế sau	",value:"	Không có/Without		"},
        {label:"	Kết nối wifi	",value:"	Không có/Without		"},
        {label:"	Hệ thống đàm thoại rảnh tay	",value:"	Có/With		"},
        {label:"	Kết nối điện thoại thông minh	",value:"	Không có/Without		"},
        {label:"	Kết nối HDMI	",value:"	Không có/Without		"},
        {label:"	Hệ thống điều hòa (Tự động/Auto)	",value:"	Chỉnh tay/Manual		"},
        {label:"	Hệ thống sạc không dây	",value:"	Không có/Without		"},
        {label:"	Chất liệu bọc ghế	",value:"	Nỉ/Fabric	"},
        {label:"	Ghế trước Loại ghế	",value:"	Thường/Normal	"},
        {label:"	Điều chỉnh ghế lái	",value:"	Chỉnh tay 4 hướng/4 way manual	"},
        {label:"	Điều chỉnh ghế hành khách	",value:"	Chỉnh tay 4 hướng/4 way manual	"},
        {label:"	Bộ nhớ vị trí	",value:"	Không có/Without	"},
        {label:"	Chức năng thông gió	",value:"	Không có/Without	"},
        {label:"	Chức năng sưởi	",value:"	Không có/Without	"},
        {label:"	Ghế sau Hàng ghế thứ hai	",value:"	Gập thẳng 50:50 1 chạm/Tumble 50:50 1 touch	"},
        {label:"	Hàng ghế thứ ba	",value:"	Gập thẳng 50:50/Tumble 50:50	"},
        {label:"	Hàng ghế thứ bốn	",value:"	Không có/Without	"},
        {label:"	Hàng ghế thứ năm	",value:"	Không có/Without	"},
        {label:"	Rèm che nắng kính sau	",value:"	Không có/Without	"},
        {label:"	Rèm che nắng cửa sau	",value:"	Không có/Without	"},
        {label:"	Cửa gió sau	",value:"	Có/With	"},
        {label:"	Hộp làm mát	",value:"	Không có/Without	"},
        {label:"	Chìa khóa thông minh & Khởi động bằng nút bấm	",value:"	Không có/Without	"},
        {label:"	Khóa cửa điện	",value:"	Có/With	"},
        {label:"	Chức năng khóa cửa từ xa	",value:"	Có/With	"},
        {label:"	Phanh tay điện tử	",value:"	Không có/Without	"},
        {label:"	Cửa sổ điều chỉnh điện	",value:"	Có, chống kẹt cửa lái/ With, D jam protection	"},
        {label:"	Cốp điều khiển điện	",value:"	Không có/Without	"},
        {label:"	Ga tự động	",value:"	Không có/Without	"},
        {label:"	Hệ thống kiểm soát hành trình	",value:"	Không có/Without	"},
        {label:"	Hệ thống báo động	",value:"	Không có/Without	"},
        {label:"	Hệ thống mã hóa khóa động cơ	",value:"	Không có/Without	"},
        {label:"	Hệ thống chống bó cứng phanh (ABS)	",value:"	Có/With	"},
        {label:"	Hệ thống hỗ trợ lực phanh khẩn cấp (BA)	",value:"	Không có/Without	"},
        {label:"	Hệ thống phân phối lực phanh điện tử (EBD)	",value:"	Có/With	"},
        {label:"	Hệ thống ổn định thân xe	",value:"	Không có/Without	"},
        {label:"	Hệ thống kiểm soát lực kéo chủ động (A-TRC)	",value:"	Không có/Without	"},
        {label:"	Hệ thống hỗ trợ khởi hành ngang dốc (HAC)	",value:"	Không có/Without	"},
        {label:"	Giữ phanh	",value:"	Không có/Without	"},
        {label:"	Hệ thống lựa chọn vận tốc vượt địa hình	",value:"	Không có/Without	"},
        {label:"	Hệ thống lựa chọn đa địa hình (MTS)	",value:"	Không có/Without	"},
        {label:"	Đèn báo phanh khẩn cấp (EBS)	",value:"	Không có/Without	"},
        {label:"	Camera lùi	",value:"	Không có/Without	"},
        {label:"	Cảm biến hỗ trợ đỗ xe Sau	",value:"	0	"},
        {label:"	Góc trước	",value:"	0	"},
        {label:"	Góc sau	",value:"	0	"},
        {label:"	Túi khí Túi khí người lái & hành khách phía trước	",value:"	Có/With	"},
        {label:"	Túi khí bên hông phía trước	",value:"	Không có/Without	"},
        {label:"	Túi khí rèm	",value:"	Không có/Without	"},
        {label:"	Túi khí bên hông phía sau	",value:"	Không có/Without	"},
        {label:"	Túi khí đầu gối người lái	",value:"	Không có/Without	"},
        {label:"	Túi khí đầu gối hành khách	",value:"	Không có/Without	"},
        {label:"	Khung xe GOA	",value:"	Có/ With	"},
        {label:"	Dây đai an toàn Trước	",value:"	3 điểm ELR, 7 vị trí/ 3 points ELRx7	"},
        {label:"	Ghế có cấu trúc giảm chấn thương cổ	",value:"	Có/With	"},
        {label:"	Cột lái tự đổ	",value:"	Có/With	"},
        {label:"	Bàn đạp phanh tự đổ	",value:"	Có/With	"}
      ]
    },
    {
      brand: 'Toyota Avanza AT',
      price: 612000000,
      lingo: 'Mang yêu thương cho mỗi hành trình',
      seats: 7,
      type: 'Đa dụng',
      fuelType: 'Xăng',
      manufacture: 'Xe nhập khẩu',
      otherInfo: ['Số tự động 4 cấp'],
      library:[
        '/assets/img/toyota/avanza/AT/library/hpr4tt.jpg',
        '/assets/img/toyota/avanza/AT/library/xwfgld.jpg',
        '/assets/img/toyota/avanza/AT/library/zc3wqa.jpg',
        '/assets/img/toyota/avanza/AT/library/nl1nql.jpg'
      ],
      colors:[
        {
          label:'Bạc - 1E7',
          image:'/assets/img/toyota/avanza/colors/AT/mauxe_600x249_bac.png',
          colorCode: '#dedfe1'
        },
        {
          label:'Xanh sẫm - B79',
          image:'/assets/img/toyota/avanza/colors/AT/mauxe_600x249_blue.jpg',
          colorCode: '#133368'
        },
        {
          label:'Vàng - T23',
          image:'/assets/img/toyota/avanza/colors/AT/mauxe_600x249_yellow.jpg',
          colorCode: '#cfcbc1'
        },
        {
          label:'Trắng - W09',
          image:'/assets/img/toyota/avanza/colors/AT/mauxe_600x249_white.jpg',
          colorCode: 'white'
        },
        {
          label:'Xám - 1G3',
          image:'/assets/img/toyota/avanza/colors/AT/mauxe_600x249_den.jpg',
          colorCode: '#94989b'
        },
        {
          label:'Đen - X12',
          image:'/assets/img/toyota/avanza/colors/AT/den-2.png',
          colorCode: 'black'
        }
      ],
      ngoaiThat: {
        label: 'DIỆN MẠO THỂ THAO, NĂNG ĐỘNG',
        backgroundImage: '/assets/img/toyota/wigo/ngoai-that/0.png',
        image: '/assets/img/toyota/avanza/AT/ngoai-that/luynyv.jpg',
        features: [
          {
            image: '/assets/img/toyota/avanza/AT/ngoai-that/0grdsc.jpg',
            label: 'Cụm đèn trước'
          },
          {
            image: '/assets/img/toyota/avanza/AT/ngoai-that/5tuoo0.jpg',
            label: 'Cánh hướng gió sau'
          },
          {
            image: '/assets/img/toyota/avanza/AT/ngoai-that/55ymmq.jpg',
            label: 'Đuôi xe'
          },
          {
            image: '/assets/img/toyota/avanza/AT/ngoai-that/tktlxp.jpg',
            label: 'Gương chiếu hậu'
          },
          {
            image: '/assets/img/toyota/avanza/AT/ngoai-that/uelewj.jpg',
            label: 'Cụm đèn sau'
          },
          {
            image: '/assets/img/toyota/avanza/AT/ngoai-that/wlt5cb.jpg',
            label: 'Mâm xe'
          },
          {
            image: '/assets/img/toyota/avanza/AT/ngoai-that/yuc00z.jpg',
            label: 'Đèn sương mù'
          }
        ]
      },
      tinhNang:[
        {
          image: "/assets/img/toyota/avanza/AT/tinh-nang/uxiqfd.jpg",
          title: "Bán kính vòng quay",
          message: "Bán kính vòng quay tối thiểu nhỏ - 4.7m cho phép xe chuyển động linh hoạt trên mọi cung đường."
        },
        {
          image: "/assets/img/toyota/avanza/AT/tinh-nang/kgibs5.jpg",
          title: "Hệ thống chống bó cứng phanh (ABS)",
          message: "ABS giúp các bánh xe không bị bó cứng khi phanh gấp hay phanh trên đường trơn trượt, đảm bảo an toàn cho người lái và hành khách trên xe."
        },
        {
          image: "/assets/img/toyota/avanza/AT/tinh-nang/rxzj13.jpg",
          title: "Hệ thống treo trước",
          message: "Hệ thống treo trước giúp xe vận hành êm dịu và đảm bảo bộ bám đường cho bánh xe."
        },
        {
          image: "/assets/img/toyota/avanza/AT/tinh-nang/yv2pfc.jpg",
          title: "Hệ thống phân phối lực phanh điện",
          message: "Hệ thống phân phối lực phanh điện tử EBD phân bố lực phanh hợp lý đến các bánh xe, giúp nâng cao hiệu quả phanh, đặc biệt khi xe đang chất tải và cào cua."
        },
        {
          image: "/assets/img/toyota/avanza/AT/tinh-nang/yzw2p2.jpg",
          title: "Hộp số",
          message: "Hộp số tự động 4 cấp (1.5 AT) và số sàn 5 cấp (1.3 MT) vận hành mượt mà."
        },
        {
          image: "/assets/img/toyota/avanza/AT/tinh-nang/zv5swb.jpg",
          title: "Động cơ",
          message: "Động cơ WT - i kép cho hiệu suất cao, tiết kiệm nhiên liệu và thân thiện với môi trường."
        }
      ],
      thongSo: [
        {label:"	ích thướcKích thước tổng thể bên ngoài (D x R x C) (mm x mm x mm)	",
        value:"	4190 x 1660 x 1740	"},
        {label:"	Kích thước tổng thể bên trong (D x R x C) (mm x mm x mm)	",
        value:"	2480 x 1415 x 1270	"},
        {label:"	Chiều dài cơ sở (mm)	",
        value:"	2655	"},
        {label:"	Chiều rộng cơ sở (Trước/sau) (mm)	",
        value:"	1425/1435	"},
        {label:"	Khoảng sáng gầm xe (mm)	",
        value:"	200	"},
        {label:"	Bán kính vòng quay tối thiểu (m)	",
        value:"	4,7	"},
        {label:"	Trọng lượng không tải (kg)	",
        value:"	1160	"},
        {label:"	Trọng lượng toàn tải (kg)	",
        value:"	1700	"},
        {label:"	Dung tích bình nhiên liệu (L)	",
        value:"	45	"},
        {label:"	Dung tích khoang hành lý (L)	",
        value:"	899	"},
        {label:"	Động cơ xăngLoại động cơ	",
        value:"	2NR-VE (1.5L)	"},
        {label:"	Số xy lanh	",
        value:"	4	"},
        {label:"	Bố trí xy lanh	",
        value:"	Thẳng hàng/In line	"},
        {label:"	Dung tích xy lanh (cc)	",
        value:"	1496	"},
        {label:"	Tỉ số nén	",
        value:"	11,5	"},
        {label:"	Hệ thống nhiên liệu	",
        value:"	Phun xăng điện tử/ Electronic fuel injection	"},
        {label:"	Loại nhiên liệu	",
        value:"	Xăng/Petrol	"},
        {label:"	Công suất tối đa ((KW) HP/ vòng/phút)	",
        value:"	(76)102/6000	"},
        {label:"	Mô men xoắn tối đa (Nm/vòng/phút)	",
        value:"	134/4200	"},
        {label:"	Tốc độ tối đa	",
        value:"	160	"},
        {label:"	Tiêu chuẩn khí thải	",
        value:"	Euro 4	"},
        {label:"	Hệ thống ngắt/mở động cơ tự động	",
        value:"	Không có/Without	"},
        {label:"	Chế độ lái (công suất cao/tiết kiệm nhiên liệu)	",
        value:"	Không có/Without	"},
        {label:"	Hệ thống truyền động	",
        value:"	Dẫn động cầu sau/RWD	"},
        {label:"	Hộp số	",
        value:"	Số tự động 4 cấp/4AT	"},
        {label:"	Hệ thống treoTrước	",
        value:"	MacPherson Strut	"},
        {label:"	Sau	",
        value:"	Liên kết đa điểm / Five link	"},
        {label:"	Hệ thống láiTrợ lực tay lái	",
        value:"	Điện/Power	"},
        {label:"	Hệ thống tay lái tỉ số truyền biến thiên (VGRS)	",
        value:"	Không có/Without	"},
        {label:"	Vành & lốp xeLoại vành	",
        value:"	Mâm đúc/Alloy	"},
        {label:"	Kích thước lốp	",
        value:"	185/65R15	"},
        {label:"	Lốp dự phòng	",
        value:"	Mâm đúc/Alloy	"},
        {label:"	PhanhTrước	",
        value:"	Đĩa tản nhiệt 13/Ventilated disc 13"},
        {label:"	Sau	",
        value:"	Tang trống/Drum	"},
        {label:"	Tiêu thụ nhiên liệuTrong đô thị (L/100km)	",
        value:"	9.96	"},
        {label:"	Ngoài đô thị (L/100km)	",
        value:"	6.43	"},
        {label:"	Kết hợp (L/100km)	",
        value:"	7.73	"},
        {label:"	Cụm đèn trước Đèn chiếu gần	",value:"	LED	"},
        {label:"	Đèn chiếu xa	",value:"	LED	"},
        {label:"	Đèn chiếu sáng ban ngày	",value:"	Không có/Without	"},
        {label:"	Hệ thống rửa đèn	",value:"	Không có/Without	"},
        {label:"	Chế độ điều khiển đèn tự động	",value:"	Không có/Without	"},
        {label:"	Hệ thống nhắc nhở đèn sáng	",value:"	Có/With	"},
        {label:"	Hệ thống cân bằng đèn pha	",value:"	Không có/Without	"},
        {label:"	Hệ thống cân bằng góc chiếu	",value:"	Không có/Without	"},
        {label:"	Chế độ đèn chờ dẫn đường	",value:"	Không có/Without	"},
        {label:"	Cụm đèn sau Đèn vị trí	",value:"	Halogen	"},
        {label:"	Đèn phanh	",value:"	Halogen	"},
        {label:"	Đèn báo rẽ	",value:"	Halogen	"},
        {label:"	Đèn lùi	",value:"	Halogen	"},
        {label:"	Đèn báo phanh trên cao	",value:"	LED	"},
        {label:"	Đèn sương mù Trước	",value:"	Có/With	"},
        {label:"	Sau	",value:"	Không có/Without	"},
        {label:"	Gương chiếu hậu ngoài Chức năng điều chỉnh điện	",value:"	Có/With	"},
        {label:"	Chức năng gập điện	",value:"	Có/With	"},
        {label:"	Tích hợp đèn chào mừng	",value:"	Không có/Without	"},
        {label:"	Tích hợp đèn báo rẽ	",value:"	Không có/Without	"},
        {label:"	Màu	",value:"	Cùng màu thân xe/Body color	"},
        {label:"	Chức năng tự điều chỉnh khi lùi	",value:"	Không có/Without	"},
        {label:"	Bộ nhớ vị trí	",value:"	Không có/Without	"},
        {label:"	Chức năng sấy gương	",value:"	Không có/Without	"},
        {label:"	Chức năng chống bám nước	",value:"	Không có/Without	"},
        {label:"	Chức năng chống chói tự động	",value:"	Không có/Without	"},
        {label:"	Gạt mưa Trước	",value:"	Gián đoạn/intermittent	"},
        {label:"	Sau	",value:"	Có/With	"},
        {label:"	Chức năng sấy kính sau	",value:"	Có/With	"},
        {label:"	Ăng ten	",value:"	Vây cá/Sharkfin	"},
        {label:"	Tay nắm cửa ngoài	",value:"	Cùng màu thân xe/Body color	"},
        {label:"	Bộ quây xe thể thao	",value:"	Không có/Without	"},
        {label:"	Thanh cản (giảm va chạm) Trước	",value:"	Cùng màu thân xe/Colored	"},
        {label:"	Sau	",value:"	Cùng màu thân xe/Colored	"},
        {label:"	Lưới tản nhiệt Trước	",value:"	Mạ chrome/Chrome	"},
        {label:"	Chắn bùn	",value:"	Không có/Without	"},
        {label:"	Chắn bùn bên	",value:"	Có/With	"},
        {label:"	Ống xả kép	",value:"	Không có/Without	"},
        {label:"	Cánh hướng gió nóc xe	",value:"	Có/With	"},
        {label:"	Thanh đỡ nóc xe	",value:"	Không có/Without	"},
        {label:"	Tay láiLoại tay lái	",
        value:"	3 chấu/3-spoke	"},
        {label:"	Chất liệu	",
        value:"	Urethane	"},
        {label:"	Nút bấm điều khiển tích hợp	",
        value:"	Âm thanh/Audio	"},
        {label:"	Điều chỉnh	",
        value:"	Chỉnh tay 2 hướng/ Manual tilt	"},
        {label:"	Lẫy chuyển số	",
        value:"	Không có/Without	"},
        {label:"	Bộ nhớ vị trí	",
        value:"	Không có/Without	"},
        {label:"	Gương chiếu hậu trong	",
        value:"	2 chế độ ngày và đêm/Day & night	"},
        {label:"	Tay nắm cửa trong	",
        value:"	Cùng màu nội thất/Material color	"},
        {label:"	Cụm đồng hồLoại đồng hồ	",
        value:"	Analog	"},
        {label:"	Đèn báo Eco	",
        value:"	Có/With	"},
        {label:"	Chức năng báo lượng tiêu thụ nhiên liệu	",
        value:"	Không có/Without	"},
        {label:"	Chức năng báo vị trí cần số	",
        value:"	Có/With	"},
        {label:"	Màn hình hiển thị đa thông tin	",
        value:"	Có/With	"},
        {label:"	Cửa sổ trời	",
        value:"	Không có/Without	"},
        {label:"	Hệ thống âm thanhĐầu đĩa	",
        value:"	DVD 7	"},
        {label:"	Số loa	",
        value:"	6	"},
        {label:"	Cổng kết nối AUX	",
        value:"	Không có/Without	"},
        {label:"	Cổng kết nối USB	",
        value:"	Có/With	"},
        {label:"	Kết nối Bluetooth	",
        value:"	Có/With	"},
        {label:"	Hệ thống điều khiển bằng giọng nói	",
        value:"	Không có/Without	"},
        {label:"	Bảng điều khiển từ hàng ghế sau	",
        value:"	Không có/Without	"},
        {label:"	Kết nối wifi	",
        value:"	Không có/Without	"},
        {label:"	Hệ thống đàm thoại rảnh tay	",
        value:"	Có/With	"},
        {label:"	Kết nối điện thoại thông minh	",
        value:"	Có/With	"},
        {label:"	Kết nối HDMI	",
        value:"	Không có/Without	"},
        {label:"	Hệ thống điều hòaTrước	",
        value:"	Chỉnh tay, dạng nút bấm/Manual, push button	"},
        {label:"	Hệ thống sạc không dây	",
        value:"	Không có/Without	"},
        {label:"	Chất liệu bọc ghế	",value:"	Nỉ/Fabric	"},
        {label:"	Ghế trước Loại ghế	",value:"	Thường/Normal	"},
        {label:"	Điều chỉnh ghế lái	",value:"	Chỉnh tay 4 hướng/4 way manual	"},
        {label:"	Điều chỉnh ghế hành khách	",value:"	Chỉnh tay 4 hướng/4 way manual	"},
        {label:"	Bộ nhớ vị trí	",value:"	Không có/Without	"},
        {label:"	Chức năng thông gió	",value:"	Không có/Without	"},
        {label:"	Chức năng sưởi	",value:"	Không có/Without	"},
        {label:"	Ghế sau Hàng ghế thứ hai	",value:"	Gập thẳng 50:50 1 chạm/Tumble 50:50 1 touch	"},
        {label:"	Hàng ghế thứ ba	",value:"	Gập thẳng 50:50/Tumble 50:50	"},
        {label:"	Hàng ghế thứ bốn	",value:"	Không có/Without	"},
        {label:"	Hàng ghế thứ năm	",value:"	Không có/Without	"},
        {label:"	Rèm che nắng kính sau	",value:"	Không có/Without	"},
        {label:"	Rèm che nắng cửa sau	",value:"	Không có/Without	"},
        {label:"	Cửa gió sau	",value:"	Có/With	"},
        {label:"	Hộp làm mát	",value:"	Không có/Without	"},
        {label:"	Chìa khóa thông minh & Khởi động bằng nút bấm	",value:"	Không có/Without	"},
        {label:"	Khóa cửa điện	",value:"	Có/With	"},
        {label:"	Chức năng khóa cửa từ xa	",value:"	Có/With	"},
        {label:"	Phanh tay điện tử	",value:"	Không có/Without	"},
        {label:"	Hệ thống dẫn đường	",value:"	Không có/Without	"},
        {label:"	Hiển thị thông tin trên kính lái	",value:"	Không có/Without	"},
        {label:"	Cửa sổ điều chỉnh điện	",value:"	Có, chống kẹt cửa lái/With, D jam protection	"},
        {label:"	Cốp điều khiển điện	",value:"	Không có/Without	"},
        {label:"	Ga tự động	",value:"	Không có/Without	"},
        {label:"	Hệ thống kiểm soát hành trình	",value:"	Không có/Without	"},
        {label:"	Hệ thống báo động	",value:"	Có/With	"},
        {label:"	Hệ thống mã hóa khóa động cơ	",value:"	Không có/Without	"},
        {label:"	Hệ thống chống bó cứng phanh (ABS)	",value:"	Có/With	"},
        {label:"	Hệ thống hỗ trợ lực phanh khẩn cấp (BA)	",value:"	Không có/Without	"},
        {label:"	Hệ thống phân phối lực phanh điện tử (EBD)	",value:"	Có/With	"},
        {label:"	Hệ thống ổn định thân xe	",value:"	Không có/Without	"},
        {label:"	Hệ thống kiểm soát lực kéo chủ động (A-TRC)	",value:"	Không có/Without	"},
        {label:"	Hệ thống hỗ trợ khởi hành ngang dốc (HAC)	",value:"	Không có/Without	"},
        {label:"	Hệ thống lựa chọn vận tốc vượt địa hình	",value:"	Không có/Without	"},
        {label:"	Hệ thống lựa chọn đa địa hình (MTS)	",value:"	Không có/Without	"},
        {label:"	Đèn báo phanh khẩn cấp (EBS)	",value:"	Không có/Without	"},
        {label:"	Camera lùi	",value:"	Không có/Without	"},
        {label:"	Cảm biến hỗ trợ đỗ xe Sau	",value:"	0	"},
        {label:"	Góc trước	",value:"	0	"},
        {label:"	Góc sau	",value:"	0	"},
        {label:"		",value:"		"},
        {label:"	Túi khí Túi khí người lái & hành khách phía trước	",value:"	Có/With	"},
        {label:"	Túi khí bên hông phía trước	",value:"	Không có/Without	"},
        {label:"	Túi khí rèm	",value:"	Không có/Without	"},
        {label:"	Túi khí bên hông phía sau	",value:"	Không có/Without	"},
        {label:"	Túi khí đầu gối người lái	",value:"	Không có/Without	"},
        {label:"	Túi khí đầu gối hành khách	",value:"	Không có/Without	"},
        {label:"	Khung xe GOA	",value:"	Có/ With	"},
        {label:"	Dây đai an toàn Trước	",value:"	3 điểm ELR, 7 vị trí/ 3 points ELRx7	"},
        {label:"	Ghế có cấu trúc giảm chấn thương cổ	",value:"	Có/With	"},
        {label:"	Cột lái tự đổ	",value:"	Có/With	"},
        {label:"	Bàn đạp phanh tự đổ	",value:"	Có/With	"}
      ]

    }
  ]
}
